Repository DataDog/dd-trace-php, pull requests merged in 2018-07, with the labels that each got.

#32 README example code doesn't work without also using OpenTracing\GlobalTracer
  README.md
Labels: docs

#41 Report Tests and Linting using JUnit reporter so that CircleCI can better help pinpointing failed tests/lints
  .circleci/config.yml
  .editorconfig
  .phpcs.xml
  README.md
Labels: ci, enhancement

#43 First cut at a Stdout transport for debugging
  src/DDTrace/Transport/Stream.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/Transport/StreamTest.php
Labels: core
