Repository DataDog/dd-trace-php, pull requests merged in 2018-11, with the labels that each got.

#95 Symfony add service type and resource name to root span
  src/DDTrace/Integrations/SymfonyBundle.php
Labels: enhancement

#88 Add Memcached integration tests
  .circleci/config.yml
  docker-compose.yml
  tests/Integration/Common/IntegrationTestCase.php
  tests/Integration/Integrations/MemcachedTest.php
Labels: dev/testing

#103 Update composer.json
  composer.json
Labels: community, core

#112 Laravel: Prevent traces not sent when app name is empty
  src/DDTrace/Integrations/LaravelProvider.php
Labels: community, integrations

#110 Extend Predis integration tests coverage
  .circleci/config.yml
  src/DDTrace/Integrations/Predis.php
  src/DDTrace/Types.php
  tests/Integration/Common/SpanChecker.php
  tests/Integration/Integrations/PredisTest.php
Labels: dev/testing

#117 Improve laravel pipeline tracing
  src/DDTrace/Integrations/LaravelProvider.php
Labels: bug, do-not-merge/WIP, integrations

#97 Bugfixes for PHP 5.6
  DDMakefile
  docker-compose.yml
  dockerfiles/debug_php-5.6/Dockerfile
  src/ext/debug.h
  src/ext/dispatch.c
  src/ext/dispatch_compat_php5.c
  tests/Integration/Integrations/MemcachedTest.php
  tests/Integration/Integrations/PDOTest.php
  tests/Integration/Integrations/PredisTest.php
Labels: core

#123 Bump version to v0.3.0-beta
  src/DDTrace/Version.php
Labels: core

#121 Move integrations to their own packages
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Integrations/LaravelProvider.php
  src/DDTrace/Integrations/Memcached.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Integrations/SymfonyBundle.php
  tests/Integration/Frameworks/Laravel/Version_4_2/bootstrap/compiled.php
  tests/Integration/Integrations/Memcached/MemcachedTest.php
  tests/Integration/Integrations/Mysqli/MysqliTest.php
  tests/Integration/Integrations/PDO/PDOTest.php
  tests/Integration/Integrations/Predis/PredisTest.php
Labels: core

#128 Bump version 0.3.1
  src/DDTrace/Version.php
Labels: core

#131 Bump version 0.4.0
  src/DDTrace/Version.php
Labels: core

#129 Symfony exception handling and meta tags for request
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
Labels: community, integrations

#126 Support tracing calling internal functions
  docker-compose.yml
  dockerfiles/ubuntu-16.04-php-7.1/Dockerfile
  src/ext/debug.h
  src/ext/dispatch.c
  src/ext/dispatch_setup.c
Labels: core

#136 Support for Eloquent 4.2
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
Labels: bug, integrations

#134 Update getting_started.md
  docs/getting_started.md
Labels: community, docs

#132 Add key obfuscation to Memcached integration
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Obfuscation.php
  tests/Integration/Integrations/Memcached/MemcachedTest.php
  tests/Unit/ObfuscationTest.php
Labels: bug, integrations

#138 Bump version 0.4.1
  src/DDTrace/Version.php
Labels: core

#139 Laravel 4.2 and 5.7 basic Integration Tests with multi-framework testing infrastructure
  .circleci/config.yml
  composer.json
  docker-compose.yml
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  tests/Integration/Common/IntegrationTestCase.php
  tests/Integration/Common/SpanAssertion.php
  tests/Integration/Common/SpanAssertionTrait.php
  tests/Integration/Common/SpanChecker.php
  tests/Integration/Common/TracerTestTrait.php
  tests/Integration/Frameworks/Laravel/Version_4_2/.gitignore
  tests/Integration/Frameworks/Laravel/Version_4_2/app/config/app.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/controllers/BaseController.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/controllers/HomeController.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/routes.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/tests/ExampleTest.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/tests/Integration/CommonScenariosTest.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/tests/TestCase.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/views/emails/auth/reminder.blade.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/views/hello.php
  tests/Integration/Frameworks/Laravel/Version_4_2/app/views/simple_view.php
  tests/Integration/Frameworks/Laravel/Version_4_2/bootstrap/autoload.php
  tests/Integration/Frameworks/Laravel/Version_4_2/bootstrap/compiled.php
  tests/Integration/Frameworks/Laravel/Version_4_2/composer.json
  tests/Integration/Frameworks/Laravel/Version_4_2/phpunit.xml
  tests/Integration/Frameworks/Laravel/Version_5_7/.gitignore
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Auth/ForgotPasswordController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Auth/LoginController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Auth/RegisterController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Auth/ResetPasswordController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Auth/VerificationController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/CommonSpecsController.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Controllers/Controller.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Kernel.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/.gitkeep
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/Authenticate.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/CheckForMaintenanceMode.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/EncryptCookies.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/RedirectIfAuthenticated.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/TrimStrings.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/TrustProxies.php
  tests/Integration/Frameworks/Laravel/Version_5_7/app/Http/Middleware/VerifyCsrfToken.php
  tests/Integration/Frameworks/Laravel/Version_5_7/composer.json
  tests/Integration/Frameworks/Laravel/Version_5_7/config/app.php
  tests/Integration/Frameworks/Laravel/Version_5_7/phpunit.xml
  tests/Integration/Frameworks/Laravel/Version_5_7/resources/views/simple_view.blade.php
  tests/Integration/Frameworks/Laravel/Version_5_7/resources/views/welcome.blade.php
  tests/Integration/Frameworks/Laravel/Version_5_7/routes/api.php
  tests/Integration/Frameworks/Laravel/Version_5_7/routes/web.php
  tests/Integration/Frameworks/Laravel/Version_5_7/tests/Feature/ExampleTest.php
  tests/Integration/Frameworks/Laravel/Version_5_7/tests/Integration/CommonScenariosTest.php
  tests/Integration/Frameworks/Laravel/Version_5_7/tests/TestCase.php
  tests/Integration/Frameworks/Laravel/Version_5_7/tests/Unit/ExampleTest.php
  tests/Integration/Frameworks/TestScenarios.php
  tests/Integration/Frameworks/Util/CommonScenariosDataProviderTrait.php
  tests/Integration/Frameworks/Util/Request/GetSpec.php
  tests/Integration/Frameworks/Util/Request/RequestSpec.php
Labels: dev/testing

#142 Use the HttpFoundation method to get the status code
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
Labels: bug, integrations

#143 SymfonyBundle: Use getenv() to get env variable
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
Labels: community, integrations

#146 bump version 0.4.2
  src/DDTrace/Version.php
Labels: core

#125 Ignore closure for laravel
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
Labels: bug, community, integrations

#147 Curl integration
  .circleci/config.yml
  docker-compose.yml
  src/DDTrace/Http/Urls.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  tests/Integration/Integrations/Curl/CurlIntegrationTest.php
  tests/Unit/Http/UrlsTest.php
Labels: integrations

#145 Distributed tracing, no sampling priority
  composer.json
  src/DDTrace/Http/Headers.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/StartSpanOptionsFactory.php
  src/DDTrace/Tracer.php
  tests/Unit/BaseTestCase.php
  tests/Unit/Http/HeadersTest.php
  tests/Unit/StartSpanOptionsFactoryTest.php
Labels: core

#63 [ext/ddtrace] Add branding on PHP info output
  src/ext/ddtrace.c
  src/ext/ddtrace.h
Labels: core

#148 [Integration] Add Guzzle v5 integration
  composer.json
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
  src/DDTrace/Integrations/Integration.php
  tests/Integration/Integrations/Guzzle/v5/GuzzleIntegrationTest.php
Labels: integrations

#152 Initial changelog file containing information about all previous releases
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/changelog.md
Labels: docs

#155 Tracer returning DDTrace\NoopSpan when in noop mode
  CHANGELOG.md
  src/DDTrace/NoopSpan.php
  src/DDTrace/Span.php
  src/DDTrace/SpanInterface.php
  src/DDTrace/Tracer.php
  tests/Unit/TracerTest.php
Labels: bug, core

#158 Laravel pipelines tracer supporting configurable handler method.
  .composer/.gitignore
  CHANGELOG.md
  docker-compose.yml
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  tests/Integration/Frameworks/Laravel/Version_5_7/tests/Integration/PipelineTracingTest.php
Labels: bug, integrations
