Repository DataDog/dd-trace-php, pull requests merged in 2018-12, with the labels that each got.

#161 Guzzle and Curl enabling for Laravel integrations
  CHANGELOG.md
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
Labels: integrations

#160 Possibility to enable/disable distributed tracing and priority sampling
  CHANGELOG.md
  src/DDTrace/Configuration.php
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/Configuration/EnvVariableRegistry.php
  src/DDTrace/Configuration/Registry.php
  src/DDTrace/StartSpanOptionsFactory.php
  tests/Unit/BaseTestCase.php
  tests/Unit/Configuration/EnvVariableRegistryTest.php
  tests/Unit/StartSpanOptionsFactoryTest.php
Labels: core

#167 Propagate distributed tracing
  CHANGELOG.md
  composer.json
  phpunit.xml
  src/DDTrace/Formats.php
  src/DDTrace/Http/Headers.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
  src/DDTrace/Propagator.php
  src/DDTrace/Propagators/CurlHeadersMap.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/Tracer.php
  src/DDTrace/Util/ArrayKVStore.php
  tests/DDTestListener.php
  tests/Integration/Frameworks/Laravel/Version_4_2/composer.json
  tests/Integration/Frameworks/Laravel/Version_5_7/composer.json
  tests/Integration/Integrations/Curl/CurlIntegrationTest.php
  tests/Integration/Integrations/Guzzle/v5/GuzzleIntegrationTest.php
  tests/Unit/BaseTestCase.php
  tests/Unit/Http/HeadersTest.php
  tests/Unit/Propagators/CurlHeadersMapTest.php
  tests/Unit/Util/ArrayKVStoreTest.php
Labels: core

#168 Let autoload all integrations and disable specific ones
  CHANGELOG.md
  docs/getting_started.md
  src/DDTrace/Configuration.php
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/Configuration/EnvVariableRegistry.php
  src/DDTrace/Configuration/Registry.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/StartSpanOptionsFactory.php
  tests/Integration/Integrations/Curl/CurlIntegrationTest.php
  tests/Integration/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integration/Integrations/Guzzle/v5/GuzzleIntegrationTest.php
  tests/Integration/Integrations/Memcached/MemcachedTest.php
  tests/Integration/Integrations/Mysqli/MysqliTest.php
  tests/Integration/Integrations/PDO/PDOTest.php
  tests/Integration/Integrations/Predis/PredisTest.php
  tests/Unit/Configuration/EnvVariableRegistryTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
Labels: core

#169 Add priority sampling
  CHANGELOG.md
  src/DDTrace/Encoders/Json.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
  src/DDTrace/Propagator.php
  src/DDTrace/Propagators/CurlHeadersMap.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/Sampling/AlwaysKeepSampler.php
  src/DDTrace/Sampling/PrioritySampling.php
  src/DDTrace/Sampling/Sampler.php
  src/DDTrace/Span.php
  src/DDTrace/SpanContext.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  tests/Integration/Common/TracerTestTrait.php
  tests/Integration/Integrations/Curl/CurlIntegrationTest.php
  tests/Integration/Integrations/Guzzle/v5/GuzzleIntegrationTest.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Propagators/CurlHeadersMapTest.php
  tests/Unit/Propagators/TextMapTest.php
  tests/Unit/Sampling/AlwaysKeepSamplerTest.php
  tests/Unit/Sampling/PrioritySamplingTest.php
  tests/Unit/SpanTest.php
  tests/Unit/TracerTest.php
Labels: core

#170 Bump version 0.7.0
  CHANGELOG.md
  src/DDTrace/Version.php
  src/ext/version.h
Labels: core

#174 Add better instructions for installing the extension
  README.md
Labels: docs

#180 Add loose support for Lumen
  CHANGELOG.md
  docs/getting_started.md
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
Labels: integrations

#184 Update symfony 3/4 docs
  docs/getting_started.md
Labels: docs

#188 Verify packages for manually installed php on centos
  .circleci/config.yml
  CHANGELOG.md
  docker-compose.yml
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/centos7-compiled/Dockerfile
  package/post-install.sh
Labels: bug, core

#190 Fix deprecated style of ini comments and avoid failing alpine builds on non errors
  dockerfiles/verify_packages/Makefile
  package/post-install.sh
Labels: core

#194 Make php code 5.4 compatible
  .circleci/config.yml
  .phpcs.xml
  CHANGELOG.md
  src/DDTrace/Encoders/Json.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Scope.php
  src/DDTrace/Util/TryCatchFinally.php
  tests/Integration/Integrations/Mysqli/MysqliTest.php
  tests/Integration/Integrations/Predis/PredisTest.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/Unit/ScopeTest.php
  tests/Unit/SpanTest.php
  tests/Unit/TraceOverrideMethodTest.php
  tests/Unit/TracerTest.php
  tests/Unit/Util/TryCatchFinallyTest.php
Labels: core

#196 [docs] Fix usage example in readme
  README.md
Labels: docs

#201 Add "Instrumentation" section to the getting-started docs
  README.md
Labels: docs

#204 Replace hex string ID's with unsigned-63-bit ints
  CHANGELOG.md
  src/DDTrace/Encoders/Json.php
  src/DDTrace/SpanContext.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Propagators/CurlHeadersMapTest.php
  tests/Unit/Propagators/TextMapTest.php
Labels: bug
