Repository DataDog/dd-trace-php, pull requests merged in 2018-10, with the labels that each got.

#55 C extension allowing overriding any method or function
  .circleci/config.yml
  .clang-format
  .editorconfig
  .gitignore
  config.m4
  src/ext/compat_zend_string.c
  src/ext/compat_zend_string.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/debug.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php5.h
  src/ext/dispatch_compat_php7.c
  src/ext/dispatch_setup.c
  tests/Unit/TraceOverrideMethodTest.php
  tests/ext/closure_accessing_outside_variables.phpt
  tests/ext/closure_set_inside_object_methods.phpt
  tests/ext/multiple_instrumentations.phpt
  tests/ext/namespaces.phpt
  tests/ext/overriding_method_defined_in_parent.phpt
  tests/ext/recursion.phpt
  tests/ext/simple_function_hook.phpt
  tests/ext/simple_method_hook.phpt
  tests/ext/variable_length_parameter_list.phpt
  tests/ext/with_params_function_hook.phpt
  tests/ext/with_params_method_hook.phpt
Labels: core

#66 [integrations] add Datadog integrations to the base Tracer
  .circleci/config.yml
  .gitignore
  .phpcs.xml
  composer.json
  phpstan.neon
  src/DDTrace/Integrations/Eloquent.php
  src/DDTrace/Integrations/LaravelProvider.php
  src/DDTrace/Integrations/Memcached.php
  src/DDTrace/Integrations/PDO.php
  src/DDTrace/Integrations/Predis.php
  src/DDTrace/Integrations/SymfonyBundle.php
  src/DDTrace/Span.php
  src/DDTrace/Tags.php
  src/DDTrace/Time.php
  src/DDTrace/Types.php
Labels: integrations

#69 [laravel] Fix method signature
  src/DDTrace/Integrations/LaravelProvider.php
Labels: bug, core

#74 Fix case sensitive lookup bug
  src/ext/debug.h
  src/ext/dispatch_compat_php5.c
  tests/ext/case_insensitive_method_hook.phpt
Labels: bug

#77 Standardize import paths
  src/ext/ddtrace.c
  src/ext/dispatch.c
  src/ext/dispatch_setup.c
Labels: bug

#84 Use test runners from docker library
  .circleci/config.yml
  DDMakefile
  README.md
  composer.json
  docker-compose.yml
Labels: dev/testing, do-not-merge/WIP

#82 Test that methods and properties with access modifier are accessible and overridable
  tests/ext/access_modifier_method_access_hook.phpt
  tests/ext/access_modifier_property_access_hook.phpt
  tests/ext/private_method_hook.phpt
  tests/ext/protected_method_hook.phpt
Labels: dev/testing

#87 Remove dd extension from required extensions in composer.
  .circleci/config.yml
  composer.json
Labels: ci, core

#85 Moved existing tracing context to common class + utils to as…
  tests/DebugTransport.php
  tests/Integration/Common/IntegrationTestCase.php
  tests/Integration/Common/SpanAssertion.php
  tests/Integration/Common/SpanChecker.php
  tests/Integration/Integrations/PredisTest.php
Labels: dev/testing

#91 Ci build artifacts
  .circleci/config.yml
  DDMakefile
  docker-compose.yml
  package/ddtrace.ini.example
  package/post-install.sh
  src/DDTrace/Version.php
  src/ext/ddtrace.h
  src/ext/version.h
Labels: ci, enhancement

#94 Mark supported version as PHP 7.0+. Change Alpha to Beta.
  README.md
  docs/getting_started.md
Labels: docs
