Repository DataDog/dd-trace-php, pull requests merged in 2019-07, with the labels that each got.

#490 Prefix invalid hostnames as service names
  CHANGELOG.md
  src/DDTrace/Http/Urls.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
Labels: integrations, 🐛 bug

#492 Bump version to 0.29.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#499 Tests from PHP
  .circleci/config.yml
  dockerfiles/ci/Dockerfile_buster
  dockerfiles/ci/docker-compose.yml
  dockerfiles/ci/docker-php-ext-configure
  dockerfiles/ci/docker-php-ext-enable
  dockerfiles/ci/docker-php-ext-install
  dockerfiles/ci/docker-php-source
  dockerfiles/ci/xfail_tests/5.4.list
  dockerfiles/ci/xfail_tests/5.6.list
  dockerfiles/ci/xfail_tests/7.0.list
  dockerfiles/ci/xfail_tests/7.1.list
  dockerfiles/ci/xfail_tests/7.2.list
  dockerfiles/ci/xfail_tests/7.3.list
  dockerfiles/verify_packages/docker-compose.yml
  src/ext/env_config.c
Labels: dev/testing, 🍏 core

#512 WIP: dd-doctor.php initial implementation
  .phpcs.xml
  phpstan.neon
  src/dd-doctor.php
Labels: dev/tooling

#519 Remove zend_execute_ex override and trace ZEND_DO_UCALL
  CHANGELOG.md
  src/ext/ddtrace.h
  src/ext/dispatch_setup.c
Labels: c-extension, 🍏 core
