Repository DataDog/dd-trace-php, pull requests merged in 2019-08, with the labels that each got.

#521 Fix memory leaks August 2019
  src/ext/coms.c
  src/ext/coms.h
  src/ext/ddtrace.c
Labels: ☠️ do-not-merge/WIP

#527 Release version 0.30.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#524 Refactor opcode handler entry
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
Labels: c-extension, 🍏 core

#529 Update changelog to reflect 0.30.0 release
  CHANGELOG.md
Labels: 📚 docs

#530 Add labels and milestone PR checklist for reviewer
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📚 docs

#531 Add symfony framework tests to CI
  .circleci/config.yml
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/docker-compose.yml
  dockerfiles/frameworks/nginx_file_server.yml
  dockerfiles/frameworks/nginx_file_server/Dockerfile
  dockerfiles/frameworks/symfony.yml
  dockerfiles/frameworks/symfony/Dockerfile
  dockerfiles/frameworks/symfony/entrypoint.sh
Labels: ci

#491 Sandboxing: Append tracing closures
  CHANGELOG.md
  Makefile
  config.m4
  package.xml
  src/DDTrace/Encoders/SpanEncoder.php
  src/DDTrace/OpenTracer/SpanContext.php
  src/DDTrace/Processing/TraceAnalyticsProcessor.php
  src/DDTrace/Span.php
  src/DDTrace/SpanContext.php
  src/DDTrace/Tracer.php
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  src/ext/dispatch_setup.c
  src/ext/logging.h
  src/ext/random.c
  src/ext/random.h
  src/ext/serializer.c
  src/ext/serializer.h
  src/ext/span.c
  src/ext/span.h
  src/ext/trace.c
  src/ext/trace.h
  tests/ext/dd_trace_function.phpt
  tests/ext/dd_trace_generate_id.phpt
  tests/ext/dd_trace_method.phpt
  tests/ext/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/dd_trace_push_span_id.phpt
  tests/ext/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
Labels: c-extension, 🍏 core

#536 Release This as soon as wrapping closure is finished and scope is left
  package.xml
  src/ext/compatibility.h
  src/ext/ddtrace.c
  src/ext/dispatch.c
  src/ext/dispatch_compat.h
  tests/ext/desctructor_called_when_this_gets_out_of_scope.phpt
Labels: c-extension, 🐛 bug

#540 Release 0.30.1
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/compatibility.h
  src/ext/ddtrace.c
  src/ext/dispatch.c
  src/ext/dispatch_compat.h
  src/ext/version.h
  tests/ext/desctructor_called_when_this_gets_out_of_scope.phpt
Labels: release

#542 Changes required to adapt to the new release process
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: dev/tooling, 🏘 community

#544 Fix ZTS builds, remove COMPAT_CTX_*
  src/ext/circuit_breaker.c
  src/ext/compatibility.h
  src/ext/configuration.c
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/dispatch.h
  src/ext/dispatch_compat_php7.c
  src/ext/env_config.h
  src/ext/logging.h
  src/ext/random.h
  src/ext/request_hooks.h
  src/ext/span.h
Labels: c-extension, 🐛 bug

#541 Symfony framework tests establish passing baseline
  .circleci/config.yml
  .env
  .gitignore
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/src/20-redis.ini
  dockerfiles/frameworks/src/Dockerfile
  dockerfiles/frameworks/src/symfony_run.sh
  dockerfiles/frameworks/src/symfony_v4.3.4.patch
  dockerfiles/packaging/Makefile
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
Labels: ci

#547 Refactor ddtrace_execute_tracing_closure
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  src/ext/span.c
  src/ext/trace.c
Labels: c-extension

#550 Move sandbox tests into subfolder
  .circleci/config.yml
  package.xml
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_function_internal.phpt
  tests/ext/sandbox/dd_trace_function_userland.phpt
  tests/ext/sandbox/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/sandbox/dd_trace_push_span_id.phpt
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
Labels: c-extension, dev/testing

#546 [Sandbox] Bind called object to tracing closure
  package.xml
  src/ext/dispatch.c
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php5.h
  src/ext/dispatch_compat_php7.c
  src/ext/trace.c
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_function_internal.phpt
  tests/ext/sandbox/dd_trace_function_userland.phpt
  tests/ext/sandbox/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_method_binds_called_object.phpt
  tests/ext/sandbox/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/sandbox/dd_trace_push_span_id.phpt
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/static_tracing_closures_will_not_bind_this.phpt
Labels: c-extension, 🍏 core
