Repository DataDog/dd-trace-php, pull requests merged in 2019-04, with the labels that each got.

#389 Build packages for "build" branch names
  .circleci/config.yml
Labels: ci

#388 Add cap to payloads sent to the Agent
  CHANGELOG.md
  src/DDTrace/Transport/Http.php
  tests/Common/TestLogger.php
  tests/Unit/Transport/HttpTest.php
Labels: 🍏 core

#392 Fix master build
  .circleci/config.yml
  docker-compose.yml
  src/ext/serializer.c
Labels: c-extension, ci, 🍏 core

#391 Bump version to 0.18.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#396 fix #395 build with -std=c99 option
  config.m4
Labels: c-extension, 🏘 community, 🐛 bug, 🥒 PECL

#397 fix #393 add mpack to pecl archive
  package.xml
Labels: 🏘 community, 🥒 PECL

#399 Make dd_trace_serialize_msgpack() tests more cross-platform friendly
  tests/ext/dd_trace_serialize_msgpack.phpt
  tests/ext/dd_trace_serialize_msgpack_error.phpt
  tests/ext/dd_trace_serialize_msgpack_error_strict.phpt
Labels: dev/testing

#398 Improve span handling performance (setTag and serialization)
  CHANGELOG.md
  src/DDTrace/Data/Span.php
  src/DDTrace/Data/SpanContext.php
  src/DDTrace/Encoders/SpanEncoder.php
  src/DDTrace/Processing/TraceAnalyticsProcessor.php
  src/DDTrace/Span.php
  src/DDTrace/SpanContext.php
  src/DDTrace/Tracer.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/OpenTracerUnit/TracerTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/Unit/StartSpanOptionsFactoryTest.php
Labels: 🍏 core

#387 Disable autoloader and load files manualy
  CHANGELOG.md
  bridge/dd_optional_deps_autoloader.php
  bridge/dd_require_all.php
  bridge/dd_required_deps_autoloader.php
  bridge/functions.php
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
  src/DDTrace/NoopTracer.php
  tests/bootstrap.php
  tests/bootstrap_utils.php
Labels: 🍏 core

#402 Bump version to 0.19.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#403 Fix CHANGELOG headings
  CHANGELOG.md
Labels: 📚 docs

#404 Fix original curl headers overwritten
  src/ext/dispatch_setup.c
Labels: c-extension, 🍏 core, 🐛 bug

#407 Release version 0.19.1
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#410 Make tests less brittle
  tests/ext/dd_trace_serialize_msgpack_error.phpt
  tests/ext/dd_trace_serialize_msgpack_error_strict.phpt
Labels: dev/testing

#411 Release 0.20.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump, 📚 docs

#412 simplify regex which fails with 7.3
  tests/ext/segfault_backtrace_enabled.phpt
  tests/ext/segfault_backtrace_enabled_via_env.phpt
  tests/ext/segfault_backtrace_enabled_via_env_disabled_in_ini.phpt
Labels: dev/testing

#414 Store unit test results and artifacts + use valgrind suppressions and config from PHP repo
  .circleci/config.yml
  .circleci/valgrind/musl_valgrind.rc
  .circleci/valgrind/valgrind_musl_suppressions.lib
Labels: dev/testing

#284 Fix inheritance bug when invoking `parent::` in a subclass
  CHANGELOG.md
  package.xml
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mongo/MongoClientIntegration.php
  src/DDTrace/Integrations/Mongo/MongoCollectionIntegration.php
  src/DDTrace/Integrations/Mongo/MongoDBIntegration.php
  src/DDTrace/Integrations/Mongo/MongoIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
  src/DDTrace/try_catch_finally.php
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  tests/ext/dd_trace_forward_call_error.phpt
  tests/ext/dd_trace_forward_call_for_functions.phpt
  tests/ext/dd_trace_forward_call_from_include.phpt
  tests/ext/dd_trace_forward_call_with_inheritance.phpt
  tests/ext/includes/try_catch_finally.php
Labels: c-extension, 🍏 core, 🐛 bug

#303 Fix callable scope after tracing
  CHANGELOG.md
  bridge/functions.php
  package.xml
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/ext/access_modifier_method_access_hook.phpt
  tests/ext/dd_trace_forward_call_with_private_callback.phpt
Labels: c-extension, 🍏 core, 🐛 bug

#415 Put changes under correct heading in CHANGELOG
  CHANGELOG.md
Labels: 📚 docs

#418 Add Lumen 5.8 to tests
  tests/Frameworks/Lumen/Version_5_8/.editorconfig
  tests/Frameworks/Lumen/Version_5_8/.env.example
  tests/Frameworks/Lumen/Version_5_8/.gitignore
  tests/Frameworks/Lumen/Version_5_8/app/Console/Commands/.gitkeep
  tests/Frameworks/Lumen/Version_5_8/app/Console/Kernel.php
  tests/Frameworks/Lumen/Version_5_8/app/Events/Event.php
  tests/Frameworks/Lumen/Version_5_8/app/Events/ExampleEvent.php
  tests/Frameworks/Lumen/Version_5_8/app/Exceptions/Handler.php
  tests/Frameworks/Lumen/Version_5_8/app/Http/Controllers/Controller.php
  tests/Frameworks/Lumen/Version_5_8/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_8/app/Http/Middleware/Authenticate.php
  tests/Frameworks/Lumen/Version_5_8/app/Http/Middleware/ExampleMiddleware.php
  tests/Frameworks/Lumen/Version_5_8/app/Jobs/ExampleJob.php
  tests/Frameworks/Lumen/Version_5_8/app/Jobs/Job.php
  tests/Frameworks/Lumen/Version_5_8/app/Listeners/ExampleListener.php
  tests/Frameworks/Lumen/Version_5_8/app/Providers/AppServiceProvider.php
  tests/Frameworks/Lumen/Version_5_8/app/Providers/AuthServiceProvider.php
  tests/Frameworks/Lumen/Version_5_8/app/Providers/EventServiceProvider.php
  tests/Frameworks/Lumen/Version_5_8/app/User.php
  tests/Frameworks/Lumen/Version_5_8/artisan
  tests/Frameworks/Lumen/Version_5_8/bootstrap/app.php
  tests/Frameworks/Lumen/Version_5_8/composer.json
  tests/Frameworks/Lumen/Version_5_8/database/factories/ModelFactory.php
  tests/Frameworks/Lumen/Version_5_8/database/migrations/.gitkeep
  tests/Frameworks/Lumen/Version_5_8/database/seeds/DatabaseSeeder.php
  tests/Frameworks/Lumen/Version_5_8/phpunit.xml
  tests/Frameworks/Lumen/Version_5_8/public/.htaccess
  tests/Frameworks/Lumen/Version_5_8/public/index.php
  tests/Frameworks/Lumen/Version_5_8/readme.md
  tests/Frameworks/Lumen/Version_5_8/resources/views/.gitkeep
  tests/Frameworks/Lumen/Version_5_8/routes/web.php
  tests/Frameworks/Lumen/Version_5_8/storage/app/.gitignore
  tests/Frameworks/Lumen/Version_5_8/storage/framework/cache/.gitignore
  tests/Frameworks/Lumen/Version_5_8/storage/framework/views/.gitignore
  tests/Frameworks/Lumen/Version_5_8/storage/logs/.gitignore
  tests/Frameworks/Lumen/Version_5_8/tests/ExampleTest.php
  tests/Frameworks/Lumen/Version_5_8/tests/TestCase.php
  tests/Frameworks/README.md
Labels: dev/testing
