Repository DataDog/dd-trace-php, pull requests merged in 2019-09, with the labels that each got.

#551 Add framework tests for flow framework
  .circleci/config.yml
  .editorconfig
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/flow.yml
  dockerfiles/frameworks/src/Dockerfile
  dockerfiles/frameworks/src/flow/20-redis.ini
  dockerfiles/frameworks/src/flow/30.tz.ini
  dockerfiles/frameworks/src/flow/Settings.yaml
  dockerfiles/frameworks/src/flow/patch.patch
  dockerfiles/frameworks/src/flow/run.sh
  dockerfiles/frameworks/src/switch_php.sh
Labels: ci

#553 Align all Laravel framework tests with tracing
  dockerfiles/frameworks/src/Dockerfile
  dockerfiles/frameworks/src/laravel/patch.patch
  src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
Labels: ci

#554 Test PDO active query exception is not happening when variable is unset
  tests/Integrations/PDO/PDOTest.php
Labels: dev/testing

#555 Fix #502: Curl headers are overwritten when using `curl_copy_handle` function
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: integrations, 🐛 bug

#549 [Sandbox] Pass original call exception to tracing closure
  package.xml
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  src/ext/trace.c
  tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure.phpt
  tests/ext/sandbox/exceptions_are_passed_to_the_tracing_closure_php5.phpt
  tests/ext/sandbox/exceptions_in_original_call_rethrown_in_tracing_closure.phpt
  tests/ext/sandbox/exceptions_in_original_call_rethrown_in_tracing_closure_php5.phpt
  tests/ext/sandbox/exceptions_in_tracing_closure_and_original_call.phpt
Labels: c-extension, 🍏 core

#558 [Sandbox] Add regression tests
  package.xml
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  src/ext/trace.c
  tests/ext/sandbox-regression/access_modifier_method_access_hook.phpt
  tests/ext/sandbox-regression/access_modifier_property_access_hook.phpt
  tests/ext/sandbox-regression/allow_overriding_before_overrided_methods_functions_are_defined.phpt
  tests/ext/sandbox-regression/case_insensitive_method_hook.phpt
  tests/ext/sandbox-regression/closure_accessing_outside_variables.phpt
  tests/ext/sandbox-regression/closure_set_inside_object_methods.phpt
  tests/ext/sandbox-regression/destructor_called_when_this_gets_out_of_scope.phpt
  tests/ext/sandbox-regression/do_not_check_if_class_or_function_exists_by_default.phpt
  tests/ext/sandbox-regression/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/sandbox-regression/extension_disabled.phpt
  tests/ext/sandbox-regression/method_invoked_via_reflection.phpt
  tests/ext/sandbox-regression/method_returning_array.phpt
  tests/ext/sandbox-regression/multiple_instrumentations.phpt
  tests/ext/sandbox-regression/namespaces.phpt
  tests/ext/sandbox-regression/overriding_construct.phpt
  tests/ext/sandbox-regression/overriding_method_defined_in_parent.phpt
  tests/ext/sandbox-regression/private_method_hook.phpt
  tests/ext/sandbox-regression/private_self_access.phpt
  tests/ext/sandbox-regression/protected_method_hook.phpt
  tests/ext/sandbox-regression/recursion.phpt
  tests/ext/sandbox-regression/reset_configured_overrides.phpt
  tests/ext/sandbox-regression/reset_function_tracing.phpt
  tests/ext/sandbox-regression/return_value_passed.phpt
  tests/ext/sandbox-regression/simple_function_hook.phpt
  tests/ext/sandbox-regression/simple_method_hook.phpt
  tests/ext/sandbox-regression/throw_exception.phpt
  tests/ext/sandbox-regression/trace_method_or_function_that_will_exist_later.phpt
  tests/ext/sandbox-regression/trace_static_method.phpt
  tests/ext/sandbox-regression/used_dispatch_shouldn_t_be_freed.phpt
  tests/ext/sandbox-regression/variable_length_parameter_list.phpt
  tests/ext/sandbox-regression/very_nested_functions.phpt
  tests/ext/sandbox-regression/with_params_function_hook.phpt
  tests/ext/sandbox-regression/with_params_method_hook.phpt
Labels: c-extension, dev/testing

#560 Fix compiler warning about uninitialized zval
  src/ext/dispatch_compat_php7.c
Labels: c-extension

#564 Fix compiler warning about uninitialized zval (redux)
  src/ext/dispatch_compat_php7.c
Labels: c-extension, dev/testing

#572 [Sandbox] Fix merging of internal and userland spans
  src/DDTrace/Tracer.php
  tests/Unit/TracerTest.php
Labels: 🐛 bug, 📦 Sandbox API

#571 Correctly treat class names as case insensitive
  package.xml
  src/ext/dispatch.c
  src/ext/dispatch_setup.c
  tests/ext/case_insensitive_class_hook.phpt
Labels: c-extension, 🐛 bug

#573 Improve dd-doctor.php with more info
  src/dd-doctor.php
Labels: dev/tooling

#577 Replace request replayer script with official image able to decode msgpack
  .circleci/config.yml
  composer.json
  docker-compose.yml
  tests/Common/AgentReplayerTrait.php
  tests/Common/TracerTestTrait.php
  tests/Integrations/CLI/CLITestCase.php
  tests/WebServer.php
  tests/request_replayer/index.php
Labels: dev/testing, dev/tooling

#576 Fix static keyword handling
  package.xml
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  tests/ext/new_static.phpt
  tests/ext/sandbox/errors_are_flagged_from_userland.phpt
  tests/ext/sandbox/new_static.phpt
Labels: c-extension, 🍏 core, 🐛 bug

#552 Container tagging
  bridge/dd_require_all.php
  src/DDTrace/Transport/Http.php
  src/DDTrace/Util/ContainerInfo.php
  src/DDTrace/Util/Runtime.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/Util/ContainerInfoTest.php
Labels: 🍏 core, 🏆 enhancement

#559 Migrate eloquent integration to sandboxed API
  .circleci/config.yml
  bridge/dd_require_all.php
  composer.json
  docker-compose.yml
  phpunit.xml
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentSandboxedIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Tag.php
  tests/Common/IntegrationTestCase.php
  tests/Common/SpanAssertionTrait.php
  tests/Common/SpanChecker.php
  tests/Common/TracerTestTrait.php
  tests/Common/WebFrameworkTestCase.php
  tests/Frameworks/Laravel/Version_4_2/app/config/database.php
  tests/Frameworks/Laravel/Version_4_2/app/controllers/EloquentTestController.php
  tests/Frameworks/Laravel/Version_4_2/app/routes.php
  tests/Frameworks/Laravel/Version_5_7/app/Http/Controllers/EloquentTestController.php
  tests/Frameworks/Laravel/Version_5_7/config/database.php
  tests/Frameworks/Laravel/Version_5_7/config/logging.php
  tests/Frameworks/Laravel/Version_5_7/routes/web.php
  tests/Frameworks/Laravel/Version_5_8/app/Http/Controllers/EloquentTestController.php
  tests/Frameworks/Laravel/Version_5_8/config/database.php
  tests/Frameworks/Laravel/Version_5_8/config/logging.php
  tests/Frameworks/Laravel/Version_5_8/routes/web.php
  tests/Integrations/Laravel/V4/EloquentSandboxedTest.php
  tests/Integrations/Laravel/V4/EloquentTest.php
  tests/Integrations/Laravel/V5_7/EloquentSandboxedTest.php
  tests/Integrations/Laravel/V5_7/EloquentTest.php
  tests/Integrations/Laravel/V5_8/EloquentSandboxedTest.php
  tests/Integrations/Laravel/V5_8/EloquentTest.php
  tests/Integrations/PDO/PDOSandboxedTest.php
  tests/Integrations/PDO/PDOTest.php
Labels: integrations, 🍏 core, 📦 Sandbox API

#578 Migrate memcached integration to sandboxed API
  bridge/dd_require_all.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
  tests/Common/TracerTestTrait.php
  tests/Integrations/Memcached/MemcachedSandboxedTest.php
  tests/Integrations/Memcached/MemcachedTest.php
Labels: integrations, 🍏 core, 📦 Sandbox API

#579 Ensure the request init hook is bound by the open_basedir INI directive
  package.xml
  src/ext/request_hooks.c
  src/ext/sandbox.h
Labels: c-extension, 🍏 core, 🐛 bug

#580 Release 0.30.2
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#583 Request init hook edge cases tests
  .circleci/valgrind/valgrind_7_3_musl_suppressions.lib
  package.xml
  src/dd-doctor.php
  src/ext/dispatch_compat_php5.c
  src/ext/request_hooks.c
  src/ext/sandbox.h
  tests/ext/includes/sanity_check.php
  tests/ext/request-init-hook/raises_fatal_error.php
  tests/ext/request-init-hook/request_init_hook_check_blacklisted_modules.phpt
  tests/ext/request-init-hook/request_init_hook_confined_to_open_basedir.phpt
  tests/ext/request-init-hook/request_init_hook_file_not_found.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_exceptions.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
  tests/ext/request-init-hook/run_file_before_request_handling.phpt
  tests/ext/request-init-hook/throws_exception.php
  tests/ext/simple_sanity_check.phpt
Labels: c-extension, dev/testing

#574 Fix Predis integration for clusters
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  tests/Integrations/Predis/PredisTest.php
Labels: 🏘 community, 🐛 bug

#591 Generate output on test controllers
  tests/Frameworks/Laravel/Version_5_7/app/Http/Controllers/EloquentTestController.php
Labels: ci, 🐛 bug

#590 Make PHP API check more specific
  package/post-install.sh
Labels: packaging, 🐛 bug
