Repository DataDog/dd-trace-php, pull requests merged in 2019-01, with the labels that each got.

#203 Allow testing of multiple library versions
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  composer.json
  docker-compose.yml
  phpunit.xml
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
Labels: dev/testing

#208 Downgrade of phpunit to 4.* in order to prepare for php 5.4
  CHANGELOG.md
  composer.json
  src/DDTrace/Util/TryCatchFinally.php
  tests/Unit/SpanTest.php
  tests/Unit/TracerTest.php
  tests/Unit/Util/TryCatchFinallyTest.php
Labels: dev/testing

#187 Predis integration supporting constructor options as an object
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  tests/Integrations/Predis/PredisTest.php
Labels: bug, community, integrations

#217 Configurable autofinishing of unfinished spans on tracer flush
  CHANGELOG.md
  docs/getting_started.md
  src/DDTrace/Configuration.php
  src/DDTrace/Tracer.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Unit/TracerTest.php
Labels: core

#215 Fix compile-time error on PHP 7.3
  src/ext/dispatch_compat_php7.c
Labels: core

#219 Disable centos 7.0 verification build, and disable cache to ensure other steps are correctly performed
  dockerfiles/verify_packages/Makefile
Labels: dev/testing, dev/tooling

#210 Add PECL config
  README.md
  docs/getting_started.md
  package.xml
Labels: c-extension, enhancement

#220 Fix noop tracer issues with Laravel integration
  CHANGELOG.md
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  tests/Frameworks/Laravel/Version_5_7/config/app.php
Labels: bug, integrations

#221 Bump version to 0.9.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Version.php
  src/ext/version.h
Labels: core

#222 Add `dd_trace_reset` function, and stop throwing exceptions when overriding missing methods
  .circleci/config.yml
  CHANGELOG.md
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_setup.c
  tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/reset_configured_overrides.phpt
  tests/ext/silently_check_if_overridable_exists.phpt
Labels: c-extension

#207 Migration from namespace based constants to class based constants for tags, formats and types
  CHANGELOG.md
  DDMakefile
  composer.json
  src/DDTrace/Format.php
  src/DDTrace/Formats.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mongo/MongoClientIntegration.php
  src/DDTrace/Integrations/Mongo/MongoCollectionIntegration.php
  src/DDTrace/Integrations/Mongo/MongoDBIntegration.php
  src/DDTrace/Integrations/Mongo/MongoIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Span.php
  src/DDTrace/StartSpanOptionsFactory.php
  src/DDTrace/Tag.php
  src/DDTrace/Tags.php
  src/DDTrace/Time.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  src/DDTrace/Type.php
  src/DDTrace/Types.php
  src/DDTrace/Version.php
  tests/Frameworks/Laravel/Version_4_2/composer.json
  tests/Frameworks/Laravel/Version_5_7/composer.json
  tests/Frameworks/Symfony/Version_3_4/composer.json
  tests/Integration/Transport/HttpTest.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Unit/SpanTest.php
  tests/Unit/TimeTest.php
  tests/Unit/TracerTest.php
Labels: breaking-change, core

#206 Removal of external dependencies to support auto-instrumentation
  .phpcs.xml
  CHANGELOG.md
  composer.json
  src/DDTrace/Encoder.php
  src/DDTrace/Encoders/Json.php
  src/DDTrace/Log/Logger.php
  src/DDTrace/Log/LoggerInterface.php
  src/DDTrace/Log/NullLogger.php
  src/DDTrace/Log/PsrLogger.php
  src/DDTrace/Transport/Http.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Log/LoggerTest.php
  tests/Unit/Log/PsrLoggerTest.php
  tests/Unit/Transport/HttpTest.php
Labels: breaking-change, core

#223 Documenting release steps
  CHANGELOG.md
  RELEASING.md
Labels: docs

#235 Improve request replayer returning traces
  tests/request_replayer/index.php
Labels: ci, dev/testing

#175 Request hook implementation
  CHANGELOG.md
  config.m4
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/request_hooks.c
  src/ext/request_hooks.h
  tests/ext/request_init_hook_file_not_found.phpt
  tests/ext/run_file_before_request_handling.phpt
  tests/ext/simple_sanity_check.phpt
Labels: c-extension, core

#232 Ability to run web framework tests in external web server
  .circleci/config.yml
  .request_dumper_data/.gitignore
  CHANGELOG.md
  composer.json
  docker-compose.yml
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Tracer.php
  tests/Common/TracerTestTrait.php
  tests/Common/WebFrameworkTestCase.php
  tests/Frameworks/Laravel/Version_4_2/app/config/app.php
  tests/Frameworks/Laravel/Version_4_2/app/tests/TestCase.php
  tests/Frameworks/Laravel/Version_4_2/composer.json
  tests/Frameworks/Laravel/Version_4_2/public/index.php
  tests/Frameworks/Laravel/Version_5_7/app/DummyPipe.php
  tests/Frameworks/Laravel/Version_5_7/app/Http/Controllers/TestsController.php
  tests/Frameworks/Laravel/Version_5_7/composer.json
  tests/Frameworks/Laravel/Version_5_7/routes/web.php
  tests/Frameworks/Laravel/Version_5_7/tests/CreatesApplication.php
  tests/Frameworks/Laravel/Version_5_7/tests/Integration/PipelineTracingTest.php
  tests/Frameworks/Laravel/Version_5_7/tests/TestCase.php
  tests/Frameworks/Symfony/Version_3_4/composer.json
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Laravel/V4/CommonScenariosTest.php
  tests/Integrations/Laravel/V5/CommonScenariosTest.php
  tests/Integrations/Laravel/V5/PipelineTracingTest.php
  tests/Integrations/Symfony/V3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3/TemplateEnginesTest.php
  tests/WebServer.php
Labels: ci, dev/testing

#240 Fix test error cases
  tests/Common/TracerTestTrait.php
  tests/Frameworks/Util/CommonScenariosDataProviderTrait.php
Labels: bug, dev/testing

#241 Add root span/scope tracking
  CHANGELOG.md
  src/DDTrace/Contracts/Tracer.php
  src/DDTrace/NoopTracer.php
  src/DDTrace/Tracer.php
  tests/Unit/TracerTest.php
Labels: core, enhancement

#242 Add INI settings to the info page
  CHANGELOG.md
  src/ext/ddtrace.c
Labels: bug, c-extension

#238 Zend Framework 1 integration
  CHANGELOG.md
  README.md
  composer.json
  docs/getting_started.md
  src/DDTrace/Integrations/ZendFramework/V1/Ddtrace.php
  src/DDTrace/Integrations/ZendFramework/V1/TraceRequest.php
  src/DDTrace/autoload.php
  tests/Frameworks/ZendFramework/Version_1_12/.gitignore
  tests/Frameworks/ZendFramework/Version_1_12/application/Bootstrap.php
  tests/Frameworks/ZendFramework/Version_1_12/application/configs/application.ini
  tests/Frameworks/ZendFramework/Version_1_12/application/controllers/ErrorController.php
  tests/Frameworks/ZendFramework/Version_1_12/application/controllers/SimpleController.php
  tests/Frameworks/ZendFramework/Version_1_12/application/views/scripts/simple/view.phtml
  tests/Integrations/ZendFramework/V1/CommonScenariosTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
Labels: integrations

#244 Fix packaging compilation + use dd blessed images
  .circleci/config.yml
Labels: ci

#245 Version bump 0.10.0
  .circleci/config.yml
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#247 Composer php compatibility declaration
  .circleci/config.yml
  CHANGELOG.md
  README.md
  composer.json
  docs/getting_started.md
Labels: core

#248 Update release notes for PECL and fix type-os in CHANGELOG
  CHANGELOG.md
  package.xml
Labels: core

#252 Add missing files to PECL releases
  CHANGELOG.md
  package.xml
Labels: 🐛 bug, 🥒 PECL

#256 Trigger of autoloader un-tracing did not respect object
  CHANGELOG.md
  bridge/dd_wrap_autoloader.php
Labels: core

#258 Update getting_started.md
  docs/getting_started.md
Labels: 🏘 community, 📚 docs

#263 Fix type-o in command to install .deb packages
  README.md
  docs/getting_started.md
Labels: 📚 docs

#261 Debug mode for logging
  CHANGELOG.md
  src/DDTrace/Configuration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Log/ErrorLogLogger.php
  src/DDTrace/Log/InterpolateTrait.php
  src/DDTrace/Log/Logger.php
  src/DDTrace/Log/LoggerInterface.php
  src/DDTrace/Log/LoggingTrait.php
  src/DDTrace/Log/NullLogger.php
  src/DDTrace/Log/PsrLogger.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  tests/Common/TracerTestTrait.php
  tests/DebugLogger.php
  tests/Integration/Transport/HttpTest.php
  tests/Unit/BaseTestCase.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/Unit/ScopeManagerTest.php
  tests/Unit/TracerTest.php
  tests/Unit/Transport/HttpTest.php
Labels: core

#262 Auto-instrumentation in Symfony 3.4 and PHP 5.6
  .circleci/config.yml
  CHANGELOG.md
  bridge/dd_init.php
  bridge/dd_wrap_autoloader.php
  bridge/functions.php
  composer.json
  docker-compose.yml
  local-build.sh
  src/DDTrace/Integrations/Symfony/V3/SymfonyIntegration.php
  src/DDTrace/Transport/Http.php
  tests/Frameworks/Symfony/Version_3_4/web/app.php
  tests/Integration/Transport/HttpTest.php
  tests/Integrations/Symfony/V3/CommonScenariosTest.php
  tests/dockerfiles/Dockerfile_php56_apache
  tests/dockerfiles/apache2.conf
  tests/dockerfiles/php.enanche.ini
  tests/dockerfiles/symfony_34_virtualhost.conf
Labels: core

#267 Build php extension for 5.4 locally
  local-build.sh
Labels: core

#266 Support for Symfony 3.3
  CHANGELOG.md
  composer.json
  src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
  tests/Frameworks/Symfony/Version_3_3/app/Resources/views/twig_template.html.twig
  tests/Frameworks/Symfony/Version_3_3/src/AppBundle/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_3_3/var/SymfonyRequirements.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
Labels: dev/testing, integrations

#260 Configurable sampler
  CHANGELOG.md
  src/DDTrace/Configuration.php
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/Configuration/EnvVariableRegistry.php
  src/DDTrace/Configuration/Registry.php
  src/DDTrace/ID.php
  src/DDTrace/Sampling/ConfigurableSampler.php
  src/DDTrace/Tracer.php
  tests/Unit/Configuration/EnvVariableRegistryTest.php
  tests/Unit/IDTest.php
  tests/Unit/Sampling/ConfigurableSamplerTest.php
Labels: core

#264 Unsupported & custom framework traces
  CHANGELOG.md
  composer.json
  src/DDTrace/Bootstrap.php
  src/DDTrace/Configuration.php
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/Configuration/EnvVariableRegistry.php
  src/DDTrace/Configuration/Registry.php
  src/DDTrace/Http/Request.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Integrations/ZendFramework/V1/Ddtrace.php
  src/DDTrace/Type.php
  tests/Frameworks/Custom/Version_Autoloaded/.gitignore
  tests/Frameworks/Custom/Version_Autoloaded/README.md
  tests/Frameworks/Custom/Version_Autoloaded/composer.json
  tests/Frameworks/Custom/Version_Autoloaded/public/index.php
  tests/Frameworks/Custom/Version_Autoloaded/src/ErrorController.php
  tests/Frameworks/Custom/Version_Autoloaded/src/SimpleController.php
  tests/Frameworks/Custom/Version_Autoloaded/src/SimpleViewController.php
  tests/Frameworks/Custom/Version_Autoloaded/src/routes.php
  tests/Frameworks/README.md
  tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
  tests/Unit/Configuration/EnvVariableRegistryTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Http/RequestTest.php
  tests/WebServer.php
Labels: core, integrations

#272 Point the documentation to the official documentation site
  CONTRIBUTING.md
  README.md
  docs/changelog.md
  docs/getting_started.md
  docs/open_tracing.md
Labels: 📚 docs
