Repository DataDog/dd-trace-php, pull requests merged in 2019-02, with the labels that each got.

#273 Support for global tags
  CHANGELOG.md
  src/DDTrace/Configuration.php
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/Configuration/EnvVariableRegistry.php
  src/DDTrace/Configuration/Registry.php
  src/DDTrace/Tracer.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Laravel/V4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Unit/Configuration/EnvVariableRegistryTest.php
  tests/Unit/TracerTest.php
Labels: core

#274 Fix Packaged extension compatiblity with Centos 6 and Alpine linux
  .circleci/config.yml
  CHANGELOG.md
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/alpine/Dockerfile.template
  dockerfiles/verify_packages/docker-compose.yml
  dockerfiles/verify_packages/verify_apk.sh
Labels: ci, 🐛 bug

#277 Detect installed SAPIs and link INI file to each one
  CHANGELOG.md
  package/post-install.sh
Labels: c-extension, core, 🐛 bug

#282 Zend integration incompatibility with Yii
  CHANGELOG.md
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
  src/DDTrace/Util/Runtime.php
Labels: integrations

#280 Integrations tests for Symfony 4.2
  CHANGELOG.md
  composer.json
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyIntegration.php
  tests/Frameworks/Symfony/Version_4_2/.env
  tests/Frameworks/Symfony/Version_4_2/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_4_2/templates/base.html.twig
  tests/Frameworks/Symfony/Version_4_2/templates/twig_template.html.twig
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
Labels: dev/testing

#286 Improvement of packagist update step in releasing instructions
  RELEASING.md
Labels: 📚 docs

#287 Span::setResource as a legit method
  CHANGELOG.md
  src/DDTrace/Contracts/Span.php
  src/DDTrace/NoopSpan.php
  src/DDTrace/Span.php
  tests/Unit/SpanTest.php
Labels: core

#288 Tracing of http status code in generic web requests
  CHANGELOG.md
  phpstan.neon
  src/DDTrace/Bootstrap.php
  tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
Labels: core

#289 Route not set in symfony 3.4 when user calls exit()
  CHANGELOG.md
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Util/TryCatchFinally.php
  tests/Frameworks/Symfony/Version_3_4/src/AppBundle/Controller/HomeController.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
Labels: integrations

#290 Fix hash table dtor for PHP 7
  src/ext/dispatch_setup.c
Labels: c-extension, core

#281 Handle php 5.4 memory leaks
  CHANGELOG.md
  Makefile
  docker-compose.yml
  dockerfiles/debug_php-5.4/Dockerfile
  dockerfiles/debug_php-7.2/Dockerfile
  src/ext/dispatch.c
  src/ext/dispatch_compat_php5.c
Labels: c-extension, core

#292 Logging more span's info when in debug mode
  .gitignore
  CHANGELOG.md
  src/DDTrace/Encoders/Json.php
  src/DDTrace/Log/AbstractLogger.php
  src/DDTrace/Log/ErrorLogLogger.php
  src/DDTrace/Log/LogLevel.php
  src/DDTrace/Log/Logger.php
  src/DDTrace/Log/LoggerInterface.php
  src/DDTrace/Log/LoggingTrait.php
  src/DDTrace/Log/NullLogger.php
  src/DDTrace/Log/PsrLogger.php
  src/DDTrace/Tracer.php
  tests/DebugLogger.php
  tests/Integrations/Laravel/V4/CommonScenariosTest.php
Labels: core

#294 Version bump 0.13.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#276 Honor ddtrace provided by composer if user provided one
  CHANGELOG.md
  bridge/functions.php
Labels: core

#291 Remove unused function that was moved to dispatch_table_dtor()
  src/ext/ddtrace.c
Labels: c-extension, core

#295 Fix 5.4 internal functions being called twice
  CHANGELOG.md
  composer.json
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch_setup.c
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
Labels: core

#296 Bump version 0.13.1
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#297 Fix ZTS compilation in php 5.6
  src/ext/ddtrace.c
  src/ext/dispatch.h
  src/ext/dispatch_setup.c
Labels: core

#305 Auto-instrumentation when user's autoloader throws exception on not found
  .circleci/config.yml
  .phpcs.xml
  CHANGELOG.md
  bridge/dd_init.php
  bridge/dd_wrap_autoloader.php
  bridge/functions.php
  composer.json
  docker-compose.yml
  phpunit.xml
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/AutoInstrumentation/scenarios/autoloader_includes_even_non_existing/index.php
  tests/AutoInstrumentation/scenarios/composer_with_ddtrace_dependency/composer.json
  tests/AutoInstrumentation/scenarios/composer_with_ddtrace_dependency/index.php
  tests/AutoInstrumentation/scenarios/composer_without_ddtrace_dependency/composer.json
  tests/AutoInstrumentation/scenarios/composer_without_ddtrace_dependency/index.php
  tests/AutoInstrumentation/scenarios/symfony_33_private_loader/composer.json
  tests/AutoInstrumentation/scenarios/symfony_33_private_loader/index.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
Labels: core, 🐛 bug

#306 Add debug builds to the package
  .circleci/config.yml
  CHANGELOG.md
  dockerfiles/verify_packages/Makefile
Labels: core

#300 Print backtrace on segfault
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  config.m4
  package.xml
  src/ext/backtrace.c
  src/ext/backtrace.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/env_config.c
  src/ext/env_config.h
  src/ext/logging.c
  src/ext/logging.h
  tests/ext/private_method_hook.phpt
  tests/ext/segfault_backtrace_disabled.phpt
  tests/ext/segfault_backtrace_disabled_via_env_enabled_in_ini.phpt
  tests/ext/segfault_backtrace_enabled.phpt
  tests/ext/segfault_backtrace_enabled_via_env.phpt
  tests/ext/segfault_backtrace_enabled_via_env_disabled_in_ini.phpt
Labels: core

#308 [ci] In CI disable tls check for 5.4 only to avoid Peer fingerprint mismatch
  .circleci/config.yml
Labels: ci

#313 Version bump 0.13.3
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#314 Fix accessing freed memory when instrumentation code un/instrumented itself
  CHANGELOG.md
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php7.c
  src/ext/dispatch_setup.c
  tests/ext/used_dispatch_shouldn_t_be_freed.phpt
Labels: c-extension, 🐛 bug

#318 Version bump 0.13.4
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#323 Update link to docs and copyright year in php info
  src/ext/ddtrace.c
Labels: c-extension, core, 📚 docs

#320 Add ability to define tracing for not yet defined methods and classes
  .gitignore
  CHANGELOG.md
  Makefile
  docker-compose.yml
  src/ext/compat_zend_string.c
  src/ext/compat_zend_string.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php5.h
  src/ext/dispatch_compat_php7.c
  src/ext/dispatch_setup.c
  tests/ext/allow_overriding_before_overrided_methods_functions_are_defined.phpt
  tests/ext/do_not_check_if_class_or_function_exists_by_default.phpt
  tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/overriding_method_defined_in_parent.phpt
  tests/ext/trace_method_or_function_that_will_exist_later.phpt
  tests/ext/trace_static_method.phpt
Labels: c-extension

#319 Loading of integrations before knowing if the library will be actually used
  CHANGELOG.md
  bridge/functions.php
  clean-composer-scenario-locks.sh
  composer.json
  src/DDTrace/Bootstrap.php
  src/DDTrace/GlobalTracer.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Guzzle/AbstractGuzzleIntegrationLoader.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/Integrations/Guzzle/V5/GuzzleIntegrationLoader.php
  src/DDTrace/Integrations/Guzzle/V6/GuzzleIntegrationLoader.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/LaravelProvider.php
  src/DDTrace/Integrations/Memcached.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli.php
  src/DDTrace/Integrations/PDO.php
  src/DDTrace/Integrations/Predis.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyIntegration.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyIntegration.php
  src/DDTrace/Integrations/SymfonyBundle.php
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkIntegration.php
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/Frameworks/Laravel/Version_4_2/app/config/app.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
Labels: core

#327 Version bump 0.14.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core

#328 Fix 5.6-zts build
  src/ext/ddtrace.c
  src/ext/dispatch.c
  src/ext/dispatch.h
Labels: c-extension, core, 🐛 bug

#330 Large number of mysqli spans not containing relevant information
  CHANGELOG.md
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  tests/Integrations/Mysqli/MysqliTest.php
Labels: integrations

#329 Replicate in tests autoloader that die() on class not found
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/AutoInstrumentation/scenarios/autoloader_die_on_not_found/index.php
Labels: dev/testing

#335 Version bump 0.14.2
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: core
