Repository DataDog/dd-trace-php, pull requests merged in 2019-11, with the labels that each got.

#637 Fix notice and refactor root span init
  src/DDTrace/Bootstrap.php
Labels: 🍏 core, 🐛 bug

#641 [Yii 2] Remove duplicate trait usage in test
  tests/Integrations/Yii/V2_0_26/ParameterizedRouteTest.php
Labels: dev/testing

#645 Fix distributed trace ID handling
  .circleci/config.yml
  composer.json
  package.xml
  phpunit.xml
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/SpanContext.php
  src/DDTrace/Tracer.php
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/random.c
  src/ext/random.h
  src/ext/span.c
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Common/WebFrameworkTestCase.php
  tests/DistributedTracing/DistributedTraceTest.php
  tests/DistributedTracing/SamplingPriorityTest.php
  tests/DistributedTracing/SandboxAndLegacyTest.php
  tests/DistributedTracing/SyntheticsTest.php
  tests/Frameworks/Custom/Version_Not_Autoloaded/sandbox.php
  tests/Frameworks/Util/Request/GetSpec.php
  tests/Frameworks/Util/Request/RequestSpec.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/ext/dd_trace_push_span_id_from_userland.phpt
  tests/ext/sandbox/dd_trace_set_trace_id.phpt
Labels: c-extension, 🍏 core, 🐛 bug

#647 Bump version to 0.34.1
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#650 Fix CodeIgniter namespace definition
  src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/AutoInstrumentation/scenarios/composer_with_ddtrace_dependency/composer.json
  tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/composer.json
  tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/index.php
Labels: 🐛 bug

#635 Move Mysqli integration to sandboxed api
  .phpcs.xml
  bridge/dd_require_all.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliCommon.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliSandboxedIntegration.php
  src/DDTrace/Integrations/SandboxedIntegration.php
  tests/Common/IntegrationTestCase.php
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Frameworks/WordPress/Version_4_8/wp-config.php
  tests/Frameworks/WordPress/Version_4_8/wp-load.php
  tests/Integrations/Mysqli/MysqliSandboxedTest.php
  tests/Integrations/Mysqli/MysqliTest.php
  tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
Labels: integrations, 📦 Sandbox API

#649 Move entire Symfony test suite to flame graph assertions
  tests/Integrations/Symfony/V2_3/RouteNameTest.php
  tests/Integrations/Symfony/V2_8/RouteNameTest.php
  tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
  tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
Labels: dev/testing

#655 Migrate Zend framework integration to sandboxed api
  bridge/dd_require_all.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkSandboxedIntegration.php
  tests/Integrations/ZendFramework/V1/CommonScenariosSanboxedTest.php
  tests/Integrations/ZendFramework/V1/CommonScenariosTest.php
  tests/Integrations/ZendFramework/V1/TraceSearchConfigSandboxedTest.php
  tests/Integrations/ZendFramework/V1/TraceSearchConfigTest.php
Labels: 📦 Sandbox API

#648 Add compile-time metric
  config.m4
  package.xml
  src/DDTrace/Encoders/SpanEncoder.php
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  tests/Common/SpanChecker.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Encoders/MessagePackTest.php
Labels: c-extension, 🍏 core, 🏆 enhancement

#660 Remove DoctrineCacheBundle
  tests/Frameworks/Symfony/Version_4_0/config/bundles.php
Labels: ci

#640 Add basic playground to live test changes to the code base
  docker-compose.yml
  playground/index.php
  playground/start-server.sh
Labels: dev/tooling

#659 Refactor opcode hooks
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_setup.c
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
Labels: c-extension, 🍏 core, 🐛 bug

#658 Add polyfill.m4 to support autoconf < 2.64
  .circleci/config.yml
  config.m4
  dockerfiles/frameworks/src/Dockerfile
  m4/polyfill.m4
  package.xml
Labels: dev/tooling, packaging, 🐛 bug

#667 Migrate Symfony framework integration to sandboxed api
  bridge/dd_require_all.php
  composer.json
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
  src/DDTrace/Processing/TraceAnalyticsProcessor.php
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Common/TracerTestTrait.php
  tests/Frameworks/Symfony/Version_4_0/composer.json
  tests/Frameworks/Symfony/Version_4_0/config/packages/validator.yaml
  tests/Frameworks/Symfony/Version_4_0/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_4_0/symfony.lock
  tests/Integrations/Symfony/V2_3/RouteNameSandboxedTest.php
  tests/Integrations/Symfony/V2_3/RouteNameTest.php
  tests/Integrations/Symfony/V2_8/RouteNameSandboxedTest.php
  tests/Integrations/Symfony/V2_8/RouteNameTest.php
  tests/Integrations/Symfony/V3_0/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_0/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_3/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34SandboxedTest.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
  tests/Integrations/Symfony/V3_4/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesSandboxedTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
  tests/Integrations/Symfony/V3_4/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_0/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_2/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
Labels: 📦 Sandbox API
