Repository DataDog/dd-trace-php, pull requests merged in 2019-12, with the labels that each got.

#663 [Memcached] Prevent mutation of the result code
  src/DDTrace/Integrations/Memcached/MemcachedSandboxedIntegration.php
  tests/Integrations/Memcached/MemcachedTest.php
Labels: integrations, 🐛 bug

#675 Separate PHP 5 and PHP 7 engine hooks
  config.m4
  package.xml
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch_compat_php7.c
  src/ext/engine_hooks.c
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/trace.c
  src/ext/trace.h
Labels: c-extension, 🍏 core

#676 Pin phpstan to 0.11.x
  .circleci/config.yml
Labels: ci, dev/tooling

#674 Migrate Laravel test suite to flame graph assertion and sandboxed testing
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Integrations/CLI/Laravel/V5_8/CommonScenariosSandboxedTest.php
  tests/Integrations/CLI/Laravel/V5_8/CommonScenariosTest.php
  tests/Integrations/Laravel/V4/CommonScenariosSandboxedTest.php
  tests/Integrations/Laravel/V4/CommonScenariosTest.php
  tests/Integrations/Laravel/V4/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Laravel/V4/TraceSearchConfigTest.php
  tests/Integrations/Laravel/V5_7/CommonScenariosSandboxedTest.php
  tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_7/PipelineTracingSandboxedTest.php
  tests/Integrations/Laravel/V5_7/PipelineTracingTest.php
  tests/Integrations/Laravel/V5_7/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Laravel/V5_7/TraceSearchConfigTest.php
  tests/Integrations/Laravel/V5_8/CommonScenariosSandboxedTest.php
  tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_8/TraceSearchConfigSandboxedTest.php
  tests/Integrations/Laravel/V5_8/TraceSearchConfigTest.php
Labels: dev/testing, 📦 Sandbox API

#669 Migrate Mongo library integration to sandboxed api
  .circleci/config.yml
  bridge/dd_require_all.php
  composer.json
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Mongo/MongoClientIntegration.php
  src/DDTrace/Integrations/Mongo/MongoSandboxedIntegration.php
  tests/Integrations/Mongo/MongoSandboxedTest.php
  tests/Integrations/Mongo/MongoTest.php
Labels: integrations, 📦 Sandbox API

#677 Refactor dispatch_compat*
  config.m4
  package.xml
  src/ext/compatibility.h
  src/ext/ddtrace.c
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_compat.h
  src/ext/dispatch_compat_php5.c
  src/ext/dispatch_compat_php5.h
  src/ext/dispatch_compat_php7.c
  src/ext/dispatch_setup.c
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/dispatch.c
  src/ext/php5/engine_hooks.c
  src/ext/php7/dispatch.c
  src/ext/php7/engine_hooks.c
  src/ext/serializer.c
  src/ext/span.c
  src/ext/span.h
Labels: c-extension

#679 Close open sandboxed spans on exit on PHP 7
  .circleci/valgrind/valgrind_7_3_musl_suppressions.lib
  .circleci/valgrind/valgrind_musl_suppressions.lib
  package.xml
  src/ext/dispatch.h
  src/ext/php7/dispatch.c
  src/ext/php7/engine_hooks.c
  src/ext/span.c
  src/ext/span.h
  tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
  tests/ext/sandbox/close-on-exit-retval.phpt
  tests/ext/sandbox/close-on-exit.phpt
Labels: c-extension, 🍏 core, 🏆 enhancement, 📦 Sandbox API

#680 Add test for HTTP headers being overridden
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: dev/testing

#683 Print circuit breaker errors only if DD_TRACE_DEBUG is enabled
  src/ext/circuit_breaker.c
Labels: c-extension

#682 Enable Sandboxed Symfony Integration
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
Labels: integrations, 📦 Sandbox API

#684 Fix Composer download
  dockerfiles/frameworks/src/Dockerfile
Labels: ci

#685 Disable ddtrace when incompatible extension is detected
  src/ext/ddtrace.c
Labels: c-extension

#686 Add support for tracing without limits
  src/DDTrace/Configuration.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Sampling/ConfigurableSampler.php
  src/DDTrace/Sampling/Sampler.php
  src/DDTrace/Tracer.php
  tests/Common/TracerTestTrait.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Sampling/ConfigurableSamplerTest.php
  tests/Unit/TracerTest.php
Labels: 🏆 enhancement

#688 Add extra info to curl errors
  src/DDTrace/Transport/Http.php
  tests/Integration/Transport/HttpTest.php
Labels: 🏆 enhancement

#687 Rename env DD_SAMPLING_RATE to DD_TRACE_SAMPLE_RATE
  src/DDTrace/Configuration.php
  tests/DistributedTracing/SyntheticsTest.php
  tests/Unit/ConfigurationTest.php
Labels: 🍏 core

#690 Bump version to 0.36.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: release, ⏩ Version Bump

#691 Add Empty Expect Header to Avoid Curl 100-Continue
  src/DDTrace/Transport/Http.php
  tests/Integration/Transport/HttpTest.php
Labels: 🍏 core, 🏘 community, 🐛 bug

#666 Speed up test execution in PHP 7.0, 7.1, 7.2, 7.3
  .circleci/config.yml
  .composer/.gitignore
  .dockerignore
  .gitignore
  composer.json
  docker-compose.yml
  dockerfiles/development/5.4.ini
  dockerfiles/development/Dockerfile_54
  dockerfiles/development/Dockerfile_56
  dockerfiles/development/Dockerfile_70
  dockerfiles/development/Dockerfile_71_72_73
  dockerfiles/development/dd-test-env.ini
  dockerfiles/development/install-php7-common-dependencies.sh
  tests/Frameworks/Symfony/Version_2_3/app/cache/.gitkeep
  tests/Frameworks/Symfony/Version_2_8/app/cache/.gitkeep
  tooling/bin/composer-cache
Labels: dev/testing

#695 Support OpenTracing contexts as parent contexts
  .circleci/config.yml
  composer.json
  src/DDTrace/StartSpanOptions.php
  tests/OpenTracerUnit/TracerTest.php
Labels: 🐛 bug

#696 Bump version to 0.36.1
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#642 Curl Integration: Add all available information from curl_getinfo as span tags
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Common/TracerTestTrait.php
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: integrations, 🏆 enhancement

#694 Backup and restore last error
  package.xml
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/exception_is_defined.phpt
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/get_last_error.phpt
Labels: c-extension, 🐛 bug, 📦 Sandbox API

#604 Target a specific PHP version during install
  .circleci/config.yml
  package/post-install.sh
  tests/PostInstallHook/README.md
  tests/PostInstallHook/bootstrap.php
  tests/PostInstallHook/classes.php
  tests/PostInstallHook/docker-compose.yml
  tests/PostInstallHook/run-tests.sh
  tests/PostInstallHook/test-installed.php
  tests/PostInstallHook/test-not-installed.php
Labels: packaging, 🏆 enhancement

#701 Replace "which" with "command -v" for better compatibility
  package/post-install.sh
Labels: packaging

#698 avoid `X-Datadog-Trace-Count` error in agent during dd-doctor.php requests
  src/dd-doctor.php
Labels: dev/tooling

#697 Add more information to tracing closure exceptions
  package.xml
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/exception_error_log.phpt
Labels: c-extension, 📦 Sandbox API
