Repository DataDog/dd-trace-php, pull requests merged in 2019-05, with the labels that each got.

#425 Temporarily remove Mongo tests from CI pipeline
  .circleci/config.yml
  composer.json
Labels: ci, dev/testing, 🐛 bug

#424 Bump version to 0.21.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#423 Ignore objects sent to Span::setTag()
  CHANGELOG.md
  src/DDTrace/Contracts/Span.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/Span.php
  tests/Unit/SpanTest.php
Labels: 🍏 core, 🐛 bug

#417 Implementation of `limited` tracer state in which most spans should not be created
  CHANGELOG.md
  src/DDTrace/Configuration.php
  src/DDTrace/Contracts/Tracer.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php
  src/DDTrace/Integrations/Eloquent/EloquentIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/Predis/PredisIntegration.php
  src/DDTrace/NoopTracer.php
  src/DDTrace/Tracer.php
  src/DDTrace/Util/CodeTracer.php
  tests/Common/TracerTestTrait.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Memcached/MemcachedTest.php
  tests/Integrations/Mongo/MongoTest.php
  tests/Integrations/Mysqli/MysqliTest.php
  tests/Integrations/PDO/PDOTest.php
  tests/Integrations/Predis/PredisTest.php
  tests/Unit/TracerTest.php
Labels: 🍏 core, 🏆 enhancement

#421 Add Lumen 5.6 to test suite
  tests/Frameworks/Lumen/Version_5_6/.env.example
  tests/Frameworks/Lumen/Version_5_6/.gitignore
  tests/Frameworks/Lumen/Version_5_6/app/Console/Commands/.gitkeep
  tests/Frameworks/Lumen/Version_5_6/app/Console/Kernel.php
  tests/Frameworks/Lumen/Version_5_6/app/Events/Event.php
  tests/Frameworks/Lumen/Version_5_6/app/Events/ExampleEvent.php
  tests/Frameworks/Lumen/Version_5_6/app/Exceptions/Handler.php
  tests/Frameworks/Lumen/Version_5_6/app/Http/Controllers/Controller.php
  tests/Frameworks/Lumen/Version_5_6/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_6/app/Http/Middleware/Authenticate.php
  tests/Frameworks/Lumen/Version_5_6/app/Http/Middleware/ExampleMiddleware.php
  tests/Frameworks/Lumen/Version_5_6/app/Jobs/ExampleJob.php
  tests/Frameworks/Lumen/Version_5_6/app/Jobs/Job.php
  tests/Frameworks/Lumen/Version_5_6/app/Listeners/ExampleListener.php
  tests/Frameworks/Lumen/Version_5_6/app/Providers/AppServiceProvider.php
  tests/Frameworks/Lumen/Version_5_6/app/Providers/AuthServiceProvider.php
  tests/Frameworks/Lumen/Version_5_6/app/Providers/EventServiceProvider.php
  tests/Frameworks/Lumen/Version_5_6/app/User.php
  tests/Frameworks/Lumen/Version_5_6/artisan
  tests/Frameworks/Lumen/Version_5_6/bootstrap/app.php
  tests/Frameworks/Lumen/Version_5_6/composer.json
  tests/Frameworks/Lumen/Version_5_6/database/factories/ModelFactory.php
  tests/Frameworks/Lumen/Version_5_6/database/migrations/.gitkeep
  tests/Frameworks/Lumen/Version_5_6/database/seeds/DatabaseSeeder.php
  tests/Frameworks/Lumen/Version_5_6/phpunit.xml
  tests/Frameworks/Lumen/Version_5_6/public/.htaccess
  tests/Frameworks/Lumen/Version_5_6/public/index.php
  tests/Frameworks/Lumen/Version_5_6/readme.md
  tests/Frameworks/Lumen/Version_5_6/resources/views/.gitkeep
  tests/Frameworks/Lumen/Version_5_6/routes/web.php
  tests/Frameworks/Lumen/Version_5_6/storage/app/.gitignore
  tests/Frameworks/Lumen/Version_5_6/storage/framework/cache/.gitignore
  tests/Frameworks/Lumen/Version_5_6/storage/framework/views/.gitignore
  tests/Frameworks/Lumen/Version_5_6/storage/logs/.gitignore
  tests/Frameworks/Lumen/Version_5_6/tests/ExampleTest.php
  tests/Frameworks/Lumen/Version_5_6/tests/TestCase.php
  tests/Frameworks/README.md
Labels: dev/testing

#420 Add Lumen 5.2 to tests
  tests/Frameworks/Lumen/Version_5_2/.env.example
  tests/Frameworks/Lumen/Version_5_2/.gitignore
  tests/Frameworks/Lumen/Version_5_2/app/Console/Commands/.gitkeep
  tests/Frameworks/Lumen/Version_5_2/app/Console/Kernel.php
  tests/Frameworks/Lumen/Version_5_2/app/Events/Event.php
  tests/Frameworks/Lumen/Version_5_2/app/Events/ExampleEvent.php
  tests/Frameworks/Lumen/Version_5_2/app/Exceptions/Handler.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/Controllers/Controller.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/Middleware/Authenticate.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/Middleware/ExampleMiddleware.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/routes.php
  tests/Frameworks/Lumen/Version_5_2/app/Jobs/ExampleJob.php
  tests/Frameworks/Lumen/Version_5_2/app/Jobs/Job.php
  tests/Frameworks/Lumen/Version_5_2/app/Listeners/ExampleListener.php
  tests/Frameworks/Lumen/Version_5_2/app/Providers/AppServiceProvider.php
  tests/Frameworks/Lumen/Version_5_2/app/Providers/AuthServiceProvider.php
  tests/Frameworks/Lumen/Version_5_2/app/Providers/EventServiceProvider.php
  tests/Frameworks/Lumen/Version_5_2/app/User.php
  tests/Frameworks/Lumen/Version_5_2/artisan
  tests/Frameworks/Lumen/Version_5_2/bootstrap/app.php
  tests/Frameworks/Lumen/Version_5_2/composer.json
  tests/Frameworks/Lumen/Version_5_2/database/factories/ModelFactory.php
  tests/Frameworks/Lumen/Version_5_2/database/migrations/.gitkeep
  tests/Frameworks/Lumen/Version_5_2/database/seeds/DatabaseSeeder.php
  tests/Frameworks/Lumen/Version_5_2/phpunit.xml
  tests/Frameworks/Lumen/Version_5_2/public/.htaccess
  tests/Frameworks/Lumen/Version_5_2/public/index.php
  tests/Frameworks/Lumen/Version_5_2/readme.md
  tests/Frameworks/Lumen/Version_5_2/resources/views/.gitkeep
  tests/Frameworks/Lumen/Version_5_2/storage/app/.gitignore
  tests/Frameworks/Lumen/Version_5_2/storage/framework/views/.gitignore
  tests/Frameworks/Lumen/Version_5_2/storage/logs/.gitignore
  tests/Frameworks/Lumen/Version_5_2/tests/ExampleTest.php
  tests/Frameworks/Lumen/Version_5_2/tests/TestCase.php
  tests/Frameworks/README.md
Labels: dev/testing

#431 Bump version to 0.22.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#416 Add support for Lumen
  CHANGELOG.md
  bridge/dd_require_all.php
  composer.json
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Lumen/LumenIntegration.php
  src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_2/app/Http/routes.php
  tests/Frameworks/Lumen/Version_5_2/resources/views/simple_view.blade.php
  tests/Frameworks/Lumen/Version_5_6/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_6/resources/views/simple_view.blade.php
  tests/Frameworks/Lumen/Version_5_6/routes/web.php
  tests/Frameworks/Lumen/Version_5_8/app/Http/Controllers/ExampleController.php
  tests/Frameworks/Lumen/Version_5_8/resources/views/simple_view.blade.php
  tests/Frameworks/Lumen/Version_5_8/routes/web.php
  tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_2/TraceSearchConfigTest.php
  tests/Integrations/Lumen/V5_6/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_6/TraceSearchConfigTest.php
  tests/Integrations/Lumen/V5_8/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_8/TraceSearchConfigTest.php
Labels: integrations

#422 Add support for the CLI SAPI
  CHANGELOG.md
  bridge/dd_wrap_autoloader.php
  bridge/functions.php
  composer.json
  docker-compose.yml
  phpunit.xml
  src/DDTrace/Bootstrap.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/Laravel/V4/LaravelProvider.php
  src/DDTrace/Integrations/Laravel/V5/LaravelIntegrationLoader.php
  src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php
  src/DDTrace/Integrations/Symfony/V3/SymfonyBundle.php
  src/DDTrace/Integrations/Symfony/V4/SymfonyBundle.php
  tests/Frameworks/Custom/Version_Autoloaded/run
  tests/Frameworks/Laravel/Version_4_2/phpunit.xml
  tests/Frameworks/Laravel/Version_5_7/phpunit.xml
  tests/Frameworks/Symfony/Version_3_4/app/AppKernel.php
  tests/Frameworks/Symfony/Version_3_4/phpunit.xml.dist
  tests/Integrations/CLI/CLITestCase.php
  tests/Integrations/CLI/Custom/Autoloaded/CommonScenariosTest.php
  tests/Integrations/CLI/EnvSerializer.php
  tests/Integrations/CLI/IniSerializer.php
  tests/Integrations/CLI/Laravel/V5_8/CommonScenariosTest.php
  tests/WebServer.php
Labels: feature-request, integrations, 🏆 enhancement

#433 Bump version to 0.23.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump

#435 Fix timezone warning in PHP 5
  CHANGELOG.md
  bridge/dd_wrap_autoloader.php
Labels: 🍏 core, 🐛 bug

#436 CakePHP v2 integration
  CHANGELOG.md
  bridge/dd_optional_deps_autoloader.php
  bridge/dd_require_all.php
  bridge/dd_wrap_autoloader.php
  composer.json
  docker-compose.yml
  phpunit.xml
  src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
  src/DDTrace/Integrations/CakePHP/V2/CakePHPIntegrationLoader.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  tests/Common/WebFrameworkTestCase.php
  tests/Frameworks/CakePHP/Version_2_8/app/Config/core.php
  tests/Frameworks/CakePHP/Version_2_8/app/Controller/ErrorController.php
  tests/Frameworks/CakePHP/Version_2_8/app/Controller/SimpleController.php
  tests/Frameworks/CakePHP/Version_2_8/app/Controller/SimpleViewController.php
  tests/Frameworks/CakePHP/Version_2_8/app/View/SimpleView/index.ctp
  tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
  tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php
  tests/request_replayer/index.php
Labels: integrations

#445 Add clean install of Slim PHP v3.12
  tests/Frameworks/README.md
  tests/Frameworks/Slim/Version_3_12/.gitignore
  tests/Frameworks/Slim/Version_3_12/CONTRIBUTING.md
  tests/Frameworks/Slim/Version_3_12/README.md
  tests/Frameworks/Slim/Version_3_12/composer.json
  tests/Frameworks/Slim/Version_3_12/docker-compose.yml
  tests/Frameworks/Slim/Version_3_12/logs/README.md
  tests/Frameworks/Slim/Version_3_12/phpunit.xml
  tests/Frameworks/Slim/Version_3_12/public/.htaccess
  tests/Frameworks/Slim/Version_3_12/public/index.php
  tests/Frameworks/Slim/Version_3_12/src/dependencies.php
  tests/Frameworks/Slim/Version_3_12/src/middleware.php
  tests/Frameworks/Slim/Version_3_12/src/routes.php
  tests/Frameworks/Slim/Version_3_12/src/settings.php
  tests/Frameworks/Slim/Version_3_12/templates/index.phtml
  tests/Frameworks/Slim/Version_3_12/tests/Functional/BaseTestCase.php
  tests/Frameworks/Slim/Version_3_12/tests/Functional/HomepageTest.php
Labels: dev/testing

#447 Fix invalid package.xml syntax
  package.xml
Labels: packaging, 🐛 bug, 🥒 PECL

#446 Add Slim v3 integration
  CHANGELOG.md
  bridge/dd_optional_deps_autoloader.php
  bridge/dd_require_all.php
  composer.json
  phpunit.xml
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Slim/SlimIntegration.php
  src/DDTrace/Integrations/Slim/V3/SlimIntegrationLoader.php
  tests/Frameworks/README.md
  tests/Frameworks/Slim/Version_3_12/app/SimpleViewController.php
  tests/Frameworks/Slim/Version_3_12/composer.json
  tests/Frameworks/Slim/Version_3_12/src/dependencies.php
  tests/Frameworks/Slim/Version_3_12/src/routes.php
  tests/Frameworks/Slim/Version_3_12/templates/simple_view.phtml
  tests/Integrations/Slim/V3_12/CommonScenariosTest.php
  tests/WebServer.php
Labels: integrations

#448 Validate package.xml in CI checks
  Makefile
Labels: ci, dev/testing, 🥒 PECL

#442 Normalized URL as the resource name
  CHANGELOG.md
  bridge/dd_require_all.php
  src/DDTrace/Bootstrap.php
  src/DDTrace/Configuration.php
  src/DDTrace/Http/Urls.php
  src/DDTrace/Integrations/Lumen/V5/LumenIntegrationLoader.php
  src/DDTrace/Obfuscation/WildcardToRegex.php
  src/DDTrace/Tracer.php
  tests/Common/WebFrameworkTestCase.php
  tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
  tests/Unit/Http/UrlsTest.php
  tests/Unit/Obfuscation/WildcardToRegexTest.php
Labels: integrations, 🍏 core, 🏆 enhancement

#453 Release 0.25.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: 🍏 core

#457 Narrow the URL normalization rules boundaries
  CHANGELOG.md
  src/DDTrace/Http/Urls.php
  tests/Unit/Http/UrlsTest.php
Labels: 🍏 core, 🐛 bug

#458 Bump version to 0.26.0
  CHANGELOG.md
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: ⏩ Version Bump
