Repository DataDog/dd-trace-php, pull requests merged in 2020-12, with the labels that each got.

#1116 Rebuild CentOS 6 containers
  .circleci/config.yml
  Makefile
  docker-compose.yml
  dockerfiles/ci/centos/6/Dockerfile
  dockerfiles/ci/centos/6/Dockerfile_php5
  dockerfiles/ci/centos/6/Dockerfile_php7
  dockerfiles/ci/centos/6/Dockerfile_php8
  dockerfiles/ci/centos/6/docker-compose.yml
  dockerfiles/ci/centos/6/download-src.sh
  dockerfiles/ci/centos/6/php-5.4/configure.sh
  dockerfiles/ci/centos/6/php-5.5/Dockerfile
  dockerfiles/ci/centos/6/php-5.6/configure.sh
  dockerfiles/ci/centos/6/php-7.0/configure.sh
  dockerfiles/ci/centos/6/php-7.1/configure.sh
  dockerfiles/ci/centos/6/php-7.2/configure.sh
  dockerfiles/ci/centos/6/php-7.3/configure.sh
  dockerfiles/ci/centos/6/php-7.4/configure.sh
  dockerfiles/ci/centos/6/php-8.0/Dockerfile
  dockerfiles/ci/centos/6/php-8.0/switch-php
  dockerfiles/ci/centos/6/switch-php
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/docker-compose.yml
  dockerfiles/verify_packages/verify_rpm_5.5.sh
  dockerfiles/verify_packages/verify_rpm_centos6.sh
  package/post-install.sh
Labels: ci, dev/tooling, 🐛 bug

#1109 Attach fatal errors to userland root span on PHP 5
  ext/php5/ddtrace.c
  ext/php5/ddtrace.h
  ext/php5/engine_hooks.c
  ext/php5/engine_hooks.h
  ext/php5/serializer.c
  ext/php5/span.h
  tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
  tests/Integrations/Custom/Autoloaded/FatalErrorTest.php
  tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
  tests/Integrations/WordPress/V5_5/CommonScenariosTest.php
Labels: c-extension, 🍏 core, 🏆 enhancement

#1113 NullLogger is essential, not optional
  bridge/_files.php
  bridge/dd_register_optional_deps_autoloader.php
Labels: 🐛 bug, 🥒 PECL

#1121 Fix multiple deferred integration loading on PHP from 7.0 to 7.2
  .gitignore
  Makefile
  docker-compose.yml
  ext/php7/dispatch.c
  ext/php7/dispatch.h
  ext/php7/engine_api.c
  ext/php7/integrations/integrations.c
  src/DDTrace/Transport/Http.php
  tests/Integrations/DeferredLoading/DeferredLoadingTest.php
  tests/Integrations/DeferredLoading/index.php
Labels: c-extension, 🐛 bug

#1120 Make Uri to resource name normalization case insensitive
  src/private/functions.php
  tests/Unit/private/UriTest.php
Labels: 🐛 bug

#1124 Fix error in case of x-datadog-origin header in distributed tracing on PHP 7.0-7.2
  .circleci/config.yml
  Makefile
  ext/php7/engine_api.c
  ext/php8/engine_api.c
  playground/start-server.sh
  tests/C2PHP/get_context_distributed_tracing_test.phpt
  tests/Common/TracerTestTrait.php
  tests/DistributedTracing/GH1070OriginHeaderSegfault/GH1070OriginHeaderSegfaultTest.php
  tests/DistributedTracing/GH1070OriginHeaderSegfault/index.php
  tests/Frameworks/Util/Request/GetSpec.php
  tests/Frameworks/Util/Request/RequestSpec.php
  tests/Sapi/PhpFpm/PhpFpm.php
Labels: 🐛 bug

#1125 Add function to correctly extract trace id in all context
  .phpcs.xml
  ext/php5/ddtrace.c
  ext/php7/ddtrace.c
  ext/php8/ddtrace.c
  tests/Common/TracerTestTrait.php
  tests/Integration/CurrentContextAccess/CurrentContextAccessTest.php
  tests/Integration/CurrentContextAccess/long-running.php
  tests/Integration/CurrentContextAccess/short-running.php
  tests/Integration/CurrentContextAccess/web.php
Labels: 🐛 bug

#1126 Bump version 0.53.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release, ⏩ Version Bump
