Repository DataDog/dd-trace-php, pull requests merged in 2020-10, with the labels that each got.

#1026 Compile src/DDTrace/version.php into _generated.php to avoid loading it at runtime
  Makefile
  package.xml
  playground/index.php
  playground/start-server.sh
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/dd-doctor.php
  src/ext/version.h
  tests/Composer/app/index.php
  tooling/bin/pecl-build
Labels: 🍏 core

#1032 Skip bug 64146 on PHP 5.5
  dockerfiles/ci/xfail_tests/5.5.list
Labels: dev/testing

#1027 Build on PHP 8.0.0 beta4
  .circleci/config.yml
  .circleci/valgrind/8_0_musl_valgrind.rc
  .circleci/valgrind/valgrind_8_0_musl_suppressions.lib
  Makefile
  composer.json
  config.m4
  docker-compose.yml
  dockerfiles/ci/README.md
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/buster/php-8.0/Dockerfile
  dockerfiles/ci/buster/php-8.0/configure.sh
  dockerfiles/ci/buster/php-8.0/welcome
  dockerfiles/ci/buster/php-master/Dockerfile
  dockerfiles/ci/buster/php-master/install-php-master
  dockerfiles/ci/buster/php-master/welcome
  dockerfiles/ci/buster/switch-php
  src/ext/comms_php.c
  src/ext/comms_php.h
  src/ext/compat_string.c
  src/ext/compatibility.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/distributed_tracing.h
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php7/dispatch.c
  src/ext/php7/engine_api.c
  src/ext/php7/engine_api.h
  src/ext/php7/engine_hooks.c
  src/ext/php7/serializer.c
  src/ext/request_hooks.c
  tests/ext/from_php_7_3_bug61728.phpt
  tests/ext/request-init-hook/error_get_last_is_unaffected.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_exceptions.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
  tests/ext/request-init-hook/shebang.phpt
  tests/ext/sandbox-prehook/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/exception_from_user_error_handler_internal.phpt
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/get_last_error.phpt
  tests/ext/sandbox/hook_function/posthook_error_02.phpt
  tests/ext/sandbox/hook_function/prehook_error_02.phpt
  tests/ext/sandbox/hook_method/posthook_error_02.phpt
  tests/ext/sandbox/hook_method/prehook_error_02.phpt
  tests/ext/sandbox/safe_to_string_metadata.phpt
  tests/ext/sandbox/safe_to_string_properties.phpt
  tests/ext/segfault_backtrace_disabled.phpt
  tests/ext/segfault_backtrace_enabled.phpt
Labels: c-extension, ci, 🏆 enhancement

#1035 Always run build_package workflow
  .circleci/config.yml
Labels: ci

#1037 Remove dead code
  src/ext/ddtrace.h
  src/ext/dispatch.h
  src/ext/php5/dispatch.c
  src/ext/php5_4/dispatch.c
  src/ext/php7/dispatch.c
Labels: c-extension

#1036 Build on PHP 8.0.0 RC 1 (without a shippable build)
  dockerfiles/ci/buster/docker-compose.yml
  src/ext/ddtrace.c
  src/ext/engine_hooks.c
  src/ext/php5_4/engine_hooks.c
Labels: c-extension, ci

#1034 Attach fatal errors to all open internal spans
  package.xml
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/fatal_errors_are_tracked_005.phpt
Labels: c-extension, 🏆 enhancement

#1038 Assert both 0 and 1 work as values for DD_TRACE_SAMPLE_RATE
  tests/Unit/Sampling/ConfigurableSamplerTest.php
Labels: dev/testing

#1044 Sort langauge xfail lists
  dockerfiles/ci/xfail_tests/5.4.list
  dockerfiles/ci/xfail_tests/5.6.list
  dockerfiles/ci/xfail_tests/7.0.list
  dockerfiles/ci/xfail_tests/7.1.list
  dockerfiles/ci/xfail_tests/7.2.list
  dockerfiles/ci/xfail_tests/7.4.list
Labels: dev/testing, dev/tooling

#1047 Update PHP language xfail lists
  dockerfiles/ci/xfail_tests/5.5.list
  dockerfiles/ci/xfail_tests/7.3.list
  dockerfiles/ci/xfail_tests/7.4.list
Labels: dev/testing, dev/tooling

#774 Build alpine packages on alpine and add e2e package verification
  .circleci/config.yml
  Makefile
  dockerfiles/compile_extension/Dockerfile_alpine
  dockerfiles/compile_extension/Makefile
  dockerfiles/compile_extension/build-dd-trace-php
  dockerfiles/compile_extension/docker-compose.yml
  dockerfiles/compile_extension/docker-php-source
  dockerfiles/compile_extension/install-php
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/alpine/install.sh
  dockerfiles/verify_packages/docker-compose.yml
  dockerfiles/verify_packages/index.php
  dockerfiles/verify_packages/verify.sh
  dockerfiles/verify_packages/verify_apk.sh
  package/post-install.sh
  src/ext/php5_4/dispatch.c
Labels: ci, packaging

#1041 Experimental PHP 8.0.0 RC 1 support
  .circleci/config.yml
  Makefile
  docker-compose.yml
  dockerfiles/ci/centos/6/docker-compose.yml
  dockerfiles/ci/centos/6/php-5.5/Dockerfile
  dockerfiles/ci/centos/6/php-5.5/modules/php/.version
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug-zts
  dockerfiles/ci/centos/6/php-5.5/switch-php
  dockerfiles/ci/centos/6/php-8.0/Dockerfile
  dockerfiles/ci/centos/6/php-8.0/configure.sh
  dockerfiles/ci/centos/6/php-8.0/download-src.sh
  dockerfiles/ci/centos/6/php-8.0/switch-php
  tests/Frameworks/Symfony/Version_4_0/composer.lock
Labels: c-extension, ci

#942 Fix naming of wp5 testing app and laravel 57 makefile
  dockerfiles/testing-environment/Laravel57/Makefile
  dockerfiles/testing-environment/Wordpress5/docker-compose.yml
Labels: dev/tooling

#1050 Disable instrumenting generators on PHP 5
  package.xml
  src/ext/php5/engine_hooks.c
  tests/ext/sandbox/generator_php5.phpt
Labels: c-extension, 🍏 core

#1051 Bump version to 0.49.0
  package.xml
  src/DDTrace/Tracer.php
  src/ext/version.h
Labels: release, ⏩ Version Bump

#1053 Experimental support for PHP 8.0.0 RC 2
  dockerfiles/ci/centos/6/docker-compose.yml
Labels: ci, 🏆 enhancement

#1048 Trace Symfony controller and more
  Makefile
  src/DDTrace/Integrations/Symfony/SymfonyIntegration.php
  tests/Integrations/Symfony/V2_3/RouteNameTest.php
  tests/Integrations/Symfony/V2_8/RouteNameTest.php
  tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
  tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_2/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V4_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_4/TraceSearchConfigTest.php
Labels: integrations, 🏆 enhancement

#1062 Tests: add Symfony 5 tests
  Makefile
  tests/Frameworks/Symfony/Version_5_0/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_5_0/templates/twig_template.html.twig
  tests/Frameworks/Symfony/Version_5_1/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_5_1/templates/twig_template.html.twig
  tests/Integrations/Symfony/V5_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V5_1/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_1/TraceSearchConfigTest.php
Labels: dev/testing, hacktoberfest-accepted, integrations

#1064 invoke make generate in overhead measurement sample app
  tests/overhead/dockerfiles/Dockerfile_73_fpm_head
  tests/overhead/dockerfiles/Dockerfile_73_fpm_master
Labels: dev/tooling

#1058 Add tests and support for WP5
  Makefile
  src/DDTrace/Integrations/WordPress/WordPressIntegration.php
  tests/Frameworks/WordPress/Version_5_5/.gitattributes
  tests/Frameworks/WordPress/Version_5_5/.htaccess
  tests/Frameworks/WordPress/Version_5_5/README.md
  tests/Frameworks/WordPress/Version_5_5/wp-config.php
  tests/Frameworks/WordPress/Version_5_5/wp-content/plugins/datadog/datadog.php
  tests/Frameworks/WordPress/Version_5_5/wp_2020-10-21.sql
  tests/Integrations/WordPress/V5_5/CommonScenariosTest.php
Labels: integrations

#1040 Add fatal error info to DDTrace\Tracer made root spans on PHP 7
  .circleci/valgrind/valgrind_8_0_musl_suppressions.lib
  dockerfiles/ci/xfail_tests/5.6.list
  src/DDTrace/Span.php
  src/DDTrace/Tracer.php
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/logging.c
  src/ext/logging.h
  src/ext/php5/serializer.c
  src/ext/php7/engine_api.h
  src/ext/php7/engine_hooks.c
  src/ext/php7/serializer.c
  src/ext/serializer.h
  src/ext/span.c
  src/ext/span.h
  tests/Common/SpanAssertion.php
  tests/Frameworks/Custom/Version_Autoloaded/src/FatalErrorController.php
  tests/Frameworks/Custom/Version_Autoloaded/src/routes.php
  tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
  tests/Integrations/Custom/Autoloaded/FatalErrorTest.php
  tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
  tests/Integrations/WordPress/V5_5/CommonScenariosTest.php
  tests/Unit/SpanTest.php
  tests/ext/sandbox/fatal_errors_are_tracked_005.phpt
Labels: c-extension, 🏆 enhancement

#1049 Add example for long running processes
  .phpcs.xml
  examples/long-running/Dockerfile
  examples/long-running/README.md
  examples/long-running/docker-compose.yml
  examples/long-running/long-running-script.php
Labels: 📚 docs
