Repository DataDog/dd-trace-php, pull requests merged in 2020-01, with the labels that each got.

#703 Move dogstatsd client init to rinit
  config.m4
  package.xml
  src/dogstatsd/README.md
  src/dogstatsd/client.c
  src/dogstatsd/dogstatsd_client/client.h
  src/dogstatsd/test/client.cc
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dogstatsd_client.c
  src/ext/dogstatsd_client.h
  src/ext/signals.c
  tests/ext/segfault_backtrace_enabled.phpt
Labels: c-extension

#705 Add gauge, histogram, and generic metric helpers
  src/dogstatsd/CMakeLists.txt
  src/dogstatsd/client.c
  src/dogstatsd/dogstatsd_client/client.h
  src/dogstatsd/test/client.cc
Labels: c-extension

#706 Remove unnecessary macro and header include
  src/ext/logging.c
  src/ext/logging.h
Labels: c-extension

#702 Handle out-of-sync spans
  package.xml
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/span.c
  tests/ext/sandbox/spans_out_of_sync.phpt
Labels: c-extension, 🍏 core, 🐛 bug, 📦 Sandbox API

#707 Sandbox tracer flushing
  package.xml
  src/DDTrace/Bootstrap.php
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/fatal_errors_ignored_in_shutdown.phpt
Labels: 📦 Sandbox API

#709 Ensure errors raised in request init hook do not affect error_get_last()
  package.xml
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/request_hooks.c
  src/ext/sandbox.h
  tests/ext/request-init-hook/error_get_last_is_unaffected.phpt
  tests/ext/request-init-hook/raises_e_notice.php
  tests/ext/request-init-hook/request_init_hook_confined_to_open_basedir.phpt
  tests/ext/request-init-hook/request_init_hook_file_not_found.phpt
  tests/ext/sandbox/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox/fatal_errors_ignored_in_tracing_closure_php7.phpt
Labels: c-extension, 🍏 core

#710 Add test to hit memory limit in a shutdown hook
  package.xml
  tests/ext/sandbox/memory_limit_graceful_bailout.phpt
Labels: dev/testing, 📦 Sandbox API

#708 Enhance OpenTracing StartSpanOptions support
  composer.json
  src/DDTrace/OpenTracer/Tracer.php
  tests/OpenTracerUnit/TracerTest.php
Labels: 🐛 bug

#712 Make memory-limit test less flaky
  tests/ext/sandbox/memory_limit_graceful_bailout.phpt
Labels: dev/testing, 📦 Sandbox API

#713 Bump version to 0.37.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#715 Move framework Docker containers to dd-trace-ci
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/flow.yml
  dockerfiles/frameworks/laravel.yml
  dockerfiles/frameworks/src/Dockerfile
  dockerfiles/frameworks/src/entrypoint.sh
  dockerfiles/frameworks/src/flow/20-redis.ini
  dockerfiles/frameworks/src/flow/30.tz.ini
  dockerfiles/frameworks/src/flow/Settings.yaml
  dockerfiles/frameworks/src/flow/patch.patch
  dockerfiles/frameworks/src/flow/run.sh
  dockerfiles/frameworks/src/laravel/patch.patch
  dockerfiles/frameworks/src/switch_php.sh
  dockerfiles/frameworks/src/symfony/run.sh
  dockerfiles/frameworks/src/symfony/v4.3.4.patch
  dockerfiles/frameworks/src/wordpress/4.8.10.patch
  dockerfiles/frameworks/src/wordpress/run.sh
  dockerfiles/frameworks/src/wordpress/wp-tests-config.php
  dockerfiles/frameworks/symfony.yml
  dockerfiles/frameworks/wordpress.yml
Labels: ci, dev/testing, dev/tooling

#711 Add heartbeat health metric
  docker-compose.yml
  src/dogstatsd/client.c
  src/dogstatsd/dogstatsd_client/client.h
  src/dogstatsd/test/client.cc
  src/ext/configuration.c
  src/ext/configuration.h
  src/ext/configuration_php_iface.c
  src/ext/configuration_render.h
  src/ext/dogstatsd_client.c
  src/ext/env_config.c
  src/ext/env_config.h
Labels: c-extension, 🏆 enhancement

#716 Set global tags in internal spans
  src/DDTrace/Tracer.php
  tests/Integration/TracerTest.php
Labels: 🐛 bug

#721 Hotfix release 0.37.1
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/flow.yml
  dockerfiles/frameworks/laravel.yml
  dockerfiles/frameworks/src/Dockerfile
  dockerfiles/frameworks/src/entrypoint.sh
  dockerfiles/frameworks/src/flow/20-redis.ini
  dockerfiles/frameworks/src/flow/30.tz.ini
  dockerfiles/frameworks/src/flow/Settings.yaml
  dockerfiles/frameworks/src/flow/patch.patch
  dockerfiles/frameworks/src/flow/run.sh
  dockerfiles/frameworks/src/laravel/patch.patch
  dockerfiles/frameworks/src/switch_php.sh
  dockerfiles/frameworks/src/symfony/run.sh
  dockerfiles/frameworks/src/symfony/v4.3.4.patch
  dockerfiles/frameworks/src/wordpress/4.8.10.patch
  dockerfiles/frameworks/src/wordpress/run.sh
  dockerfiles/frameworks/src/wordpress/wp-tests-config.php
  dockerfiles/frameworks/symfony.yml
  dockerfiles/frameworks/wordpress.yml
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
  tests/Integration/TracerTest.php
Labels: ⏩ Version Bump

#720 RELEASING.md was removed
  README.md
Labels: 📚 docs

#719 PHP 5.4: Remove sandbox API
  package.xml
  src/ext/ddtrace.c
  tests/ext/sandbox/sandbox_api_not_available_on_unsupported_versions.phpt
Labels: c-extension, 🍏 core, 📦 Sandbox API

#724 Update coms code style to C99
  src/ext/coms.c
  src/ext/coms.h
  src/ext/coms_curl.c
  src/ext/coms_curl.h
  src/ext/coms_debug.c
  src/ext/coms_debug.h
Labels: c-extension

#730 Fix msgpack serialization with a reference
  package.xml
  src/ext/ddtrace.c
  src/ext/serializer.c
  tests/ext/dd_trace_serialize_msgpack_error.phpt
  tests/ext/dd_trace_serialize_msgpack_error_strict.phpt
  tests/ext/dd_trace_serialize_msgpack_reference.phpt
Labels: c-extension, 🐛 bug

#731 Release 0.38.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#732 Add new license files to package.xml
  dockerfiles/ci/xfail_tests/7.4.list
  package.xml
Labels: 🥒 PECL

#735 Bump version to 0.38.1
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#738 Update background sender
  config.m4
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  src/ext/arrays.c
  src/ext/arrays.h
  src/ext/comms_php.c
  src/ext/comms_php.h
  src/ext/coms.c
  src/ext/coms.h
  src/ext/coms_curl.c
  src/ext/coms_curl.h
  src/ext/coms_debug.c
  src/ext/ddtrace.c
  tests/bootstrap.php
  tests/ext/dd_trace_coms_curl_out.phpt
  tests/ext/dd_trace_coms_test_parallel_writer_consistency.phpt
  tests/ext/dd_trace_coms_test_span_concatenation.phpt
  tests/ext/dd_trace_coms_writer_shutdown_and_flush_on_exit.phpt
  tests/ext/dd_trace_send_traces_via_thread.phpt
Labels: c-extension, 🏆 enhancement

#739 Bump version and release 0.39.0
  composer.json
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: release, ⏩ Version Bump

#740 Increase available memory for PHP 5.6 Web Integration tests
  .circleci/config.yml
  composer.json
Labels: dev/testing
