Repository DataDog/dd-trace-php, pull requests merged in 2020-09, with the labels that each got.

#1009 Sandbox flush in limited mode on PHP 5.4
  src/DDTrace/Bootstrap.php
Labels: 🍏 core

#1011 Update excluded modules
  CONTRIBUTING.md
  config.m4
  package.xml
  src/ext/blacklist.h
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/debug.h
  src/ext/dispatch.c
  src/ext/excluded_modules.h
  src/ext/memory_limit.c
  src/ext/php5/blacklist.c
  src/ext/php5/dispatch.c
  src/ext/php5/excluded_modules.c
  src/ext/php5/startup_logging.c
  src/ext/php5_4/dispatch.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/php7/excluded_modules.c
  src/ext/php7/startup_logging.c
  tests/xdebug/2.9.2/startup_logging_diagnostics.phpt
Labels: c-extension

#1013 Call ddtrace_engine_hooks_{rinit,rshutdown}
  src/ext/ddtrace.c
Labels: c-extension, 🐛 bug

#1014 Deprecate dd-doctor.php
  .github/ISSUE_TEMPLATE/bug_report.md
  src/dd-doctor.php
Labels: dev/tooling, 📚 docs

#1015 Release 0.48.2
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  config.m4
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/dd-doctor.php
  src/ext/blacklist.h
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/debug.h
  src/ext/dispatch.c
  src/ext/excluded_modules.h
  src/ext/memory_limit.c
  src/ext/php5/blacklist.c
  src/ext/php5/dispatch.c
  src/ext/php5/excluded_modules.c
  src/ext/php5/startup_logging.c
  src/ext/php5_4/dispatch.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/php7/excluded_modules.c
  src/ext/php7/startup_logging.c
  src/ext/version.h
  tests/xdebug/2.9.2/startup_logging_diagnostics.phpt
Labels: release, ⏩ Version Bump

#1008 Support PHP 5.5
  .circleci/config.yml
  .circleci/php-5.5_web.txt
  composer.json
  dockerfiles/ci/centos/6/docker-compose.yml
  dockerfiles/ci/centos/6/php-5.5/Dockerfile
  dockerfiles/ci/centos/6/php-5.5/configure.sh
  dockerfiles/ci/centos/6/php-5.5/modules/php/.version
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug
  dockerfiles/ci/centos/6/php-5.5/modules/php/5.5-debug-zts
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/docker-compose.yml
  dockerfiles/verify_packages/verify_rpm.sh
  dockerfiles/verify_packages/verify_rpm_5.5.sh
  package.xml
  src/ext/php5/engine_hooks.c
  src/ext/request_hooks.c
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/Integrations/Memcached/MemcachedTest.php
  tests/Unit/TracerTest.php
  tests/ext/request-init-hook/raises_fatal_error.php
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
Labels: c-extension, 🍏 core, 🏆 enhancement

#1018 Add Slim 3 to PHP 5.5's test suite
  .circleci/php-5.5_web.txt
  composer.json
  tests/Frameworks/Slim/Version_3_12/composer.json
  tests/Integrations/Slim/V3_12/CommonScenariosTest.php
Labels: dev/testing

#1019 Add PHP 5.4 to PECL build
  .circleci/config.yml
  config.m4
  package.xml
  tests/ext/call_user_func/namespaced-array.phpt
  tests/ext/call_user_func/namespaced.phpt
  tests/ext/call_user_func/not-namespaced-array.phpt
  tests/ext/call_user_func/not-namespaced.phpt
  tests/ext/request-init-hook/error_get_last_is_unaffected.phpt
  tests/ext/request-init-hook/request_init_hook_confined_to_open_basedir.phpt
  tests/ext/request-init-hook/request_init_hook_contains_non_printable_character.phpt
  tests/ext/request-init-hook/request_init_hook_file_not_found.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_exceptions.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors_php_54.phpt
  tests/ext/request-init-hook/run_file_before_request_handling.phpt
  tests/ext/sandbox-prehook/php5_unsupported.phpt
  tests/ext/sandbox-regression/access_modifier_method_access_hook.phpt
  tests/ext/sandbox-regression/access_modifier_property_access_hook.phpt
  tests/ext/sandbox-regression/allow_overriding_before_overrided_methods_functions_are_defined.phpt
  tests/ext/sandbox-regression/case_insensitive_method_hook.phpt
  tests/ext/sandbox-regression/closure_accessing_outside_variables.phpt
  tests/ext/sandbox-regression/closure_set_inside_object_methods.phpt
  tests/ext/sandbox-regression/dd_trace_tracer_is_limited_hard.phpt
  tests/ext/sandbox-regression/destructor_called_when_this_gets_out_of_scope.phpt
  tests/ext/sandbox-regression/disable_tracing_disables_tracing.phpt
  tests/ext/sandbox-regression/do_not_check_if_class_or_function_exists_by_default.phpt
  tests/ext/sandbox-regression/extension_disabled.phpt
  tests/ext/sandbox-regression/method_invoked_via_reflection.phpt
  tests/ext/sandbox-regression/method_returning_array.phpt
  tests/ext/sandbox-regression/multiple_instrumentations.phpt
  tests/ext/sandbox-regression/namespaces.phpt
  tests/ext/sandbox-regression/overriding_construct.phpt
  tests/ext/sandbox-regression/overriding_method_defined_in_parent.phpt
  tests/ext/sandbox-regression/private_method_hook.phpt
  tests/ext/sandbox-regression/private_self_access.phpt
  tests/ext/sandbox-regression/protected_method_hook.phpt
  tests/ext/sandbox-regression/recursion.phpt
  tests/ext/sandbox-regression/reset_configured_overrides.phpt
  tests/ext/sandbox-regression/reset_function_tracing.phpt
  tests/ext/sandbox-regression/return_value_passed.phpt
  tests/ext/sandbox-regression/simple_function_hook.phpt
  tests/ext/sandbox-regression/simple_method_hook.phpt
  tests/ext/sandbox-regression/throw_exception.phpt
  tests/ext/sandbox-regression/trace_method_or_function_that_will_exist_later.phpt
  tests/ext/sandbox-regression/trace_static_method.phpt
  tests/ext/sandbox-regression/used_dispatch_shouldn_t_be_freed.phpt
  tests/ext/sandbox-regression/variable_length_parameter_list.phpt
  tests/ext/sandbox-regression/with_params_method_hook.phpt
  tests/ext/sandbox/preinitialized_tracing_of_method.phpt
  tests/ext/sandbox/return_by_ref.phpt
  tests/ext/traced_internal_functions_override_01.phpt
Labels: dev/testing, 🥒 PECL

#1022 Fix sigsegv in deferred loading
  package.xml
  src/ext/php7/engine_api.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/deferred_load_missing_load_fn.phpt
Labels: c-extension, 🐛 bug

#1024 Harden curl integration
  package.xml
  src/ext/php7/engine_api.c
  src/ext/php7/engine_api.h
  src/ext/php7/handlers_curl.c
  tests/ext/sandbox/distributed_tracing_curl_missing_fn.phpt
Labels: c-extension, dev/testing

#1023 Release 0.48.3
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/php7/engine_api.c
  src/ext/php7/engine_hooks.c
  src/ext/version.h
  tests/ext/sandbox/deferred_load_missing_load_fn.phpt
Labels: release, ⏩ Version Bump, 🐛 bug

#1025 Add Levi and Luca as lead developers to package.xml
  package.xml
Labels: 🥒 PECL

#1030 Add more tests for PHP 5.5
  .circleci/config.yml
  dockerfiles/ci/xfail_tests/5.5.list
Labels: dev/testing

#1031 Add back support for trace analytics to curl integration
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: 🐛 bug

#1028 Close open spans on fatal errors
  .circleci/valgrind/valgrind_musl_suppressions.lib
  dockerfiles/ci/xfail_tests/7.3.list
  package.xml
  src/ext/compatibility.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php5/serializer.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/php7/serializer.c
  tests/ext/sandbox-prehook/exception_handling.phpt
  tests/ext/sandbox/exception_handling.phpt
  tests/ext/sandbox/fatal_errors_are_tracked_001.phpt
  tests/ext/sandbox/fatal_errors_are_tracked_002.phpt
  tests/ext/sandbox/fatal_errors_are_tracked_003_php5.phpt
  tests/ext/sandbox/fatal_errors_are_tracked_003_php7.phpt
  tests/ext/sandbox/fatal_errors_are_tracked_004.phpt
Labels: c-extension, 🏆 enhancement
