Repository DataDog/dd-trace-php, pull requests merged in 2020-03, with the labels that each got.

#776 Log background sender messages to error_log
  phpunit.xml
  src/ext/coms.c
  src/ext/ddtrace.c
  src/ext/logging.c
  src/ext/logging.h
  tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
Labels: c-extension

#779 Bump version to 0.41.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: ⏩ Version Bump

#780 Close open sandboxed spans on exit (PHP 5)
  src/ext/php5/engine_hooks.c
  src/ext/span.c
  src/ext/span.h
  tests/ext/sandbox/close-on-exit-retval.phpt
  tests/ext/sandbox/close-on-exit.phpt
  tests/ext/sandbox/exit_and_drop_span.phpt
Labels: c-extension, 🍏 core, 🏆 enhancement, 📦 Sandbox API

#781 Fix pecl installs
  config.m4
Labels: c-extension, packaging, 🐛 bug

#783 Fix background sender logging for ZTS
  src/ext/ddtrace.c
  src/ext/logging.c
  src/ext/logging.h
Labels: c-extension, 🐛 bug

#789 Remove old internal background sender tests
  package.xml
  tests/ext/dd_trace_coms_curl_out.phpt
  tests/ext/dd_trace_coms_test_parallel_writer_consistency.phpt
  tests/ext/dd_trace_coms_test_span_concatenation.phpt
  tests/ext/dd_trace_coms_writer_shutdown_and_flush_on_exit.phpt
Labels: dev/testing

#784 Prehook: run tracing closures before the original call (PHP 7)
  .circleci/config.yml
  package.xml
  src/ext/ddtrace.c
  src/ext/dispatch.h
  src/ext/php7/engine_hooks.c
  tests/ext/dd_trace_api_error.phpt
  tests/ext/sandbox-prehook/access_modifier_method_access_hook.phpt
  tests/ext/sandbox-prehook/access_modifier_property_access_hook.phpt
  tests/ext/sandbox-prehook/args_copy_before_mutation.phpt
  tests/ext/sandbox-prehook/close_on_exit.phpt
  tests/ext/sandbox-prehook/closure_arg_exception.phpt
  tests/ext/sandbox-prehook/closure_arg_retval.phpt
  tests/ext/sandbox-prehook/dd_trace_api_error.phpt
  tests/ext/sandbox-prehook/dd_trace_function_internal.phpt
  tests/ext/sandbox-prehook/dd_trace_function_userland.phpt
  tests/ext/sandbox-prehook/dd_trace_method.phpt
  tests/ext/sandbox-prehook/dd_trace_method_binds_called_object.phpt
  tests/ext/sandbox-prehook/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/sandbox-prehook/drop_spans.phpt
  tests/ext/sandbox-prehook/exception_error_log.phpt
  tests/ext/sandbox-prehook/exception_handling.phpt
  tests/ext/sandbox-prehook/exceptions_and_errors_are_ignored_in_tracing_closure.phpt
  tests/ext/sandbox-prehook/exit_and_drop_span.phpt
  tests/ext/sandbox-prehook/keep_spans_in_limited_tracing_userland_functions.phpt
  tests/ext/sandbox-prehook/new_static.phpt
  tests/ext/sandbox-prehook/php5_unsupported.phpt
  tests/ext/sandbox-prehook/trace_static_method.phpt
  tests/ext/sandbox-prehook/variable_length_parameter_list.phpt
  tests/ext/sandbox/dd_trace_api_error.phpt
Labels: c-extension, 🍏 core, 🏆 enhancement, 📦 Sandbox API

#791 Pass return value as null to tracing closure when value IS_UNDEF
  package.xml
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/retval_is_null_with_exception.phpt
Labels: c-extension, 🐛 bug, 📦 Sandbox API

#786 Refactor Symfony integration
  src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
Labels: integrations, 📦 Sandbox API

#792 Set a sane memory limit when running php from inside post-install hook
  package/post-install.sh
Labels: packaging

#799 Avoid strdup
  src/ext/env_config.c
  src/ext/env_config.h
  src/ext/logging.c
Labels: c-extension, 🐛 bug

#796 Enable background sender (BGS) by default
  src/ext/configuration.h
  tests/ext/read_c_configuration.phpt
Labels: 🍏 core, 🏆 enhancement

#804 Let curl calculate Content-Length header value when sending requests to the agent
  playground/start-server.sh
  src/DDTrace/Transport/Http.php
  tests/Integration/Transport/HttpTest.php
Labels: 🐛 bug

#802 Add xdebug helpers
  docker-compose.yml
  tooling/bin/install-xdebug.sh
Labels: dev/tooling

#800 Enable background sender in tests
  src/DDTrace/Transport/Http.php
  src/ext/compatibility.h
  src/ext/coms.c
  src/ext/configuration.h
  tests/Common/TracerTestTrait.php
  tests/Common/WebFrameworkTestCase.php
  tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
  tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
  tests/Integrations/Custom/Autoloaded/TraceSearchConfigTest.php
  tests/ext/read_c_configuration.phpt
Labels: dev/testing
