Repository DataDog/dd-trace-php, pull requests merged in 2020-07, with the labels that each got.

#803 Add support for DD_VERSION and DD_ENV variables
  bridge/configuration.php
  src/DDTrace/Span.php
  src/DDTrace/Tracer.php
  src/api/Configuration.php
  src/api/Tag.php
  tests/Integration/TracerTest.php
  tests/OpenTracerUnit/TracerTest.php
  tests/Unit/ConfigurationTest.php
Labels: 🏆 enhancement

#939 Add nginx + php-fpm example app for docs
  examples/README.md
  examples/nginx-php-fpm/.env
  examples/nginx-php-fpm/Dockerfile_php_fpm
  examples/nginx-php-fpm/README.md
  examples/nginx-php-fpm/default.conf
  examples/nginx-php-fpm/docker-compose.yml
  examples/nginx-php-fpm/public/index.php
  examples/nginx-php-fpm/www.conf
Labels: 📚 docs

#940 Extract ddtrace_sandbox_begin/ddtrace_sandbox_end helpers
  src/ext/engine_hooks.c
  src/ext/engine_hooks.h
  src/ext/php5/engine_hooks.c
  src/ext/php7/engine_hooks.c
  src/ext/php7/handlers_curl.c
Labels: c-extension

#943 Make compilation to single file compatible with `include __DIR__ . '...'` in files
  composer.json
Labels: packaging, 🐛 bug

#946 Enable sandboxed integration for Symfony on PHP 5
  src/DDTrace/Integrations/IntegrationsLoader.php
Labels: integrations, 📦 Sandbox API

#947 Add Apache + mode_php example app for docs
  examples/apache-mod_php/Dockerfile
  examples/apache-mod_php/README.md
  examples/apache-mod_php/docker-compose.yml
  examples/apache-mod_php/public/index.php
  examples/apache-mod_php/virtual-host.conf
Labels: 📚 docs

#938 Add a separate PHP 5 only file
  bridge/dd_init.php
  bridge/php5.php
  tests/Integration/ResponseStatusCodeTest_files/index.php
  tests/Integration/TracerTest_files/index.php
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: Overhead

#945 Sandbox Lumen on PHP 5
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Lumen/LumenSandboxedIntegration.php
  tests/Integrations/Lumen/V5_2/CommonScenariosSandboxedTest.php
  tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_2/TraceSearchConfigTest.php
  tests/Integrations/Lumen/V5_6/CommonScenariosSandboxedTest.php
  tests/Integrations/Lumen/V5_6/TraceSearchConfigTest.php
  tests/Integrations/Lumen/V5_8/TraceSearchConfigTest.php
Labels: integrations, 📦 Sandbox API

#935 Add startup logging
  .circleci/config.yml
  config.m4
  package.xml
  src/ext/coms.c
  src/ext/coms.h
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/env_config.c
  src/ext/php5/startup_logging.c
  src/ext/php7/startup_logging.c
  src/ext/startup_logging.h
  tests/ext/startup_logging.inc
  tests/ext/startup_logging.phpt
  tests/ext/startup_logging_config.phpt
  tests/ext/startup_logging_diagnostics.phpt
  tests/ext/startup_logging_disabled.phpt
  tests/ext/startup_logging_json.phpt
  tests/ext/startup_logging_json_config.phpt
  tests/ext/startup_logging_skipif.inc
Labels: c-extension, 🏆 enhancement

#941 Warn on dd_trace usage if DD_TRACE_WARN_LEGACY_DD_TRACE
  .circleci/config.yml
  package.xml
  src/ext/configuration.h
  src/ext/ddtrace.c
  tests/ext/access_modifier_method_access_hook.phpt
  tests/ext/access_modifier_property_access_hook.phpt
  tests/ext/allow_overriding_before_overrided_methods_functions_are_defined.phpt
  tests/ext/case_insensitive_class_hook.phpt
  tests/ext/case_insensitive_method_hook.phpt
  tests/ext/closure_accessing_outside_variables.phpt
  tests/ext/closure_set_inside_object_methods.phpt
  tests/ext/dd_trace_api_error.phpt
  tests/ext/dd_trace_can_skip_original_call.phpt
  tests/ext/dd_trace_forward_call_error.phpt
  tests/ext/dd_trace_forward_call_for_functions.phpt
  tests/ext/dd_trace_forward_call_from_include.phpt
  tests/ext/dd_trace_forward_call_with_inheritance.phpt
  tests/ext/dd_trace_forward_call_with_private_callback.phpt
  tests/ext/dd_trace_tracer_is_limited_hard.phpt
  tests/ext/dd_trace_warning.phpt
  tests/ext/destructor_called_when_this_gets_out_of_scope.phpt
  tests/ext/disable_tracing_disables_tracing.phpt
  tests/ext/do_not_check_if_class_or_function_exists_by_default.phpt
  tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/keep_spans_in_limited_tracing_internal_functions.phpt
  tests/ext/keep_spans_in_limited_tracing_internal_methods.phpt
  tests/ext/keep_spans_in_limited_tracing_userland_functions.phpt
  tests/ext/keep_spans_in_limited_tracing_userland_methods.phpt
  tests/ext/method_invoked_via_reflection.phpt
  tests/ext/method_returning_array.phpt
  tests/ext/multiple_instrumentations.phpt
  tests/ext/namespaces.phpt
  tests/ext/new_static.phpt
  tests/ext/overriding_construct.phpt
  tests/ext/overriding_method_defined_in_parent.phpt
  tests/ext/private_method_hook.phpt
  tests/ext/private_self_access.phpt
  tests/ext/protected_method_hook.phpt
  tests/ext/recursion.phpt
  tests/ext/reset_configured_overrides.phpt
  tests/ext/reset_function_tracing.phpt
  tests/ext/return_value_passed.phpt
  tests/ext/sandbox-prehook/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/sandbox/dd_trace_method_works_with_dd_trace.phpt
  tests/ext/simple_function_hook.phpt
  tests/ext/simple_method_hook.phpt
  tests/ext/throw_exception.phpt
  tests/ext/trace_method_or_function_that_will_exist_later.phpt
  tests/ext/trace_static_method.phpt
  tests/ext/used_dispatch_shouldn_t_be_freed.phpt
  tests/ext/variable_length_parameter_list.phpt
  tests/ext/very_nested_functions.phpt
  tests/ext/with_params_function_hook.phpt
  tests/ext/with_params_method_hook.phpt
Labels: 🏆 enhancement

#949 Release 0.47.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: release, ⏩ Version Bump

#950 Add a test for non-zero durations
  package.xml
  tests/ext/sandbox/non-zero_duration.phpt
Labels: dev/testing

#891 Allow defered initialization of integrations, and matching integration to a callable at compiletime
  Makefile
  bridge/_files.php
  config.m4
  dockerfiles/ci/xfail_tests/7.0.list
  package.xml
  src/DDTrace/Integrations/ElasticSearch/V1/loader.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/ext/ddtrace.c
  src/ext/ddtrace_string.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/integrations/elasticsearch.h
  src/ext/integrations/integrations.c
  src/ext/integrations/integrations.h
  src/ext/integrations/test_integration.h
  src/ext/php5/engine_hooks.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/deferred_load_attempt_loading_once.phpt
  tests/ext/sandbox/deferred_load_using_function.phpt
  tests/ext/sandbox/preinitialized_tracing_of_method.phpt
Labels: c-extension, integrations, 🍏 core, 🏆 enhancement

#845 install everything needed for pecl
  package.xml
  src/ext/ddtrace.c
Labels: 🏘 community, 🐛 bug, 🥒 PECL

#954 Fix package.xml validation for PECL
  Makefile
  package.xml
  src/ext/ddtrace.c
  tests/ext/startup_logging.inc
Labels: dev/testing, packaging, 🥒 PECL

#956 Removed obsolete pre-integrations loading check from dd-doctor.php
  examples/apache-mod_php/docker-compose.yml
  examples/apache-mod_php/public/index.php
  examples/nginx-php-fpm/docker-compose.yml
  examples/nginx-php-fpm/public/index.php
  src/dd-doctor.php
Labels: dev/tooling

#955 Remove strict_mode
  package.xml
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/engine_hooks.h
  src/ext/integrations/elasticsearch.h
  src/ext/php5/dispatch.c
  src/ext/php5/engine_hooks.c
  src/ext/php5_4/engine_hooks.c
  src/ext/php7/dispatch.c
  src/ext/php7/engine_hooks.c
  tests/ext/dd_trace_api_error.phpt
  tests/ext/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/sandbox-regression/enable_throw_exception_if_overridable_doesnt_exist.phpt
  tests/ext/sandbox/dd_trace_api_error.phpt
Labels: c-extension

#926 Add DD_TRACE_AGENT_URL environment support
  src/DDTrace/Transport/Http.php
  src/ext/coms.c
  src/ext/configuration.h
Labels: 🏆 enhancement

#962 Consistent env vars: DD_TRACE_AGENT_URL
  phpunit.xml
  src/ext/coms.c
  src/ext/coms.h
  src/ext/php5/startup_logging.c
  src/ext/php7/startup_logging.c
  tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarInvalidTest.php
  tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarTest.php
Labels: c-extension, dev/testing

#967 Deeper instrumentation of Symfony 4.4
  composer.json
  src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
  tests/Frameworks/README.md
  tests/Frameworks/Symfony/.gitignore
  tests/Frameworks/Symfony/Version_4_0/symfony.lock
  tests/Frameworks/Symfony/Version_4_2/symfony.lock
  tests/Frameworks/Symfony/Version_4_4/.env
  tests/Frameworks/Symfony/Version_4_4/.env.test
  tests/Frameworks/Symfony/Version_4_4/.gitattributes
  tests/Frameworks/Symfony/Version_4_4/.gitignore
  tests/Frameworks/Symfony/Version_4_4/bin/console
  tests/Frameworks/Symfony/Version_4_4/bin/phpunit
  tests/Frameworks/Symfony/Version_4_4/composer.json
  tests/Frameworks/Symfony/Version_4_4/config/bootstrap.php
  tests/Frameworks/Symfony/Version_4_4/config/bundles.php
  tests/Frameworks/Symfony/Version_4_4/config/packages/cache.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/dev/debug.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/dev/monolog.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/dev/web_profiler.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/doctrine.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/doctrine_migrations.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/framework.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/mailer.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/prod/deprecations.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/prod/doctrine.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/prod/monolog.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/prod/routing.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/routing.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/security.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/sensio_framework_extra.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/test/framework.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/test/monolog.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/test/twig.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/test/validator.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/test/web_profiler.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/translation.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/twig.yaml
  tests/Frameworks/Symfony/Version_4_4/config/packages/validator.yaml
  tests/Frameworks/Symfony/Version_4_4/config/routes.yaml
  tests/Frameworks/Symfony/Version_4_4/config/routes/annotations.yaml
  tests/Frameworks/Symfony/Version_4_4/config/routes/dev/framework.yaml
  tests/Frameworks/Symfony/Version_4_4/config/routes/dev/web_profiler.yaml
  tests/Frameworks/Symfony/Version_4_4/config/services.yaml
  tests/Frameworks/Symfony/Version_4_4/migrations/.gitignore
  tests/Frameworks/Symfony/Version_4_4/phpunit.xml.dist
  tests/Frameworks/Symfony/Version_4_4/public/index.php
  tests/Frameworks/Symfony/Version_4_4/src/Controller/.gitignore
  tests/Frameworks/Symfony/Version_4_4/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_4_4/src/Entity/.gitignore
  tests/Frameworks/Symfony/Version_4_4/src/Kernel.php
  tests/Frameworks/Symfony/Version_4_4/src/Repository/.gitignore
  tests/Frameworks/Symfony/Version_4_4/templates/base.html.twig
  tests/Frameworks/Symfony/Version_4_4/templates/twig_template.html.twig
  tests/Frameworks/Symfony/Version_4_4/tests/bootstrap.php
  tests/Frameworks/Symfony/Version_4_4/translations/.gitignore
  tests/Integrations/Symfony/V4_4/CommonScenariosSandboxedTest.php
  tests/Integrations/Symfony/V4_4/TraceSearchConfigSandboxedTest.php
Labels: integrations

#971 Add PHP-FPM test runner to web tests
  .circleci/config.yml
  .gitignore
  tests/Common/SpanChecker.php
  tests/Common/TracerTestTrait.php
  tests/Common/WebFrameworkTestCase.php
  tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarInvalidTest.php
  tests/Integrations/Custom/Autoloaded/AgentUrlEnvVarTest.php
  tests/Integrations/Custom/Autoloaded/BackgroundSenderLogTest.php
  tests/Integrations/Custom/Autoloaded/CircuitBreakerTest.php
  tests/Integrations/Custom/Autoloaded/CommonScenariosTest.php
  tests/Integrations/Custom/Autoloaded/CompileTimeDisabledTest.php
  tests/Integrations/Custom/Autoloaded/CompileTimeEnabledTest.php
  tests/Integrations/Custom/Autoloaded/TraceSearchConfigTest.php
  tests/Nginx/NginxServer.php
  tests/Nginx/nginx-default.conf
  tests/Sapi/CliServer/CliServer.php
  tests/Sapi/PhpCgi/PhpCgi.php
  tests/Sapi/PhpFpm/PhpFpm.php
  tests/Sapi/PhpFpm/www.conf
  tests/Sapi/Sapi.php
  tests/WebServer.php
Labels: dev/testing

#973 Remove query string when new resource mapper is used
  src/private/functions.php
  tests/Unit/private/UriTest.php
  tests/overhead/docker-compose.yml
Labels: 🐛 bug

#963 Consistent env vars: Fix propagation of DD_ENV and DD_VERSION to children spans
  src/DDTrace/Tracer.php
  tests/Integration/TracerTest.php
Labels: 🐛 bug

#961 Move startup logging to first RINIT
  .gitignore
  dockerfiles/ci/xfail_tests/7.3.list
  dockerfiles/ci/xfail_tests/7.4.list
  src/ext/ddtrace.c
  src/ext/php5/startup_logging.c
  src/ext/php7/startup_logging.c
  src/ext/startup_logging.h
  tests/Integrations/Custom/Autoloaded/StartupLoggingDiagnosticsDisabledTest.php
  tests/Integrations/Custom/Autoloaded/StartupLoggingDiagnosticsTest.php
  tests/Integrations/Custom/Autoloaded/StartupLoggingDisabledTest.php
  tests/Integrations/Custom/Autoloaded/StartupLoggingTest.php
  tests/Sapi/PhpFpm/PhpFpm.php
  tests/ext/startup_logging.phpt
  tests/ext/startup_logging_diagnostics.phpt
Labels: 🐛 bug

#975 Speedup build of test/overhead images and move all configs to own folder
  docker-compose.yml
  tests/overhead/Makefile
  tests/overhead/dockerfiles/Dockerfile_73_fpm_base
  tests/overhead/dockerfiles/composer-installer.php
Labels: dev/tooling

#969 Consistent env vars: Support for DD_TRACE_<INTEGRATION>_<SUFFIX> env vars
  bridge/configuration.php
  src/DDTrace/Integrations/DefaultIntegrationConfiguration.php
  src/api/Configuration.php
  src/ext/configuration.c
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/env_config.c
  src/ext/env_config.h
  src/ext/integrations/elasticsearch.h
  src/ext/integrations/integrations.c
  src/ext/integrations/integrations.h
  src/ext/php5/startup_logging.c
  src/ext/php7/startup_logging.c
  tests/Unit/ConfigurationTest.php
  tests/Unit/Integrations/DefaultIntegrationConfigurationTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/ext/startup_logging_diagnostics.phpt
Labels: 🏆 enhancement

#976 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev/tooling

#979 Update Jessie package verification
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/debian_jessie/Dockerfile
Labels: ci
