Repository DataDog/dd-trace-php, pull requests merged in 2020-06, with the labels that each got.

#909 Bump version to 0.46.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: release, ⏩ Version Bump, 💔 breaking-change

#910 Update package.xml for recent changes to tracer for PHP 5.4
  package.xml
Labels: 🐛 bug, 🥒 PECL

#911 Sandbox cURL (PHP 5)
  .circleci/config.yml
  bridge/dd_init.php
  config.m4
  docker-compose.yml
  package.xml
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/distributed_tracing.h
  src/ext/php5/distributed_tracing.c
  src/ext/php5/engine_api.c
  src/ext/php5/engine_api.h
  src/ext/php5/handlers_curl.c
  src/ext/php5/handlers_internal.c
  src/ext/php5_4/distributed_tracing.c
  src/ext/php7/distributed_tracing.c
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/ext/sandbox/distributed_tracing.inc
  tests/ext/sandbox/distributed_tracing_curl.phpt
  tests/ext/sandbox/distributed_tracing_curl_copy_handle.phpt
  tests/ext/sandbox/distributed_tracing_curl_existing_headers_001.phpt
  tests/ext/sandbox/distributed_tracing_curl_existing_headers_002.phpt
  tests/ext/sandbox/distributed_tracing_curl_inject.inc
  tests/ext/sandbox/distributed_tracing_curl_inject_exception.inc
  tests/ext/sandbox/distributed_tracing_curl_sandboxed.phpt
Labels: c-extension, 📦 Sandbox API

#917 Fix issues from recent PHPStan updates
  phpstan.ddtrace.neon
Labels: dev/tooling

#921 Enable OpenTracing test suite in CI
  composer.json
  tests/OpenTracerUnit/GlobalTracerTest.php
Labels: dev/testing

#919 Add support for service name configuration via DD_SERVICE
  src/ext/configuration.c
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/env_config.c
  src/ext/env_config.h
  tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
  tests/Integrations/CLI/Custom/Autoloaded/CommonScenariosTest.php
  tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php
  tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_6/CommonScenariosSandboxedTest.php
  tests/Integrations/Lumen/V5_6/CommonScenariosTest.php
  tests/Integrations/Lumen/V5_8/CommonScenariosTest.php
  tests/Integrations/Slim/V3_12/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_2/CommonScenariosTest.php
  tests/Integrations/WordPress/V4_8/CommonScenariosTest.php
  tests/Integrations/Yii/V2_0_26/CommonScenariosTest.php
  tests/Integrations/Yii/V2_0_26/ParameterizedRouteTest.php
  tests/Unit/ConfigurationTest.php
Labels: c-extension

#920 Add support for DD_TAGS, fallback to DD_TRACE_GLOBAL_TAGS
  bridge/configuration.php
  src/api/Configuration.php
  tests/Integration/TracerTest.php
  tests/Integrations/Laravel/V4/CommonScenariosSandboxedTest.php
  tests/Integrations/Laravel/V4/CommonScenariosTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/TracerTest.php
Labels: 🏆 enhancement

#925 Separate serializer.c into PHP version directories
  config.m4
  package.xml
  src/ext/php5/serializer.c
  src/ext/php5_4/serializer.c
  src/ext/php7/serializer.c
  tests/ext/sandbox/memory_limit_graceful_bailout.phpt
Labels: c-extension, 📦 Sandbox API

#923 Defaults for name and resource on SpanData
  dockerfiles/ci/xfail_tests/5.4.list
  dockerfiles/ci/xfail_tests/5.6.list
  dockerfiles/ci/xfail_tests/7.0.list
  dockerfiles/ci/xfail_tests/7.1.list
  dockerfiles/ci/xfail_tests/7.2.list
  dockerfiles/ci/xfail_tests/7.3.list
  dockerfiles/ci/xfail_tests/7.4.list
  package.xml
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/php5/engine_hooks.c
  src/ext/php5/serializer.c
  src/ext/php7/engine_hooks.c
  src/ext/php7/serializer.c
  tests/ext/sandbox-prehook/dd_trace_method.phpt
  tests/ext/sandbox/auto_flush.phpt
  tests/ext/sandbox/auto_flush_attach_exception.phpt
  tests/ext/sandbox/auto_flush_disables_tracing.phpt
  tests/ext/sandbox/dd_dumper.inc
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_function_internal.phpt
  tests/ext/sandbox/dd_trace_function_userland.phpt
  tests/ext/sandbox/dd_trace_method.phpt
  tests/ext/sandbox/default_span_properties.phpt
  tests/ext/sandbox/default_span_properties_method.phpt
  tests/ext/sandbox/errors_are_flagged_from_userland.phpt
  tests/ext/sandbox/exception_handled_for_correct_catch_block.phpt
  tests/ext/sandbox/exception_handled_in_correct_catch_frame.phpt
  tests/ext/sandbox/exception_handled_in_multicatch.phpt
  tests/ext/sandbox/exception_handled_with_finally.phpt
  tests/ext/sandbox/safe_to_string_properties.phpt
Labels: c-extension, 🍏 core, 🏆 enhancement, 📦 Sandbox API

#929 Only build on 64-bit platforms
  config.m4
Labels: c-extension, 🐛 bug

#928 Apply new uri to resource normalization rules
  bridge/_files.php
  bridge/configuration.php
  src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
  src/DDTrace/Integrations/WordPress/V4/WordPressIntegrationLoader.php
  src/DDTrace/Tracer.php
  src/private/README.md
  src/private/functions.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/private/UriTest.php
Labels: 🏆 enhancement

#932 Refactor dispatch.{c,h}
  config.m4
  package.xml
  src/ext/dispatch.c
  src/ext/dispatch.h
  src/ext/dispatch_setup.c
  src/ext/php5/dispatch.c
  src/ext/php5_4/dispatch.c
  src/ext/php7/dispatch.c
  src/ext/php7/engine_hooks.c
Labels: c-extension
