Repository DataDog/dd-trace-php, pull requests merged in 2020-05, with the labels that each got.

#867 Simplify spl_autoload_register instrumentation
  bridge/functions.php
Labels: 🏆 enhancement

#870 Add ddtrace_config_distributed_tracing_enabled
  src/DDTrace/Configuration.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/StartSpanOptionsFactory.php
  src/ext/configuration.c
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/ddtrace_string.h
  src/ext/php7/handlers_curl.c
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/StartSpanOptionsFactoryTest.php
Labels: c-extension, 🍏 core, 🏆 enhancement

#852 Refactor module blacklist
  .circleci/config.yml
  composer.json
  config.m4
  package.xml
  src/ext/blacklist.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/php5/blacklist.c
  src/ext/php7/blacklist.c
  src/ext/request_hooks.c
  src/ext/request_hooks.h
  tests/ext/request-init-hook/request_init_hook_check_blacklisted_modules.phpt
  tests/ext/request-init-hook/run_file_before_request_handling.phpt
  tests/xdebug/2.7.2/request_init_hook_disable_php_7.0.phpt
  tests/xdebug/2.9.2/request_init_hook_disable.phpt
  tests/xdebug/2.9.5/request_init_hook.phpt
  tests/xdebug/fake_request_init_hook.inc
Labels: c-extension, 🏆 enhancement

#833 Optimize Configuration
  bridge/_files.php
  bridge/autoload.php
  bridge/configuration.php
  phpstan.neon
  src/DDTrace/Configuration.php
  src/DDTrace/Integrations/AbstractIntegrationConfiguration.php
  src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
  src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterSandboxedIntegration.php
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
  src/DDTrace/Integrations/DefaultIntegrationConfiguration.php
  src/DDTrace/Integrations/Eloquent/EloquentSandboxedIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
  src/DDTrace/Integrations/Integration.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Slim/SlimIntegration.php
  src/DDTrace/Integrations/Symfony/SymfonySandboxedIntegration.php
  src/DDTrace/Integrations/WordPress/V4/WordPressIntegrationLoader.php
  src/DDTrace/Integrations/Yii/V2/YiiIntegrationLoader.php
  src/DDTrace/Integrations/ZendFramework/ZendFrameworkSandboxedIntegration.php
  src/DDTrace/Log/Logger.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/Sampling/ConfigurableSampler.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/composer.json
  tests/Frameworks/Symfony/Version_3_4/composer.json
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Integrations/AbstractIntegrationConfigurationTest.php
  tests/Unit/Sampling/ConfigurableSamplerTest.php
  tests/Unit/TracerTest.php
  tests/bootstrap_utils.php
Labels: c-extension, integrations, 🍏 core, 🏆 enhancement

#869 Use normalized URL as the resource name for curl
  src/DDTrace/Integrations/Curl/CurlIntegration.php
  src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
  tests/Integrations/CLI/Custom/Autoloaded/NoRootSpanTest.php
  tests/Integrations/Curl/CurlIntegrationTest.php
Labels: 🏆 enhancement, 🏘 community

#872 Fix variadic args with empty function signature
  package.xml
  src/ext/php5/handlers_curl.c
  src/ext/php7/engine_hooks.c
  tests/ext/sandbox/variadic_no_args.phpt
Labels: c-extension, 🐛 bug, 📦 Sandbox API

#874 Fix character handling in request init hook
  package.xml
  src/ext/request_hooks.c
  tests/ext/request-init-hook/contains_binary_character.php
  tests/ext/request-init-hook/request_init_hook_contains_non_printable_character.phpt
Labels: c-extension, 🐛 bug

#841 Bump phpstan to 0.12 and fix issues
  .circleci/config.yml
  phpstan.neon
  src/DDTrace/Configuration/AbstractConfiguration.php
  src/DDTrace/NoopScopeManager.php
  src/DDTrace/NoopTracer.php
Labels: dev/testing, dev/tooling

#875 Sandbox header and http_response_code
  src/DDTrace/Bootstrap.php
Labels: 🏆 enhancement, 📦 Sandbox API

#876 Bump version to 0.45.0
  package.xml
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/version.h
Labels: release, ⏩ Version Bump

#878 Move Slim to Sandboxed API
  bridge/_files.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Slim/SlimSandboxedIntegration.php
  tests/Integrations/Slim/V3_12/CommonScenariosSandboxedTest.php
  tests/Integrations/Slim/V3_12/CommonScenariosTest.php
Labels: integrations, 📦 Sandbox API

#881 Run sandboxed and legacy integration tests in isolated processes
  composer.json
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchSandboxedIntegrationTest.php
Labels: ci, dev/testing

#885 Prevent curl and guzzle from inheriting top level app name
  src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
  tests/Common/SpanChecker.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Curl/curl_in_web_request.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V5/guzzle_in_web_request.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/guzzle_in_web_request.php
Labels: 🐛 bug

#886 Change PDO service name to lowercase
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php
  tests/Integrations/PDO/PDOSandboxedTest.php
  tests/Integrations/PDO/PDOTest.php
Labels: 🐛 bug

#882 Fix uncaught exceptions with auto flushing enabled
  package.xml
  src/ext/php7/auto_flush.c
  tests/ext/sandbox/auto_flush.phpt
  tests/ext/sandbox/auto_flush_attach_exception.phpt
  tests/ext/sandbox/auto_flush_disables_tracing.phpt
  tests/ext/sandbox/auto_flush_sandbox_exception.phpt
  tests/ext/sandbox/auto_flush_userland_root_span.phpt
  tests/ext/sandbox/fake_global_tracer.inc
  tests/ext/sandbox/fake_tracer.inc
  tests/ext/sandbox/fake_tracer_exception.inc
Labels: c-extension, 🐛 bug, 📦 Sandbox API

#887 Bump version to 0.45.1
  package.xml
  src/DDTrace/Integrations/Curl/CurlSandboxedIntegration.php
  src/DDTrace/Integrations/Guzzle/GuzzleSandboxedIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Integrations/PDO/PDOSandboxedIntegration.php
  src/DDTrace/Tracer.php
  src/DDTrace/version.php
  src/ext/php7/auto_flush.c
  src/ext/version.h
  tests/Common/SpanChecker.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Curl/curl_in_web_request.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V5/guzzle_in_web_request.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/guzzle_in_web_request.php
  tests/Integrations/PDO/PDOSandboxedTest.php
  tests/Integrations/PDO/PDOTest.php
  tests/ext/sandbox/auto_flush.phpt
  tests/ext/sandbox/auto_flush_attach_exception.phpt
  tests/ext/sandbox/auto_flush_disables_tracing.phpt
  tests/ext/sandbox/auto_flush_sandbox_exception.phpt
  tests/ext/sandbox/auto_flush_userland_root_span.phpt
  tests/ext/sandbox/fake_global_tracer.inc
  tests/ext/sandbox/fake_tracer.inc
  tests/ext/sandbox/fake_tracer_exception.inc
Labels: ⏩ Version Bump

#889 Be compatible with psr4 composer autoloading now that we have non-psr4 config functions
  bridge/functions.php
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/AutoInstrumentation/scenarios/composer_with_local_code_dependency/composer.json
Labels: 🐛 bug

#892 Make minor robustness tweaks to the tests
  tests/ext/includes/sanity_check.php
  tests/ext/request-init-hook/contains_binary_character.php
  tests/ext/request-init-hook/raises_fatal_error.php
  tests/ext/request-init-hook/throws_exception.php
  tests/ext/sandbox/memory_limit_graceful_bailout.phpt
Labels: dev/testing

#896 fix opcache check in dd-doctor
  src/dd-doctor.php
Labels: 🐛 bug

#898 Sandbox the CakePHP integration
  bridge/_files.php
  composer.json
  src/DDTrace/Integrations/CakePHP/CakePHPIntegration.php
  src/DDTrace/Integrations/CakePHP/CakePHPSandboxedIntegration.php
  src/DDTrace/Integrations/CakePHP/V2/CakePHPIntegrationLoader.php
  src/DDTrace/Integrations/IntegrationsLoader.php
  tests/Integrations/CLI/CLITestCase.php
  tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosSandboxedTest.php
  tests/Integrations/CLI/CakePHP/V2_8/CommonScenariosTest.php
  tests/Integrations/CakePHP/V2_8/CommonScenariosSandboxedTest.php
  tests/Integrations/CakePHP/V2_8/CommonScenariosTest.php
Labels: integrations, 📦 Sandbox API

#899 Remove legacy hook for OpenTracing
  docs/open_tracing.md
  src/DDTrace/Bootstrap.php
Labels: 🍏 core, 💔 breaking-change

#900 Noop the legacy API when a potentially conflicting module detected
  src/ext/blacklist.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/php5/blacklist.c
  src/ext/php7/blacklist.c
Labels: c-extension, 🏆 enhancement

#905 Move setting that ignores legacy blacklist to env var
  src/ext/configuration.h
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/php5_4/blacklist.c
Labels: c-extension

#907 Move the request init hook to auto_prepend_file
  .circleci/config.yml
  .circleci/valgrind/valgrind_musl_suppressions.lib
  Makefile
  bridge/dd_wrap_autoloader.php
  dockerfiles/ci/xfail_tests/5.4.list
  package.xml
  package/post-install.sh
  src/ext/ddtrace.c
  src/ext/ddtrace.h
  src/ext/request_hooks.c
  src/ext/request_hooks.h
  tests/AutoInstrumentation/AutoInstrumentationTest.php
  tests/Common/WebFrameworkTestCase.php
  tests/Composer/ComposerInteroperabilityTest.php
  tests/DistributedTracing/SandboxAndLegacyTest.php
  tests/Frameworks/Symfony/Version_3_0/web/index.php
  tests/Frameworks/Symfony/Version_3_3/web/index.php
  tests/Frameworks/Symfony/Version_3_4/web/index.php
  tests/Integrations/CLI/CLITestCase.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Integrations/Symfony/V2_3/RouteNameTest.php
  tests/Integrations/Symfony/V2_8/RouteNameTest.php
  tests/Integrations/Symfony/V3_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_0/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_3/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_3/TraceSearchConfigTest.php
  tests/Integrations/Symfony/V3_4/AutofinishedTracesSymfony34Test.php
  tests/Integrations/Symfony/V3_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V3_4/TemplateEnginesTest.php
  tests/Integrations/Symfony/V3_4/TraceSearchConfigTest.php
  tests/Metrics/SigSegV/SigSegVTest.php
  tests/WebServer.php
  tests/ext/includes/dd_init.php
  tests/ext/includes/request_init_hook.inc
  tests/ext/request-init-hook/auto_prepend_file.inc
  tests/ext/request-init-hook/auto_prepend_file_none.phpt
  tests/ext/request-init-hook/auto_prepend_file_once.phpt
  tests/ext/request-init-hook/auto_prepend_file_original.phpt
  tests/ext/request-init-hook/auto_prepend_file_original_disabled.phpt
  tests/ext/request-init-hook/auto_prepend_file_original_disabled_ini.phpt
  tests/ext/request-init-hook/contains-binary-character/dd_init.php
  tests/ext/request-init-hook/contains_binary_character.php
  tests/ext/request-init-hook/dd_init_open_basedir.inc
  tests/ext/request-init-hook/dd_init_open_basedir.phpt
  tests/ext/request-init-hook/raises-e-notice/dd_init.php
  tests/ext/request-init-hook/raises-fatal-error/dd_init.php
  tests/ext/request-init-hook/raises_e_notice.php
  tests/ext/request-init-hook/raises_fatal_error.php
  tests/ext/request-init-hook/request_init_hook_confined_to_open_basedir.phpt
  tests/ext/request-init-hook/request_init_hook_file_not_found.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors.phpt
  tests/ext/request-init-hook/request_init_hook_ignores_fatal_errors_php_54.phpt
  tests/ext/request-init-hook/shebang.phpt
  tests/ext/request-init-hook/throws-exception/dd_init.php
  tests/ext/request-init-hook/throws_exception.php
  tests/overhead/dockerfiles/Dockerfile_73_fpm_head
  tests/overhead/dockerfiles/Dockerfile_73_fpm_master
Labels: c-extension, 🍏 core
