Repository DataDog/dd-trace-php, pull requests merged in 2021-04, with the labels that each got.

#1192 Exclude dockerfiles directory from the composer package
  .gitattributes
Labels: 🏆 enhancement

#1193 Accept multiple requests dumped from request-replayer
  tests/Common/AgentReplayerTrait.php
  tests/Common/TracerTestTrait.php
  tests/Integration/Transport/HttpTest.php
  tests/ext/includes/request_replayer.inc
Labels: dev/testing

#1190 Container tagging for AWS Fargate 1.4+
  components/container_id/container_id.c
  components/container_id/container_id.h
  components/container_id/tests/CMakeLists.txt
  components/container_id/tests/container_id.cc
  components/container_id/tests/container_id_from_file.cc
  components/container_id/tests/container_id_parser.cc
  components/container_id/tests/stubs/cgroup.invalid_line_container_id
  components/container_id/tests/stubs/cgroup.invalid_line_task_id
  components/container_id/tests/stubs/cgroup.upper
  components/container_id/tests/stubs/cgroup.whitespace
  ext/php5/ddshared.c
  ext/php7/ddshared.c
  ext/php8/ddshared.c
  package.xml
  tests/ext/background-sender/agent_headers_container_id_fargate.phpt
  tests/ext/background-sender/stubs/cgroup.fargate.1.4
Labels: c-extension, 🏆 enhancement

#1197 Disable php language tests `ext/openssl/tests/bug54992.phpt`
  dockerfiles/ci/xfail_tests/5.4.list
  dockerfiles/ci/xfail_tests/5.5.list
  dockerfiles/ci/xfail_tests/README.md
Labels: dev/testing

#1198 handle laravel 7+ generated:: prefix for unnamed routes
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  tests/Frameworks/Laravel/Version_8_x/app/Http/Controllers/RouteCachingController.php
  tests/Frameworks/Laravel/Version_8_x/routes/web.php
  tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
  tests/Integrations/Laravel/V8_x/CommonScenariosTest.php
  tests/Integrations/Laravel/V8_x/RouteCachingTest.php
Labels: 🐛 bug

#1203 Remove PHP version prefix from buster development containers
  .circleci/config.yml
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/php-5.4/Dockerfile
  dockerfiles/ci/buster/php-5.4/welcome
  dockerfiles/ci/buster/php-5.5/Dockerfile
  dockerfiles/ci/buster/php-5.5/welcome
  dockerfiles/ci/buster/php-5.6/Dockerfile
  dockerfiles/ci/buster/php-5.6/welcome
  dockerfiles/ci/buster/php-7.0/Dockerfile
  dockerfiles/ci/buster/php-7.0/welcome
  dockerfiles/ci/buster/php-7.1/Dockerfile
  dockerfiles/ci/buster/php-7.1/welcome
  dockerfiles/ci/buster/php-7.2/Dockerfile
  dockerfiles/ci/buster/php-7.2/welcome
  dockerfiles/ci/buster/php-7.3/Dockerfile
  dockerfiles/ci/buster/php-7.3/welcome
  dockerfiles/ci/buster/php-7.4/Dockerfile
  dockerfiles/ci/buster/php-7.4/welcome
  dockerfiles/ci/buster/php-8.0/Dockerfile
  dockerfiles/ci/buster/php-8.0/Dockerfile_shared_ext
  dockerfiles/ci/buster/php-8.0/welcome
Labels: dev/testing

#1205 Release 0.57.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release, ⏩ Version Bump

#1206 Add a Kubernetes example to container tagging tests
  components/container_id/tests/container_id_parser.cc
Labels: dev/testing

#1204 ZAI SAPI
  .circleci/config.yml
  Makefile
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/catch2_main.cc
  zend_abstract_interface/zai_sapi/CMakeLists.txt
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/tests/CMakeLists.txt
  zend_abstract_interface/zai_sapi/tests/zai_sapi_ini.cc
  zend_abstract_interface/zai_sapi/tests/zai_sapi_io.cc
  zend_abstract_interface/zai_sapi/zai_sapi.h
  zend_abstract_interface/zai_sapi/zai_sapi_ini.c
  zend_abstract_interface/zai_sapi/zai_sapi_ini.h
  zend_abstract_interface/zai_sapi/zai_sapi_io.c
  zend_abstract_interface/zai_sapi/zai_sapi_io.h
Labels: dev/testing, 🏆 enhancement

#1208 [ZAI SAPI] Add test helpers
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/tests/CMakeLists.txt
  zend_abstract_interface/zai_sapi/tests/stubs/basic.php
  zend_abstract_interface/zai_sapi/tests/zai_sapi.cc
  zend_abstract_interface/zai_sapi/zai_sapi.h
Labels: dev/testing, 🏆 enhancement

#1212 [ZAI SAPI] Zai\trigger_error() SAPI function
  .circleci/config.yml
  .phpcs.xml
  config.m4
  package.xml
  zend_abstract_interface/zai_sapi/CMakeLists.txt
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/tests/CMakeLists.txt
  zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_CORE_ERROR.php
  zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_ERROR.php
  zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_NOTICE.php
  zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_E_WARNING.php
  zend_abstract_interface/zai_sapi/tests/stubs/trigger_error_invalid.php
  zend_abstract_interface/zai_sapi/tests/zai_sapi_functions.cc
  zend_abstract_interface/zai_sapi/zai_sapi.h
  zend_abstract_interface/zai_sapi/zai_sapi_functions.c
  zend_abstract_interface/zai_sapi/zai_sapi_functions.h
Labels: dev/testing, 🏆 enhancement

#1216 Tidy the components/
  components/container_id/container_id.c
  components/container_id/container_id.h
  components/container_id/tests/container_id_from_file.cc
  components/sapi/sapi.c
  components/sapi/tests/sapi.cc
Labels: c-extension

#1210 Use new buster containers in CI
  .circleci/config.yml
  .circleci/php-5.5_web.txt
  Makefile
  docker-compose.yml
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/install-ext-from-source
  dockerfiles/ci/buster/php-5.4/Dockerfile
  dockerfiles/ci/buster/php-5.4/configure.sh
  dockerfiles/ci/buster/php-5.5/Dockerfile
  dockerfiles/ci/buster/php-5.5/configure.sh
  dockerfiles/ci/buster/php-5.6/Dockerfile
  dockerfiles/ci/buster/php-5.6/configure.sh
  dockerfiles/ci/buster/php-7.0/Dockerfile
  dockerfiles/ci/buster/php-7.0/configure.sh
  dockerfiles/ci/buster/php-7.1/Dockerfile
  dockerfiles/ci/buster/php-7.2/Dockerfile
  dockerfiles/ci/buster/php-7.3/Dockerfile
  dockerfiles/ci/buster/php-7.4/Dockerfile
  dockerfiles/ci/buster/php-8.0/Dockerfile
  dockerfiles/ci/xfail_tests/5.4.list
  dockerfiles/ci/xfail_tests/5.5.list
  dockerfiles/ci/xfail_tests/5.6.list
  dockerfiles/ci/xfail_tests/7.0.list
  dockerfiles/ci/xfail_tests/7.1.list
  dockerfiles/ci/xfail_tests/7.2.list
  dockerfiles/ci/xfail_tests/7.3.list
  dockerfiles/ci/xfail_tests/7.4.list
  dockerfiles/ci/xfail_tests/8.0.list
  dockerfiles/ci/xfail_tests/README.md
  tests/Integrations/WordPress/V5_5/CommonScenariosTest.php
Labels: ci

#1217 remove _tmp suffix from development buster images
  docker-compose.yml
Labels: dev/testing

#1215 Skip tests that have development environment dependencies
  .circleci/config.yml
  package.xml
  tests/ext/background-sender/agent_headers.phpt
  tests/ext/background-sender/agent_headers_container_id.phpt
  tests/ext/background-sender/agent_headers_container_id_empty.phpt
  tests/ext/background-sender/agent_headers_container_id_fargate.phpt
  tests/ext/background-sender/agent_headers_ignore_userland.phpt
  tests/ext/includes/skipif_no_dev_env.inc
Labels: dev/testing, 🐛 bug

#1222 Fix ingestion control reporting
  bridge/configuration.php
  src/DDTrace/Sampling/ConfigurableSampler.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Sampling/ConfigurableSamplerTest.php
Labels: 🐛 bug
