Repository DataDog/dd-trace-php, pull requests merged in 2021-02, with the labels that each got.

#1137 Add support for redis cluster
  .circleci/config.yml
  .phpcs.xml
  Makefile
  dockerfiles/services/redis/Dockerfile
  dockerfiles/services/redis/app_start.sh
  dockerfiles/services/redis/conf_template.conf
  dockerfiles/services/redis/conf_template_cluster.conf
  dockerfiles/services/redis/prepare-server.sh
  ext/php5/integrations/integrations.c
  ext/php7/handlers_phpredis.c
  ext/php7/integrations/integrations.c
  ext/php8/handlers_phpredis.c
  ext/php8/integrations/integrations.c
  src/DDTrace/Integrations/PHPRedis/PHPRedisIntegration.php
  tests/Integrations/PHPRedis/V3/PHPRedisClusterTest.php
  tests/Integrations/PHPRedis/V3/PHPRedisTest.php
  tests/Integrations/PHPRedis/V4/PHPRedisClusterTest.php
  tests/Integrations/PHPRedis/V4/PHPRedisTest.php
  tests/Integrations/PHPRedis/V5/PHPRedisClusterTest.php
  tests/Integrations/PHPRedis/V5/PHPRedisTest.php
Labels: integrations

#1141 fix clang-format installation after circleci image update to buster
  .circleci/config.yml
Labels: dev/tooling

#1140 Release version 0.55.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release, ⏩ Version Bump

#1069 update links in README.md to configuration and OT docs
  README.md
Labels: 📚 docs

#1144 add missing dependency on curl extension for PHP 8
  ext/php8/ddtrace.c
Labels: 🐛 bug

#1147 Fix linting + xfail a flaky test
  dockerfiles/ci/xfail_tests/5.6.list
  ext/php8/ddtrace.c
Labels: ci

#1149 Comment to long running example for method instead of function as the repetitive hook
  examples/long-running/long-running-script.php
Labels: cat:usability

#1131 Add randomized testing to test hundreds of different scenarios
  .circleci/config.yml
  .gitignore
  .phpcs.xml
  tests/Frameworks/Slim/Version_4/README.md
  tests/randomized/.gitignore
  tests/randomized/Makefile
  tests/randomized/README.md
  tests/randomized/analyze-results.php
  tests/randomized/app/.gitignore
  tests/randomized/app/composer-5.4.json
  tests/randomized/app/composer-5.5.json
  tests/randomized/app/composer-5.6.json
  tests/randomized/app/composer-7.0.json
  tests/randomized/app/composer-7.1.json
  tests/randomized/app/composer-7.2.json
  tests/randomized/app/composer-7.3.json
  tests/randomized/app/composer-7.4.json
  tests/randomized/app/composer-8.0.json
  tests/randomized/app/public/index.php
  tests/randomized/app/src/RandomizedTests/GeneratorSnippets.php
  tests/randomized/app/src/RandomizedTests/RandomExecutionPath.php
  tests/randomized/app/src/RandomizedTests/Snippets.php
  tests/randomized/app/src/RandomizedTests/Utils.php
  tests/randomized/config/envs.php
  tests/randomized/config/inis.php
  tests/randomized/config/platforms.php
  tests/randomized/docker/Dockerfile
  tests/randomized/docker/enable-coredump.sh
  tests/randomized/docker/nginx.conf
  tests/randomized/docker/nginx.site.conf
  tests/randomized/docker/prepare.sh
  tests/randomized/docker/run.sh
  tests/randomized/generate-scenarios.php
  tests/randomized/lib/ApacheConfigGenerator.php
  tests/randomized/lib/DockerComposeFileGenerator.php
  tests/randomized/lib/MakefileGenerator.php
  tests/randomized/lib/PhpFpmConfigGenerator.php
  tests/randomized/lib/RequestTargetsGenerator.php
  tests/randomized/lib/Utils.php
  tests/randomized/lib/templates/Makefile.template
  tests/randomized/lib/templates/apache.template.conf
  tests/randomized/lib/templates/docker-compose.service.template.yml
  tests/randomized/lib/templates/docker-compose.template.yml
  tests/randomized/lib/templates/php-fpm.template.conf
Labels: dev/testing

#1154 Add configured http headers to root span
  .phpcs.xml
  bridge/configuration.php
  src/DDTrace/Bootstrap.php
  src/private/functions.php
  tests/Frameworks/Custom/Version_Not_Autoloaded/Headers/index.php
  tests/Integrations/Custom/NotAutoloaded/HttpHeadersConfiguredTest.php
  tests/Integrations/Custom/NotAutoloaded/HttpHeadersNotConfiguredTest.php
  tests/Unit/ConfigurationTest.php
Labels: 🏆 enhancement

#1159 Fix initialization of curl_multi_init() for distributed tracing
  ext/php5/handlers_curl.c
  ext/php7/handlers_curl.c
  package.xml
  tests/ext/sandbox/distributed_tracing_curl_multi_exec_001.phpt
  tests/ext/sandbox/distributed_tracing_curl_multi_exec_002.phpt
Labels: 🐛 bug
