Repository DataDog/dd-trace-php, pull requests merged in 2021-07, with the labels that each got.

#1278 Add ext/ffi to PHP builds
  dockerfiles/ci/alpine/docker-compose.yml
  dockerfiles/ci/alpine/php-8.0/configure.sh
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/buster/php-7.4/configure.sh
  dockerfiles/ci/buster/php-8.0/configure.sh
  dockerfiles/ci/buster/php-8.0/configure_shared_ext.sh
  dockerfiles/ci/buster/php-master/install-php-master
  dockerfiles/ci/centos/6/CentOS-Base.repo
  dockerfiles/ci/centos/6/CentOS-SCLo-scl-rh.repo
  dockerfiles/ci/centos/6/CentOS-SCLo-scl.repo
  dockerfiles/ci/centos/6/Dockerfile
  dockerfiles/ci/centos/6/Dockerfile_php5
  dockerfiles/ci/centos/6/Dockerfile_php7
  dockerfiles/ci/centos/6/Dockerfile_php8
  dockerfiles/ci/centos/6/docker-compose.yml
  dockerfiles/ci/centos/6/php-7.4/configure.sh
  dockerfiles/ci/centos/6/php-8.0/configure.sh
  dockerfiles/ci/xfail_tests/7.4.list
  dockerfiles/ci/xfail_tests/8.0.list
  dockerfiles/ci/xfail_tests/README.md
  dockerfiles/compile_extension/docker-compose.yml
  dockerfiles/compile_extension/install-php
Labels: cat:devtools

#1276 Set SECBIT_NO_SETUID_FIXUP to prevent crashes after setuid() calls
  config.m4
  ext/php5/coms.c
  ext/php5/configuration.h
  ext/php7/coms.c
  ext/php7/configuration.h
  ext/php8/coms.c
  ext/php8/configuration.h
  package.xml
  tests/ext/background-sender/background_sender_survives_setuid.phpt
Labels: c-extension, sev-1, 🐛 bug

#1281 Register SpanData->exception property and store exception info there instead of internally
  ext/php8/compatibility.h
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/engine_hooks.h
  ext/php8/handlers_exception.c
  ext/php8/php8/engine_hooks.c
  ext/php8/serializer.c
  ext/php8/serializer.h
  ext/php8/span.h
  package.xml
  tests/ext/sandbox/deferred_load_missing_load_fn.phpt
  tests/ext/span_with_removed_exception.phpt
Labels: c-extension, 🏆 enhancement

#1279 Apply original curl headers when curl_setopt_array() fails
  .circleci/config.yml
  Makefile
  dockerfiles/ci/buster/php-8.0/Dockerfile_shared_ext
  ext/php5/handlers_curl.c
  ext/php7/handlers_curl.c
  ext/php8/handlers_curl.c
  package.xml
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_003.phpt
Labels: c-extension, 🐛 bug

#1280 Fix owner of files included in the distributed .tar.gz archive
  .circleci/config.yml
  Makefile
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/docker-compose.yml
  dockerfiles/verify_packages/tar_gz/install.sh
  dockerfiles/verify_packages/verify_tar_gz_root.sh
Labels: cat:installation

#1283 Use exceptions ZAI for PHP 7 as well
  config.m4
  ext/php7/engine_hooks.c
  ext/php7/engine_hooks.h
  ext/php7/php7/engine_hooks.c
  ext/php7/request_hooks.c
  ext/php7/serializer.c
  package.xml
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/exceptions/exceptions.h
  zend_abstract_interface/exceptions/exceptions_common.h
  zend_abstract_interface/exceptions/php7-8/exceptions.c
  zend_abstract_interface/exceptions/php7-8/exceptions.h
  zend_abstract_interface/exceptions/tests/CMakeLists.txt
  zend_abstract_interface/exceptions/tests/php7-8/exceptions.cc
  zend_abstract_interface/properties/php7-8/properties.c
Labels: c-extension

#1286 Add linux/securebits.h to CentOS docker container, to have it present in linux build artifacts
  Makefile
  dockerfiles/ci/centos/6/Dockerfile
Labels: 🐛 bug

#1287 Handle an additional case of capabilities being dropped within our background sender
  config.m4
  ext/php5/coms.c
  ext/php7/coms.c
  ext/php8/coms.c
  package.xml
  tests/ext/background-sender/background_sender_restores_capabilities.phpt
Labels: c-extension, sev-1, 🐛 bug

#1288 Release 0.62.1
  Makefile
  config.m4
  dockerfiles/ci/centos/6/Dockerfile
  ext/php5/coms.c
  ext/php7/coms.c
  ext/php8/coms.c
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
  tests/ext/background-sender/background_sender_restores_capabilities.phpt
Labels: release
