Repository DataDog/dd-trace-php, pull requests merged in 2021-05, with the labels that each got.

#1224 Autocomplete Makefile target names in buster dev images
  dockerfiles/ci/buster/Dockerfile
Labels: cat:devtools

#1223 Tidy up the docker-compose file a bit
  docker-compose.yml
  dockerfiles/development/5.4.ini
  dockerfiles/development/Dockerfile_54
  dockerfiles/development/Dockerfile_56
  dockerfiles/development/Dockerfile_70
  dockerfiles/development/Dockerfile_71_72_73
  dockerfiles/development/dd-test-env.ini
  dockerfiles/development/install-php7-common-dependencies.sh
  dockerfiles/ubuntu-16.04-php-7.1/Dockerfile
  dockerfiles/ubuntu-18.04-php-7.2/Dockerfile
  tests/dockerfiles/Dockerfile_php56_apache
  tests/dockerfiles/apache2.conf
  tests/dockerfiles/php.enanche.ini
  tests/dockerfiles/symfony_34_virtualhost.conf
Labels: ci

#1196 Disable PCNTL in forked processes
  .phpcs.xml
  Makefile
  config.m4
  docker-compose.yml
  dockerfiles/ci/xfail_tests/7.4.list
  dockerfiles/ci/xfail_tests/README.md
  ext/php5/comms_php.c
  ext/php5/coms.c
  ext/php5/coms.h
  ext/php5/ddtrace.c
  ext/php5/ddtrace.h
  ext/php5/handlers_internal.c
  ext/php5/handlers_pcntl.c
  ext/php5/logging.c
  ext/php7/comms_php.c
  ext/php7/coms.c
  ext/php7/coms.h
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php7/handlers_internal.c
  ext/php7/handlers_pcntl.c
  ext/php7/logging.c
  ext/php8/comms_php.c
  ext/php8/coms.c
  ext/php8/coms.h
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/handlers_internal.c
  ext/php8/handlers_pcntl.c
  ext/php8/logging.c
  package.xml
  tests/Common/TracerTestTrait.php
  tests/Integrations/PCNTL/PCNTLTest.php
  tests/Integrations/PCNTL/scripts/_functions.php
  tests/Integrations/PCNTL/scripts/long-running-autoflush.php
  tests/Integrations/PCNTL/scripts/long-running-manual-flush.php
  tests/Integrations/PCNTL/scripts/short-running-multiple-nested.php
  tests/Integrations/PCNTL/scripts/short-running-multiple.php
  tests/Integrations/PCNTL/scripts/short-running.php
  tests/Integrations/PCNTL/scripts/synthetic.php
  tests/ext/includes/fake_global_tracer.inc
  tests/ext/includes/fake_scope.inc
  tests/ext/includes/fake_span.inc
  tests/ext/includes/fake_tracer.inc
  tests/ext/includes/fake_tracer_exception.inc
  tests/ext/pcntl/functions.inc
  tests/ext/pcntl/pcntl_fork_long_running_autoflush.phpt
  tests/ext/pcntl/pcntl_fork_long_running_manual.phpt
  tests/ext/pcntl/pcntl_fork_short_running_multiple.phpt
  tests/ext/pcntl/pcntl_fork_short_running_nested.phpt
  tests/ext/pcntl/pcntl_fork_short_running_single.phpt
  tests/ext/sandbox/auto_flush.phpt
  tests/ext/sandbox/auto_flush_attach_exception.phpt
  tests/ext/sandbox/auto_flush_disables_tracing.phpt
  tests/ext/sandbox/auto_flush_sandbox_exception.phpt
  tests/ext/sandbox/auto_flush_userland_root_span.phpt
Labels: c-extension

#1209 Always resolve curl class entry symbols at runtime (PHP 8)
  .circleci/config.yml
  Makefile
  ext/php8/handlers_curl.c
  tests/ext/from_php_7_3_bug61728.phpt
  tests/ext/pcntl/pcntl_fork_long_running_autoflush.phpt
  tests/ext/pcntl/pcntl_fork_long_running_manual.phpt
  tests/ext/pcntl/pcntl_fork_short_running_multiple.phpt
  tests/ext/pcntl/pcntl_fork_short_running_nested.phpt
  tests/ext/pcntl/pcntl_fork_short_running_single.phpt
  tests/ext/segfault_backtrace_disabled.phpt
  tests/ext/segfault_backtrace_enabled.phpt
Labels: 🐛 bug

#1225 Begin documenting architecture
  .editorconfig
  CONTRIBUTING.md
  UPGRADE-0.10.md
  architecture.md
  components/README.md
  tests/PostInstallHook/README.md
Labels: cat:docs

#1220 Nette integration
  Makefile
  bridge/_files.php
  ext/php5/integrations/integrations.c
  ext/php5/integrations/integrations.h
  ext/php7/integrations/integrations.c
  ext/php7/integrations/integrations.h
  ext/php8/integrations/integrations.c
  ext/php8/integrations/integrations.h
  src/DDTrace/Integrations/IntegrationsLoader.php
  src/DDTrace/Integrations/Nette/NetteIntegration.php
  tests/Frameworks/Nette/Version_2_4/.gitignore
  tests/Frameworks/Nette/Version_2_4/app/bootstrap.php
  tests/Frameworks/Nette/Version_2_4/app/config/config.neon
  tests/Frameworks/Nette/Version_2_4/app/presenters/ErrorPresenter.php
  tests/Frameworks/Nette/Version_2_4/app/presenters/HomepagePresenter.php
  tests/Frameworks/Nette/Version_2_4/app/presenters/templates/@layout.latte
  tests/Frameworks/Nette/Version_2_4/app/presenters/templates/Error/500.phtml
  tests/Frameworks/Nette/Version_2_4/app/presenters/templates/Homepage/default.latte
  tests/Frameworks/Nette/Version_2_4/app/presenters/templates/Homepage/simpleView.latte
  tests/Frameworks/Nette/Version_2_4/app/router/RouterFactory.php
  tests/Frameworks/Nette/Version_2_4/composer.json
  tests/Frameworks/Nette/Version_2_4/log/.gitignore
  tests/Frameworks/Nette/Version_2_4/temp/.gitignore
  tests/Frameworks/Nette/Version_2_4/www/.htaccess
  tests/Frameworks/Nette/Version_2_4/www/index.php
  tests/Frameworks/Nette/Version_3_0/.gitignore
  tests/Frameworks/Nette/Version_3_0/app/Bootstrap.php
  tests/Frameworks/Nette/Version_3_0/app/Presenters/ErrorPresenter.php
  tests/Frameworks/Nette/Version_3_0/app/Presenters/HomepagePresenter.php
  tests/Frameworks/Nette/Version_3_0/app/Presenters/templates/@layout.latte
  tests/Frameworks/Nette/Version_3_0/app/Presenters/templates/Error/500.phtml
  tests/Frameworks/Nette/Version_3_0/app/Presenters/templates/Homepage/default.latte
  tests/Frameworks/Nette/Version_3_0/app/Presenters/templates/Homepage/simpleView.latte
  tests/Frameworks/Nette/Version_3_0/app/Router/RouterFactory.php
  tests/Frameworks/Nette/Version_3_0/app/config/common.neon
  tests/Frameworks/Nette/Version_3_0/composer.json
  tests/Frameworks/Nette/Version_3_0/log/.gitignore
  tests/Frameworks/Nette/Version_3_0/temp/.gitignore
  tests/Frameworks/Nette/Version_3_0/www/.htaccess
  tests/Frameworks/Nette/Version_3_0/www/index.php
  tests/Integrations/Nette/V2_4/NetteTest.php
  tests/Integrations/Nette/V3_0/NetteTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
Labels: cat:new-integration, 🏆 enhancement

#1213 ZAI Sandbox
  .circleci/config.yml
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/sandbox/CMakeLists.txt
  zend_abstract_interface/sandbox/php5/sandbox.c
  zend_abstract_interface/sandbox/php7/sandbox.c
  zend_abstract_interface/sandbox/php8/sandbox.c
  zend_abstract_interface/sandbox/sandbox.h
  zend_abstract_interface/sandbox/tests/CMakeLists.txt
  zend_abstract_interface/sandbox/tests/sandbox.cc
  zend_abstract_interface/sandbox/tests/stubs/throw_exception.php
  zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_ERROR.php
  zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_NOTICE.php
  zend_abstract_interface/sandbox/tests/stubs/trigger_error_E_WARNING.php
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/tests/zai_sapi.cc
  zend_abstract_interface/zai_sapi/tests/zai_sapi_functions.cc
  zend_abstract_interface/zai_sapi/zai_sapi.h
  zend_abstract_interface/zai_sapi/zai_sapi_functions.c
Labels: 🏆 enhancement

#1186 Zend Abstract Interface: Method call seam (PHP 5)
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/methods/CMakeLists.txt
  zend_abstract_interface/methods/methods.h
  zend_abstract_interface/methods/php5/methods.c
  zend_abstract_interface/methods/tests/CMakeLists.txt
  zend_abstract_interface/methods/tests/php5/methods.cc
  zend_abstract_interface/methods/tests/stubs/AbstractTest.php
  zend_abstract_interface/methods/tests/stubs/ExceptionTest.php
  zend_abstract_interface/methods/tests/stubs/Test.php
Labels: c-extension, 🏆 enhancement

#1221 Self update composer in the image we use to prepare the code in CI
  .circleci/config.yml
Labels: dev/testing

#1229 Detect ZAI ZMM leaks
  .circleci/config.yml
  zend_abstract_interface/methods/tests/php5/methods.cc
  zend_abstract_interface/sandbox/tests/sandbox.cc
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/zai_sapi.h
Labels: ci, dev/testing, 🏆 enhancement

#1232 Fix flaky PCNTL tests
  tests/Integrations/PCNTL/PCNTLTest.php
Labels: ci, dev/testing

#1235 Remove Json encoder and Stream transport
  bridge/_files.php
  bridge/dd_register_optional_deps_autoloader.php
  src/DDTrace/Encoders/Json.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  src/DDTrace/Transport/Stream.php
  src/dd-doctor.php
  tests/Common/TracerTestTrait.php
  tests/Integration/Transport/HttpTest.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Unit/Encoders/JsonTest.php
  tests/Unit/Transport/HttpTest.php
  tests/Unit/Transport/StreamTest.php
Labels: 💔 breaking-change

#1239 Remove redundant dd_trace_tracer_is_limited() calls
  bridge/_files.php
  phpstan.ddtrace.neon
  src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
  src/DDTrace/Integrations/Memcached/MemcachedIntegration.php
  src/DDTrace/Integrations/Mongo/MongoIntegration.php
  src/DDTrace/Integrations/Mysqli/MysqliIntegration.php
  src/DDTrace/Integrations/PDO/PDOIntegration.php
  src/DDTrace/Util/CodeTracer.php
Labels: 🏆 enhancement

#1202 Update Docker ci docs
  dockerfiles/ci/README.md
  dockerfiles/ci/xfail_tests/7.1.list
  dockerfiles/ci/xfail_tests/7.2.list
  dockerfiles/ci/xfail_tests/7.4.list
  dockerfiles/ci/xfail_tests/8.0.list
  dockerfiles/ci/xfail_tests/README.md
Labels: ci

#1240 Eliminate "innerhook" from trace_method and trace_function
  ext/php5/ddtrace.c
  ext/php5/dispatch.h
  ext/php7/ddtrace.c
  ext/php7/dispatch.h
  ext/php8/ddtrace.c
  ext/php8/dispatch.h
  tests/ext/dd_trace_api_error.phpt
  tests/ext/sandbox/dd_trace_api_error.phpt
Labels: 🏆 enhancement

#1241 Remove TSRMLS_* macros from PHP 7 and PHP 8
  Makefile
  ext/php7/circuit_breaker.c
  ext/php7/compat_string.h
  ext/php7/configuration.c
  ext/php7/configuration.h
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php7/dispatch.c
  ext/php7/dispatch.h
  ext/php7/dogstatsd_client.c
  ext/php7/dogstatsd_client.h
  ext/php7/engine_hooks.c
  ext/php7/engine_hooks.h
  ext/php7/env_config.c
  ext/php7/env_config.h
  ext/php7/integrations/integrations.c
  ext/php7/integrations/integrations.h
  ext/php7/logging.h
  ext/php7/memory_limit.c
  ext/php7/memory_limit.h
  ext/php7/php7/engine_hooks.c
  ext/php7/random.c
  ext/php7/random.h
  ext/php7/request_hooks.c
  ext/php7/request_hooks.h
  ext/php7/serializer.c
  ext/php7/serializer.h
  ext/php7/signals.c
  ext/php7/signals.h
  ext/php7/span.c
  ext/php7/span.h
  ext/php8/circuit_breaker.c
  ext/php8/compat_string.h
  ext/php8/compatibility.h
  ext/php8/configuration.c
  ext/php8/configuration.h
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/dispatch.c
  ext/php8/dispatch.h
  ext/php8/dogstatsd_client.c
  ext/php8/dogstatsd_client.h
  ext/php8/engine_hooks.c
  ext/php8/env_config.c
  ext/php8/env_config.h
  ext/php8/integrations/integrations.c
  ext/php8/integrations/integrations.h
  ext/php8/memory_limit.c
  ext/php8/memory_limit.h
  ext/php8/php8/engine_hooks.c
  ext/php8/random.c
  ext/php8/random.h
  ext/php8/request_hooks.c
  ext/php8/request_hooks.h
  ext/php8/serializer.c
  ext/php8/serializer.h
  ext/php8/signals.c
  ext/php8/signals.h
  ext/php8/span.c
  ext/php8/span.h
Labels: c-extension

#1238 Change config.m4 to allow in-tree build
  config.m4
  ext/php5/signals.c
  ext/php7/signals.c
  ext/php8/signals.c
  php_ddtrace.h
Labels: c-extension

#1244 Fix meta header name for language version in BGS agent request
  ext/php5/coms.c
  ext/php7/coms.c
  ext/php8/coms.c
  tests/Common/TracerTestTrait.php
  tests/ext/background-sender/agent_headers.phpt
Labels: 🐛 bug

#1245 speed up randomized testing using a post #1192 version
  tests/randomized/app/composer-5.4.json
  tests/randomized/app/composer-5.5.json
  tests/randomized/app/composer-5.6.json
  tests/randomized/app/composer-7.0.json
  tests/randomized/app/composer-7.1.json
  tests/randomized/app/composer-7.2.json
  tests/randomized/app/composer-7.3.json
  tests/randomized/app/composer-7.4.json
  tests/randomized/app/composer-8.0.json
Labels: dev/testing

#1234 ZAI function-call seam (PHP 8)
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/functions/CMakeLists.txt
  zend_abstract_interface/functions/functions.h
  zend_abstract_interface/functions/php8/functions.c
  zend_abstract_interface/functions/tests/CMakeLists.txt
  zend_abstract_interface/functions/tests/php8/functions.cc
  zend_abstract_interface/functions/tests/stubs/basic.php
  zend_abstract_interface/methods/php5/methods.c
  zend_abstract_interface/sandbox/php8/sandbox.c
  zend_abstract_interface/sandbox/sandbox.h
  zend_abstract_interface/zai_assert/CMakeLists.txt
  zend_abstract_interface/zai_assert/zai_assert.h
Labels: 🏆 enhancement

#1237 Move from uint63 to uint64 for trace_id span_id and parent_id
  .circleci/config.yml
  docker-compose.yml
  ext/php5/random.c
  ext/php5/serializer.c
  ext/php7/random.c
  ext/php7/serializer.c
  ext/php8/random.c
  ext/php8/serializer.c
  src/DDTrace/Encoders/MessagePack.php
  src/DDTrace/Encoders/SpanEncoder.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/SpanContext.php
  src/DDTrace/Tracer.php
  src/DDTrace/Transport/Http.php
  tests/Common/SpanChecker.php
  tests/DistributedTracing/DistributedTraceTest.php
  tests/DistributedTracing/SandboxAndLegacyTest.php
  tests/DistributedTracing/SyntheticsTest.php
  tests/Integration/CurrentContextAccess/CurrentContextAccessTest.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/ext/dd_trace_push_span_id_from_userland.phpt
  tests/ext/dd_trace_serialize_msgpack.phpt
  tests/ext/dd_trace_serialize_msgpack_reference.phpt
  tests/ext/sandbox-prehook/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_function_internal.phpt
  tests/ext/sandbox/dd_trace_function_userland.phpt
  tests/ext/sandbox/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_push_span_id.phpt
  tests/ext/sandbox/dd_trace_set_trace_id.phpt
  tests/ext/sandbox/errors_are_flagged_from_userland.phpt
Labels: c-extension

#1243 Deferred loading with ZAI function-call seam (PHP 8)
  ext/php8/ddtrace.c
  ext/php8/engine_hooks.h
  ext/php8/php8/engine_hooks.c
Labels: c-extension

#1247 Release 0.60.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release

#1246 Create property ZAI seam for PHP 8
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/properties/CMakeLists.txt
  zend_abstract_interface/properties/php7-8/properties.c
  zend_abstract_interface/properties/php7-8/properties.h
  zend_abstract_interface/properties/properties.h
  zend_abstract_interface/properties/tests/CMakeLists.txt
  zend_abstract_interface/properties/tests/php7-8/properties.cc
  zend_abstract_interface/properties/tests/stubs/classes.php
Labels: 🏆 enhancement
