Repository DataDog/dd-trace-php, pull requests merged in 2021-03, with the labels that each got.

#1162 remove non php7 code from ext/php7 folder
  ext/php7/arrays.c
  ext/php7/auto_flush.h
  ext/php7/comms_php.c
  ext/php7/compat_string.c
  ext/php7/compat_string.h
  ext/php7/compatibility.h
  ext/php7/configuration.c
  ext/php7/ddtrace.c
  ext/php7/ddtrace_string.c
  ext/php7/ddtrace_string.h
  ext/php7/dispatch.c
  ext/php7/engine_api.c
  ext/php7/engine_hooks.c
  ext/php7/engine_hooks.h
  ext/php7/logging.h
  ext/php7/php7/engine_hooks.c
  ext/php7/random.c
  ext/php7/request_hooks.c
  ext/php7/serializer.c
  ext/php7/span.c
  ext/php7/span.h
  ext/php7/startup_logging.h
Labels: c-extension

#1164 Remove non php5 code from ext/php5 folder
  ext/php5/arrays.c
  ext/php5/comms_php.c
  ext/php5/compat_string.c
  ext/php5/compat_string.h
  ext/php5/compatibility.h
  ext/php5/configuration.c
  ext/php5/ddtrace.c
  ext/php5/ddtrace_string.h
  ext/php5/dispatch.c
  ext/php5/dispatch.h
  ext/php5/handlers_internal.c
  ext/php5/integrations/integrations.c
  ext/php5/logging.h
  ext/php5/php5/engine_hooks.c
  ext/php5/random.c
  ext/php5/request_hooks.c
  ext/php5/serializer.c
  ext/php5/span.c
  ext/php5/startup_logging.h
Labels: c-extension

#1167 bump version 0.56.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release

#1163 do not keep alive connections while executing randomized testing
  tests/randomized/docker/run.sh
Labels: dev/testing

#1165 Remove non php8 code from ext/php8 folder
  ext/php8/arrays.c
  ext/php8/auto_flush.h
  ext/php8/comms_php.c
  ext/php8/compat_string.c
  ext/php8/compat_string.h
  ext/php8/compatibility.h
  ext/php8/configuration.c
  ext/php8/ddtrace.c
  ext/php8/ddtrace_string.c
  ext/php8/ddtrace_string.h
  ext/php8/dispatch.c
  ext/php8/dispatch.h
  ext/php8/engine_api.c
  ext/php8/excluded_modules.c
  ext/php8/logging.h
  ext/php8/random.c
  ext/php8/request_hooks.c
  ext/php8/serializer.c
  ext/php8/span.c
  ext/php8/startup_logging.h
Labels: c-extension

#1172 [Tracer] Add component system, string_view and sapi components
  .circleci/config.yml
  Makefile
  components/CMakeLists.txt
  components/catch2_main.cc
  components/sapi/CMakeLists.txt
  components/sapi/sapi.c
  components/sapi/sapi.h
  components/sapi/tests/CMakeLists.txt
  components/sapi/tests/sapi.cc
  components/string_view/CMakeLists.txt
  components/string_view/string_view.c
  components/string_view/string_view.h
  components/string_view/tests/CMakeLists.txt
  components/string_view/tests/string_view.cc
  config.m4
  dockerfiles/ci/xfail_tests/5.4.list
  ext/php5/ddtrace.c
  ext/php7/ddtrace.c
  ext/php8/ddtrace.c
  package.xml
Labels: c-extension

#1173 More curl-multi scenarios in randomized tests
  tests/randomized/app/src/RandomizedTests/Snippets.php
Labels: dev/testing

#1176 Enable Symfony on PHP 8.0
  Makefile
  src/DDTrace/Integrations/IntegrationsLoader.php
  tests/Frameworks/Symfony/Version_4_4/composer.json
  tests/Frameworks/Symfony/Version_5_0/composer.lock
  tests/Unit/Integrations/IntegrationsLoaderTest.php
Labels: 🏆 enhancement

#1177 Add sources for Symfony 5.2 framework
  tests/Frameworks/README.md
  tests/Frameworks/Symfony/Version_5_2/.env
  tests/Frameworks/Symfony/Version_5_2/.gitignore
  tests/Frameworks/Symfony/Version_5_2/bin/console
  tests/Frameworks/Symfony/Version_5_2/composer.json
  tests/Frameworks/Symfony/Version_5_2/config/bundles.php
  tests/Frameworks/Symfony/Version_5_2/config/packages/cache.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/framework.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/prod/routing.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/routing.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/test/framework.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/test/twig.yaml
  tests/Frameworks/Symfony/Version_5_2/config/packages/twig.yaml
  tests/Frameworks/Symfony/Version_5_2/config/preload.php
  tests/Frameworks/Symfony/Version_5_2/config/routes.yaml
  tests/Frameworks/Symfony/Version_5_2/config/routes/annotations.yaml
  tests/Frameworks/Symfony/Version_5_2/config/routes/dev/framework.yaml
  tests/Frameworks/Symfony/Version_5_2/config/services.yaml
  tests/Frameworks/Symfony/Version_5_2/public/index.php
  tests/Frameworks/Symfony/Version_5_2/src/Controller/.gitignore
  tests/Frameworks/Symfony/Version_5_2/src/Kernel.php
  tests/Frameworks/Symfony/Version_5_2/templates/base.html.twig
Labels: dev/testing

#1178 Test Symfony 5.2
  Makefile
  tests/Frameworks/Symfony/Version_5_2/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_5_2/templates/twig_template.html.twig
  tests/Integrations/Symfony/V5_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_2/TraceSearchConfigTest.php
  tooling/bin/install-xdebug.sh
Labels: dev/testing

#1143 Move container ID detection to the extension level
  .circleci/config.yml
  Makefile
  bridge/_files.php
  cmake/ubsan.cmake
  components/CMakeLists.txt
  components/container_id/CMakeLists.txt
  components/container_id/container_id.c
  components/container_id/container_id.h
  components/container_id/tests/CMakeLists.txt
  components/container_id/tests/container_id.cc
  components/container_id/tests/stubs/cgroup.docker
  components/container_id/tests/stubs/cgroup.ecs
  components/container_id/tests/stubs/cgroup.edge_cases
  components/container_id/tests/stubs/cgroup.fargate
  components/container_id/tests/stubs/cgroup.fargate.1.4
  components/container_id/tests/stubs/cgroup.kubernetes
  components/container_id/tests/stubs/cgroup.linux
  components/container_id/tests/stubs/cgroup.unrecognized
  components/container_id/tests/stubs/cgroup.whitespace
  components/string_view/string_view.c
  components/string_view/string_view.h
  components/string_view/tests/string_view.cc
  config.m4
  docker-compose.yml
  ext/php5/comms_php.c
  ext/php5/comms_php.h
  ext/php5/coms.c
  ext/php5/coms.h
  ext/php5/ddshared.c
  ext/php5/ddshared.h
  ext/php5/ddtrace.c
  ext/php5/ddtrace.h
  ext/php7/comms_php.c
  ext/php7/comms_php.h
  ext/php7/coms.c
  ext/php7/coms.h
  ext/php7/ddshared.c
  ext/php7/ddshared.h
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php8/comms_php.c
  ext/php8/comms_php.h
  ext/php8/coms.c
  ext/php8/coms.h
  ext/php8/ddshared.c
  ext/php8/ddshared.h
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  package.xml
  src/DDTrace/Transport/Http.php
  src/DDTrace/Util/ContainerInfo.php
  tests/Unit/Util/ContainerInfoTest.php
  tests/ext/background-sender/agent_headers.phpt
  tests/ext/background-sender/agent_headers_container_id.phpt
  tests/ext/background-sender/agent_headers_container_id_empty.phpt
  tests/ext/background-sender/agent_headers_ignore_userland.phpt
  tests/ext/background-sender/stubs/cgroup.docker
  tests/ext/background-sender/stubs/cgroup.empty
  tests/ext/includes/request_replayer.inc
Labels: c-extension, dev/testing

#1179 Refactor the PHP 8 exception serialization
  ext/php8/engine_api.h
  ext/php8/serializer.c
  tests/Integrations/PDO/PDOTest.php
Labels: c-extension, dev/testing, 🐛 bug

#1170 Support PsrHttpServerMiddleware for Slim 4
  src/DDTrace/Integrations/Slim/SlimIntegration.php
  tests/Integrations/Slim/V4/CommonScenariosTest.php
Labels: 🏆 enhancement

#1183 Import framework tests suite from dd-trace-ci to dd-trace-php
  dockerfiles/frameworks/Makefile
  dockerfiles/frameworks/README.md
  dockerfiles/frameworks/contrib/Dockerfile
  dockerfiles/frameworks/contrib/entrypoint.sh
  dockerfiles/frameworks/contrib/flow/20-redis.ini
  dockerfiles/frameworks/contrib/flow/30.tz.ini
  dockerfiles/frameworks/contrib/flow/Settings.yaml
  dockerfiles/frameworks/contrib/flow/patch.patch
  dockerfiles/frameworks/contrib/flow/run.sh
  dockerfiles/frameworks/contrib/laravel/patch.patch
  dockerfiles/frameworks/contrib/phpredis/3.1.6/patch.patch
  dockerfiles/frameworks/contrib/phpredis/3.1.6/run.sh
  dockerfiles/frameworks/contrib/phpredis/4.3.0/patch.patch
  dockerfiles/frameworks/contrib/phpredis/4.3.0/run.sh
  dockerfiles/frameworks/contrib/phpredis/5.3.1/patch.patch
  dockerfiles/frameworks/contrib/phpredis/5.3.1/run.sh
  dockerfiles/frameworks/contrib/switch_php.sh
  dockerfiles/frameworks/contrib/symfony/run.sh
  dockerfiles/frameworks/contrib/symfony/v4.3.4.patch
  dockerfiles/frameworks/contrib/wordpress/4.8.10.patch
  dockerfiles/frameworks/contrib/wordpress/run.sh
  dockerfiles/frameworks/contrib/wordpress/wp-tests-config.php
  dockerfiles/frameworks/flow.yml
  dockerfiles/frameworks/laravel.yml
  dockerfiles/frameworks/phpredis3.yml
  dockerfiles/frameworks/phpredis4.yml
  dockerfiles/frameworks/phpredis5.yml
  dockerfiles/frameworks/symfony.yml
  dockerfiles/frameworks/wordpress.yml
Labels: dev/testing

#1181 Fix "undefined symbol: curl_multi_ce" on PHP 8
  .circleci/config.yml
  docker-compose.yml
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/buster/php-8.0/Dockerfile_shared_ext
  dockerfiles/ci/buster/php-8.0/configure_shared_ext.sh
  dockerfiles/ci/buster/php-master/Dockerfile
  dockerfiles/ci/buster/php-master/install-php-master
  dockerfiles/ci/xfail_tests/8.0.list
  ext/php8/ddtrace.c
  ext/php8/handlers_curl.c
  package.xml
  tests/ext/integrations/curl/distributed_tracing.inc
  tests/ext/integrations/curl/distributed_tracing_curl.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_copy_handle.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_inject.inc
  tests/ext/integrations/curl/distributed_tracing_curl_inject_exception.inc
  tests/ext/integrations/curl/distributed_tracing_curl_missing_fn.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle_bug_71523.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_disable.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_sandboxed.phpt
Labels: c-extension, 🐛 bug
