Repository DataDog/dd-trace-php, pull requests merged in 2021-06, with the labels that each got.

#1227 Add \DDTrace\get_current_context
  ext/php5/ddtrace.c
  ext/php7/ddtrace.c
  ext/php8/ddtrace.c
  package.xml
  tests/ext/dd_trace_current_context.phpt
  tests/ext/dd_trace_current_context_noenv.phpt
Labels: 🏆 enhancement

#1248 Create exceptions ZAI seam for PHP 8
  config.m4
  ext/php8/engine_hooks.c
  ext/php8/engine_hooks.h
  ext/php8/php8/engine_hooks.c
  ext/php8/request_hooks.c
  ext/php8/serializer.c
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/exceptions/exceptions.h
  zend_abstract_interface/exceptions/exceptions_common.h
  zend_abstract_interface/exceptions/php8/exceptions.c
  zend_abstract_interface/exceptions/php8/exceptions.h
  zend_abstract_interface/exceptions/tests/CMakeLists.txt
  zend_abstract_interface/exceptions/tests/php8/exceptions.cc
  zend_abstract_interface/exceptions/tests/stubs/functions.php
Labels: c-extension, 🏆 enhancement

#1255 Run mongodb-driver testsuite in CI with and without the tracer
  .circleci/config.yml
  dockerfiles/frameworks/contrib/Dockerfile
  dockerfiles/frameworks/contrib/mongodb-driver/README.md
  dockerfiles/frameworks/contrib/mongodb-driver/run.sh
  dockerfiles/frameworks/mongodb-driver.yml
Labels: dev/testing

#1257 Relese 0.61.0
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: release

#1254 Refactor internal span objects to be allocated together with their internal data
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/php8/engine_hooks.c
  ext/php8/serializer.c
  ext/php8/span.c
  ext/php8/span.h
  package.xml
  tests/ext/active_span.phpt
  tests/ext/sandbox/span_clone.phpt
  tests/ext/sandbox/span_resource_serialization.phpt
Labels: c-extension

#1256 Add ZAI component for reading headers
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/env/env.h
  zend_abstract_interface/headers/CMakeLists.txt
  zend_abstract_interface/headers/headers.h
  zend_abstract_interface/headers/php7-8/headers.c
  zend_abstract_interface/headers/tests/CMakeLists.txt
  zend_abstract_interface/headers/tests/php7-8/headers.cc
  zend_abstract_interface/zai_assert/zai_assert.h
  zend_abstract_interface/zai_sapi/php5/zai_sapi.c
  zend_abstract_interface/zai_sapi/php7/zai_sapi.c
  zend_abstract_interface/zai_sapi/php8/zai_sapi.c
  zend_abstract_interface/zai_sapi/zai_sapi.h
  zend_abstract_interface/zai_string/CMakeLists.txt
  zend_abstract_interface/zai_string/string.h
Labels: c-extension, 🏆 enhancement

#1258 Enforce metrics to be floats in internal serializer
  ext/php5/serializer.c
  ext/php7/serializer.c
  ext/php8/serializer.c
  tests/ext/sandbox-prehook/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_method.phpt
Labels: c-extension, 🐛 bug

#1259 Fix msgpack serialization of empty arrays
  ext/php5/serializer.c
  ext/php7/serializer.c
  ext/php8/serializer.c
  tests/ext/dd_trace_serialize_msgpack.phpt
Labels: c-extension, 🐛 bug

#1266 Fix tests: Pin Symfony 4 tests to laminas/laminas-code < 4.4
  tests/Frameworks/Symfony/Version_4_2/composer.json
  tests/Frameworks/Symfony/Version_4_4/composer.json
Labels: dev/testing

#1265 Allow for global debug mode, add zai testing to Makefile and more minor testing improvements
  CONTRIBUTING.md
  Makefile
  docker-compose.yml
  dockerfiles/ci/buster/Dockerfile
  tests/Sapi/CliServer/CliServer.php
  tests/Sapi/PhpCgi/PhpCgi.php
  tests/Sapi/PhpFpm/PhpFpm.php
  zend_abstract_interface/CMakeLists.txt
Labels: dev/testing
