Repository DataDog/dd-trace-php, pull requests merged in 2021-09, with the labels that each got.

#1304 Fix memory leak of already defined global tags
  .circleci/config.yml
  ext/php8/serializer.c
Labels: c-extension

#1300 Add functions ZAI support for PHP 5 and 7
  config.m4
  ext/php7/ddtrace.c
  ext/php7/engine_hooks.h
  ext/php7/php7/engine_hooks.c
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/functions/CMakeLists.txt
  zend_abstract_interface/functions/functions.h
  zend_abstract_interface/functions/php5/functions.c
  zend_abstract_interface/functions/php7-8/functions.c
  zend_abstract_interface/functions/tests/CMakeLists.txt
  zend_abstract_interface/functions/tests/functions.cc
  zend_abstract_interface/headers/CMakeLists.txt
  zend_abstract_interface/properties/CMakeLists.txt
  zend_abstract_interface/zai_compat.h
Labels: 🏆 enhancement, c-extension

#1306 Add properties and exceptions ZAI implementations for PHP 5
  config.m4
  package.xml
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/exceptions/exceptions_common.h
  zend_abstract_interface/exceptions/php5/exceptions.c
  zend_abstract_interface/exceptions/php5/exceptions.h
  zend_abstract_interface/exceptions/php7-8/exceptions.h
  zend_abstract_interface/exceptions/tests/php5/exceptions.cc
  zend_abstract_interface/properties/CMakeLists.txt
  zend_abstract_interface/properties/php5/properties.c
  zend_abstract_interface/properties/php5/properties.h
  zend_abstract_interface/properties/tests/CMakeLists.txt
  zend_abstract_interface/properties/tests/php7-8/properties.cc
  zend_abstract_interface/properties/tests/properties.cc
Labels: c-extension

#1320 Fix CLI processes emitting empty root spans when CLI tracing is not enabled
  .circleci/config.yml
  Makefile
  ext/php7/ddtrace.c
  ext/php7/handlers_curl.c
  ext/php7/span.c
  ext/php8/ddtrace.c
  ext/php8/handlers_curl.c
  ext/php8/span.c
  tests/Common/AgentReplayerTrait.php
  tests/Integration/DisabledTest.php
Labels: 🐛 bug, c-extension

#1322 Enhance exception reporting on Laravel 5+
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
  tests/Integrations/Laravel/V8_x/CommonScenariosTest.php
Labels: 🏆 enhancement

#1267 Migrate _dd.origin & distributed header sending to internal
  .circleci/config.yml
  Makefile
  docker-compose.yml
  ext/php7/ddtrace.c
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/handlers_curl.c
  ext/php8/serializer.c
  ext/php8/span.c
  ext/php8/span.h
  package.xml
  src/DDTrace/Bootstrap.php
  src/DDTrace/Propagators/TextMap.php
  src/DDTrace/Tracer.php
  src/api/Contracts/SpanContext.php
  src/api/Data/SpanContext.php
  tests/C2PHP/get_context_distributed_tracing_test.phpt
  tests/Common/TracerTestTrait.php
  tests/Integrations/Curl/CurlIntegrationTest.php
  tests/Integrations/Guzzle/V5/GuzzleIntegrationTest.php
  tests/Integrations/Guzzle/V6/GuzzleIntegrationTest.php
  tests/Unit/SpanTest.php
  tests/Unit/TracerTest.php
  tests/ext/distributed_tracing/distributed_trace_bogus_ids.phpt
  tests/ext/distributed_tracing/distributed_trace_inherit.phpt
  tests/ext/integrations/curl/distributed_tracing_curl.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_copy_handle.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_existing_headers_003.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_inject.inc
  tests/ext/integrations/curl/distributed_tracing_curl_missing_fn.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_copy_handle_bug_71523.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_disable.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_001.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_multi_exec_existing_headers_002.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_sampling_priority.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_sandboxed.phpt
  tests/randomized/README.md
  tests/randomized/docker/Dockerfile
  tests/randomized/docker/run.sh
  tests/randomized/lib/templates/Makefile.scenario.template
  tests/randomized/lib/templates/docker-compose.template.yml
Labels: 🏆 enhancement, c-extension
