Repository DataDog/dd-trace-php, pull requests merged in 2022-02, with the labels that each got.

#1487 Remove version number from datadog-setup.php's help output
  datadog-setup.php
Labels: 🐛 bug, cat:installation

#1491 Adjust stack sample max stack depth
  components/stack-sample/stack-sample.c
  components/stack-sample/stack-sample.h
Labels: c-extension

#1489 Improve error detection for datadog-setup.php
  datadog-setup.php
Labels: cat:installation

#1495 Update profiling to v0.4.0
  Makefile
Labels: 🏆 enhancement, c-extension

#1496 Release 0.70.0
  .gitlab-ci.yml
  Makefile
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
Labels: ⏩ Version Bump, release

#1502 Clean up Tea SAPI and allow ddtrace to run there
  .circleci/config.yml
  components/sapi/sapi.c
  components/sapi/sapi.h
  components/sapi/tests/sapi.cc
  ext/php5/ddtrace.c
  ext/php7/ddtrace.c
  ext/php8/ddtrace.c
  tea/CMakeLists.txt
Labels: dev/testing

#1499 Trigger profiling interrupt function before internal observer_end
  .circleci/config.yml
  ext/php7/ddtrace.c
  ext/php7/engine_hooks.h
  ext/php7/handlers_internal.c
  ext/php7/handlers_internal.h
  ext/php7/php7/engine_hooks.c
  ext/php8/ddtrace.c
  ext/php8/engine_hooks.h
  ext/php8/handlers_internal.c
  ext/php8/handlers_internal.h
  ext/php8/php8/engine_hooks.c
  tests/tea/CMakeLists.txt
  tests/tea/profiling/CMakeLists.txt
  tests/tea/profiling/interrupt.cc
  tests/tea/profiling/profiling.cc
  tests/tea/profiling/profiling.h
  tests/tea/profiling/sleep.php
Labels: c-extension

#1507 Always include the Tea SAPI Catch2 test header
  tea/CMakeLists.txt
Labels: dev/testing

#1511 Fix #1510 post-install not detecting required extension
  package/post-install.sh
Labels: cat:installation

#1506 Increase sending backlog size by 20%
  ext/php5/coms.h
  ext/php7/coms.h
  ext/php8/coms.h
Labels: c-extension

#1513 (PHP 5) Remove empty multi_curl handles hashtables and track curl handle freeing
  ext/php5/handlers_curl.c
  ext/php5/handlers_internal.c
Labels: c-extension

#1515 Add is_nil function to UUID component
  components/uuid/tests/uuid.cc
  components/uuid/uuid.c
  components/uuid/uuid.h
Labels: c-extension

#1356 Add long running script memory check to randomized tests
  phpcs.xml
  tests/randomized/Makefile
  tests/randomized/analyze-results.php
  tests/randomized/app/public/index.php
  tests/randomized/app/public/long_running_script.php
  tests/randomized/app/src/RandomizedTests/RandomExecutionPath.php
  tests/randomized/app/src/RandomizedTests/RandomExecutionPathConfiguration.php
  tests/randomized/app/src/RandomizedTests/Snippets.php
  tests/randomized/app/src/RandomizedTests/SnippetsConfiguration.php
  tests/randomized/config/envs.php
  tests/randomized/docker/prepare.sh
  tests/randomized/docker/run.sh
  tests/randomized/generate-scenarios.php
  tests/randomized/lib/CLIRunnerGenerator.php
  tests/randomized/lib/templates/cli-runner.template.sh
  tests/randomized/lib/templates/docker-compose.template.yml
Labels: ci

#1526 Tea ZE Suppport
  tea/include/extension.h
  tea/private/extension.h
  tea/src/extension.c
  tea/tests/extension.cc
Labels: c-extension

#1527 Run cmake-format on TEA's CMakeLists.txt
  tea/CMakeLists.txt
Labels: dev/testing
