Repository DataDog/dd-trace-php, pull requests merged in 2022-04, with the labels that each got.

#1564 Respect autofinish on flush(), add warnings in debug mode when having unbalanced spans
  ext/php5/ddtrace.c
  ext/php5/span.c
  ext/php7/ddtrace.c
  ext/php7/span.c
  ext/php8/ddtrace.c
  ext/php8/span.c
  src/DDTrace/Span.php
  src/DDTrace/Tracer.php
  tests/Integration/TracerTest.php
  tests/Integrations/PCNTL/scripts/long-running-manual-flush.php
  tests/ext/close_spans_until.phpt
  tests/ext/start_span_without_closing.phpt
  tests/ext/start_span_without_closing_autofinish.phpt
Labels: c-extension

#1573 Update profiling to v0.6.0
  Makefile
Labels: 🏆 enhancement

#1576 datadog-setup: allow profiling for PHP 8.1
  datadog-setup.php
  tooling/bin/generate-final-artifact.sh
Labels: 🏆 enhancement, cat:installation
