Repository DataDog/dd-trace-php, pull requests merged in 2022-01, with the labels that each got.

#1440 Replace direct access of meta/metrics zvals by safe array access in most places
  ext/php5/ddshared.c
  ext/php5/startup_logging.c
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php7/priority_sampling/priority_sampling.c
  ext/php7/serializer.c
  ext/php7/span.c
  ext/php7/startup_logging.c
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/priority_sampling/priority_sampling.c
  ext/php8/serializer.c
  ext/php8/span.c
  ext/php8/startup_logging.c
Labels: sev-1

#1411 Move ZAI SAPI to root directory
  .circleci/config.yml
  Makefile
  zai_sapi/CMakeLists.txt
  zai_sapi/cmake/ZaiSapiConfig.cmake.in
  zai_sapi/php5/zai_sapi.c
  zai_sapi/php7/zai_sapi.c
  zai_sapi/php8/zai_sapi.c
  zai_sapi/tests/CMakeLists.txt
  zai_sapi/tests/stubs/basic.php
  zai_sapi/tests/stubs/trigger_error_E_CORE_ERROR.php
  zai_sapi/tests/stubs/trigger_error_E_ERROR.php
  zai_sapi/tests/stubs/trigger_error_E_NOTICE.php
  zai_sapi/tests/stubs/trigger_error_E_WARNING.php
  zai_sapi/tests/stubs/trigger_error_invalid.php
  zai_sapi/tests/zai_sapi.cc
  zai_sapi/tests/zai_sapi_functions.cc
  zai_sapi/tests/zai_sapi_ini.cc
  zai_sapi/tests/zai_sapi_io.cc
  zai_sapi/zai_sapi.h
  zai_sapi/zai_sapi_extension.c
  zai_sapi/zai_sapi_extension.h
  zai_sapi/zai_sapi_functions.c
  zai_sapi/zai_sapi_functions.h
  zai_sapi/zai_sapi_ini.c
  zai_sapi/zai_sapi_ini.h
  zai_sapi/zai_sapi_io.c
  zai_sapi/zai_sapi_io.h
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/config/tests/CMakeLists.txt
  zend_abstract_interface/env/tests/CMakeLists.txt
  zend_abstract_interface/exceptions/tests/CMakeLists.txt
  zend_abstract_interface/functions/tests/CMakeLists.txt
  zend_abstract_interface/headers/tests/CMakeLists.txt
  zend_abstract_interface/json/tests/CMakeLists.txt
  zend_abstract_interface/methods/tests/CMakeLists.txt
  zend_abstract_interface/properties/tests/CMakeLists.txt
  zend_abstract_interface/sandbox/tests/CMakeLists.txt
  zend_abstract_interface/uri_normalization/tests/CMakeLists.txt
  zend_abstract_interface/zai_sapi/CMakeLists.txt
Labels: dev/testing

#1443 Fix ZaiSapi_ROOT path in Makefile
  .circleci/config.yml
  Makefile
Labels: dev/testing

#1446 Release 0.68.2
  .gitlab-ci.yml
  Makefile
  ext/php5/ddshared.c
  ext/php5/startup_logging.c
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php7/priority_sampling/priority_sampling.c
  ext/php7/serializer.c
  ext/php7/span.c
  ext/php7/startup_logging.c
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/priority_sampling/priority_sampling.c
  ext/php8/serializer.c
  ext/php8/span.c
  ext/php8/startup_logging.c
  ext/version.h
  package.xml
  src/DDTrace/Tracer.php
  tooling/bin/generate-final-artifact.sh
Labels: ⏩ Version Bump

#1447 Revert "remove embed sapi (#1195)"
  dockerfiles/ci/alpine/php-8.0/configure.sh
  dockerfiles/ci/centos/6/php-5.4/configure.sh
  dockerfiles/ci/centos/6/php-5.5/configure.sh
  dockerfiles/ci/centos/6/php-5.6/configure.sh
  dockerfiles/ci/centos/6/php-7.0/configure.sh
  dockerfiles/ci/centos/6/php-7.1/configure.sh
  dockerfiles/ci/centos/6/php-7.2/configure.sh
  dockerfiles/ci/centos/6/php-7.3/configure.sh
  dockerfiles/ci/centos/6/php-7.4/configure.sh
  dockerfiles/ci/centos/6/php-8.0/configure.sh
Labels: ci

#1454 Strip query string from http.url
  ext/php5/serializer.c
  ext/php7/serializer.c
  ext/php8/serializer.c
  tests/ext/root_span_url_as_resource_names.phpt
Labels: 🏆 enhancement, c-extension

#1405 Implement x-datadog-tag propagation and _dd.p.upstream_services
  config.m4
  ext/php5/configuration.h
  ext/php5/ddtrace.c
  ext/php5/ddtrace.h
  ext/php5/handlers_curl.c
  ext/php5/priority_sampling/priority_sampling.c
  ext/php5/serializer.c
  ext/php5/tracer_tag_propagation/tracer_tag_propagation.c
  ext/php5/tracer_tag_propagation/tracer_tag_propagation.h
  ext/php7/configuration.h
  ext/php7/ddtrace.c
  ext/php7/ddtrace.h
  ext/php7/handlers_curl.c
  ext/php7/priority_sampling/priority_sampling.c
  ext/php7/serializer.c
  ext/php7/tracer_tag_propagation/tracer_tag_propagation.c
  ext/php7/tracer_tag_propagation/tracer_tag_propagation.h
  ext/php8/configuration.h
  ext/php8/ddtrace.c
  ext/php8/ddtrace.h
  ext/php8/handlers_curl.c
  ext/php8/priority_sampling/priority_sampling.c
  ext/php8/serializer.c
  ext/php8/tracer_tag_propagation/tracer_tag_propagation.c
  ext/php8/tracer_tag_propagation/tracer_tag_propagation.h
  tests/Common/SpanChecker.php
  tests/ext/distributed_tracing/distributed_trace_bogus_ids.phpt
  tests/ext/distributed_tracing/distributed_trace_inherit.phpt
  tests/ext/integrations/curl/distributed_tracing_curl.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_copy_handle.phpt
  tests/ext/integrations/curl/distributed_tracing_curl_propagate_tags.phpt
  tests/ext/priority_sampling/001-default-sampling.phpt
  tests/ext/priority_sampling/002-user-reject.phpt
  tests/ext/priority_sampling/003-user-keep.phpt
  tests/ext/priority_sampling/004-rule-basic.phpt
  tests/ext/priority_sampling/005-rule-name.phpt
  tests/ext/priority_sampling/006-rule-name-reject.phpt
  tests/ext/priority_sampling/007-rule-service.phpt
  tests/ext/priority_sampling/008-rule-service-reject.phpt
  tests/ext/priority_sampling/009-rule-name-service.phpt
  tests/ext/priority_sampling/010-rule-name-service-reject.phpt
  tests/ext/priority_sampling/011-preset.phpt
  tests/ext/priority_sampling/012-default.phpt
  tests/ext/root_span_add_tag.phpt
  tests/ext/root_span_url_as_resource_names.phpt
  tests/ext/root_span_url_as_resource_names_no_host.phpt
  tests/ext/sandbox-prehook/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_function_alias.phpt
  tests/ext/sandbox/dd_trace_function_complex.phpt
  tests/ext/sandbox/dd_trace_function_internal.phpt
  tests/ext/sandbox/dd_trace_method.phpt
  tests/ext/sandbox/dd_trace_method_alias.phpt
  tests/ext/sandbox/default_span_properties.phpt
  tests/ext/sandbox/default_span_properties_method.phpt
  tests/ext/sandbox/errors_are_flagged_from_userland.phpt
  tests/ext/sandbox/span_clone.phpt
  tests/ext/span_with_removed_exception.phpt
  tests/ext/start_span_with_all_properties.phpt
  tests/ext/start_span_without_closing.phpt
  zend_abstract_interface/config/config.h
Labels: 🏆 enhancement, c-extension

#1453 ZAI Value Interface
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/value/CMakeLists.txt
  zend_abstract_interface/value/tests/CMakeLists.txt
  zend_abstract_interface/value/tests/value.cc
  zend_abstract_interface/value/value.h
Labels: c-extension

#1455 ZAI SAPI Test Harness
  zai_sapi/CMakeLists.txt
  zai_sapi/php5/zai_sapi.c
  zai_sapi/php7/zai_sapi.c
  zai_sapi/php8/zai_sapi.c
  zai_sapi/testing/catch2.hpp
  zai_sapi/tests/zai_sapi.cc
  zai_sapi/tests/zai_sapi_functions.cc
  zai_sapi/tests/zai_sapi_ini.cc
  zai_sapi/tests/zai_sapi_io.cc
Labels: c-extension

#1458 ZAI Test Harness Bailout Handling
  zai_sapi/php5/zai_sapi.c
  zai_sapi/php7/zai_sapi.c
  zai_sapi/php8/zai_sapi.c
  zai_sapi/testing/catch2.hpp
  zai_sapi/tests/CMakeLists.txt
  zai_sapi/tests/zai_sapi_testing.cc
Labels: c-extension

#1457 ZAI Test Refactoring
  zend_abstract_interface/config/tests/CMakeLists.txt
  zend_abstract_interface/config/tests/config.cc
  zend_abstract_interface/config/tests/config_test_helpers.h
  zend_abstract_interface/config/tests/decode.cc
  zend_abstract_interface/config/tests/default.cc
  zend_abstract_interface/config/tests/env.cc
  zend_abstract_interface/config/tests/ext_zai_config.cc
  zend_abstract_interface/config/tests/id.cc
  zend_abstract_interface/config/tests/ini.cc
  zend_abstract_interface/config/tests/zai_tests_common.hpp
  zend_abstract_interface/env/tests/CMakeLists.txt
  zend_abstract_interface/env/tests/env.cc
  zend_abstract_interface/env/tests/error.cc
  zend_abstract_interface/env/tests/host.cc
  zend_abstract_interface/env/tests/sapi.cc
  zend_abstract_interface/env/tests/zai_tests_common.hpp
  zend_abstract_interface/exceptions/tests/php5/exceptions.cc
  zend_abstract_interface/exceptions/tests/php7-8/exceptions.cc
  zend_abstract_interface/headers/tests/headers.cc
  zend_abstract_interface/json/tests/json.cc
  zend_abstract_interface/sandbox/tests/CMakeLists.txt
  zend_abstract_interface/sandbox/tests/error.cc
  zend_abstract_interface/sandbox/tests/exception.cc
  zend_abstract_interface/sandbox/tests/sandbox.cc
  zend_abstract_interface/sandbox/tests/zai_tests_common.hpp
  zend_abstract_interface/uri_normalization/tests/uri_normalization.cc
  zend_abstract_interface/value/tests/value.cc
Labels: c-extension

#1452 ZAI Symbols Interface
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/symbols/CMakeLists.txt
  zend_abstract_interface/symbols/api/README.md
  zend_abstract_interface/symbols/api/call.h
  zend_abstract_interface/symbols/api/class.h
  zend_abstract_interface/symbols/api/constant.h
  zend_abstract_interface/symbols/api/function.h
  zend_abstract_interface/symbols/api/local.h
  zend_abstract_interface/symbols/api/property.h
  zend_abstract_interface/symbols/call.c
  zend_abstract_interface/symbols/lookup.c
  zend_abstract_interface/symbols/symbols.h
  zend_abstract_interface/symbols/tests/CMakeLists.txt
  zend_abstract_interface/symbols/tests/api/README.md
  zend_abstract_interface/symbols/tests/api/call.cc
  zend_abstract_interface/symbols/tests/api/class.cc
  zend_abstract_interface/symbols/tests/api/constant.cc
  zend_abstract_interface/symbols/tests/api/function.cc
  zend_abstract_interface/symbols/tests/api/property.cc
  zend_abstract_interface/symbols/tests/call/internal.cc
  zend_abstract_interface/symbols/tests/call/user.cc
  zend_abstract_interface/symbols/tests/lookup/class.cc
  zend_abstract_interface/symbols/tests/lookup/constant.cc
  zend_abstract_interface/symbols/tests/lookup/function.cc
  zend_abstract_interface/symbols/tests/lookup/local/frame.cc
  zend_abstract_interface/symbols/tests/lookup/local/static.cc
  zend_abstract_interface/symbols/tests/lookup/property.cc
  zend_abstract_interface/symbols/tests/stubs/call/user/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/class/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/constant/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/function/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/local/frame/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/local/static/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/property/Stub.php
Labels: c-extension

#1464 Remove generator support on PHP 7
  ext/php7/php7/engine_hooks.c
  tests/ext/sandbox/generator.phpt
  tests/ext/sandbox/generator_not_supported.phpt
  tests/ext/sandbox/generator_with_exception.phpt
  tests/ext/sandbox/generator_with_return.phpt
  tests/ext/sandbox/generator_yield_from.phpt
Labels: 🐛 bug

#1463 Hard-code version in installer, remove --url option, rename it
  .circleci/config.yml
  Makefile
  datadog-setup.php
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/alpine/install.sh
  dockerfiles/verify_packages/centos/install.sh
  dockerfiles/verify_packages/debian/install.sh
  dockerfiles/verify_packages/installer/test_alpine_install_no_ext_curl_no_curl_cli.sh
  dockerfiles/verify_packages/installer/test_alpine_install_no_ext_curl_yes_curl_cli.sh
  dockerfiles/verify_packages/installer/test_alpine_no_ext_json.sh
  dockerfiles/verify_packages/installer/test_alpine_no_libcurl.sh
  dockerfiles/verify_packages/installer/test_alpine_no_libexecinfo.sh
  dockerfiles/verify_packages/installer/test_first_install.sh
  dockerfiles/verify_packages/installer/test_first_install_alpine.sh
  dockerfiles/verify_packages/installer/test_first_install_php_debug.sh
  dockerfiles/verify_packages/installer/test_first_install_php_debugzts.sh
  dockerfiles/verify_packages/installer/test_first_install_php_zts.sh
  dockerfiles/verify_packages/installer/test_fpm.sh
  dockerfiles/verify_packages/installer/test_install_add_missing_ini_settings.sh
  dockerfiles/verify_packages/installer/test_install_custom_installation_directory.sh
  dockerfiles/verify_packages/installer/test_install_custom_installation_root.sh
  dockerfiles/verify_packages/installer/test_install_non_root_user.sh
  dockerfiles/verify_packages/installer/test_install_subdir_from_file.sh
  dockerfiles/verify_packages/installer/test_install_subdir_from_url.sh
  dockerfiles/verify_packages/installer/test_install_subdir_from_version.sh
  dockerfiles/verify_packages/installer/test_profiler_install_disabled.sh
  dockerfiles/verify_packages/installer/test_profiler_install_enabled.sh
  dockerfiles/verify_packages/installer/test_uninstall.sh
  dockerfiles/verify_packages/installer/test_upgrade_from_legacy.sh
  dockerfiles/verify_packages/installer/test_upgrade_from_php_installer.sh
  dockerfiles/verify_packages/installer/utils.sh
  dockerfiles/verify_packages/verify_rpm_centos6.sh
  phpcs.xml
  tests/Integration/PHPInstallerTest.php
  tooling/bin/generate-installers.sh
Labels: 💔 breaking-change, cat:installation

#1466 Clear the root span when dropped
  ext/php5/span.c
  ext/php7/span.c
  ext/php8/span.c
  tests/ext/disabling_root_span_generation_at_runtime.phpt
Labels: 🐛 bug, c-extension, sev-1

#1475 Always emit NoopSpans if the tracer extension is disabled
  src/DDTrace/Tracer.php
  tests/Common/TracerTestTrait.php
  tests/Integration/CurrentContextAccess/CurrentContextAccessTest.php
  tests/Integrations/PCNTL/PCNTLTest.php
  tests/Integrations/PCNTL/scripts/access-tracer-after-fork.php
Labels: 🐛 bug

#1473 ZAI Sandbox Bailout
  zend_abstract_interface/sandbox/php5/sandbox.c
  zend_abstract_interface/sandbox/php7/sandbox.c
  zend_abstract_interface/sandbox/php8/sandbox.c
  zend_abstract_interface/sandbox/sandbox.h
  zend_abstract_interface/sandbox/tests/error.cc
  zend_abstract_interface/sandbox/tests/sandbox.cc
Labels: c-extension

#1476 fix dd_update_upstream_services on php5
  ext/php5/priority_sampling/priority_sampling.c
Labels: c-extension

#1467 fix symbols build and call issues
  zend_abstract_interface/symbols/call.c
  zend_abstract_interface/symbols/lookup.c
  zend_abstract_interface/symbols/symbols.h
  zend_abstract_interface/symbols/tests/CMakeLists.txt
  zend_abstract_interface/symbols/tests/call/closure.cc
  zend_abstract_interface/symbols/tests/lookup/local/static.cc
  zend_abstract_interface/symbols/tests/stubs/call/closure/Stub.php
  zend_abstract_interface/symbols/tests/stubs/lookup/local/static/Stub.php
Labels: c-extension

#1479 Tea: build once during development
  Makefile
Labels: c-extension

#1480 Ensure dropped spans are distinguishable from unfinished spans
  ext/php5/php5_4/engine_hooks.c
  ext/php5/span.c
  ext/php7/span.c
  ext/php8/span.c
  tests/ext/dropped_spans_have_negative_duration.phpt
Labels: c-extension

#1481 Fix Span::setError docblock
  src/DDTrace/Span.php
  src/api/Contracts/Span.php
Labels: cat:docs

#1465 Use symbols interface
  config.m4
  ext/php5/serializer.c
  ext/php7/php7/engine_hooks.c
  ext/php7/serializer.c
  ext/php8/php8/engine_hooks.c
  ext/php8/serializer.c
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/config/tests/decode.cc
  zend_abstract_interface/config/tests/default.cc
  zend_abstract_interface/config/tests/env.cc
  zend_abstract_interface/config/tests/ext_zai_config.cc
  zend_abstract_interface/config/tests/ext_zai_config.h
  zend_abstract_interface/config/tests/id.cc
  zend_abstract_interface/config/tests/ini.cc
  zend_abstract_interface/config/tests/zai_tests_common.hpp
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/exceptions/php5/exceptions.h
  zend_abstract_interface/exceptions/php7-8/exceptions.h
  zend_abstract_interface/exceptions/tests/CMakeLists.txt
  zend_abstract_interface/exceptions/tests/php5/exceptions.cc
  zend_abstract_interface/exceptions/tests/php7-8/exceptions.cc
  zend_abstract_interface/functions/CMakeLists.txt
  zend_abstract_interface/functions/functions.h
  zend_abstract_interface/functions/php5/functions.c
  zend_abstract_interface/functions/php7-8/functions.c
  zend_abstract_interface/functions/tests/CMakeLists.txt
  zend_abstract_interface/functions/tests/functions.cc
  zend_abstract_interface/functions/tests/stubs/basic.php
  zend_abstract_interface/headers/tests/headers.cc
  zend_abstract_interface/json/tests/json.cc
  zend_abstract_interface/methods/CMakeLists.txt
  zend_abstract_interface/methods/methods.h
  zend_abstract_interface/methods/php5/methods.c
  zend_abstract_interface/methods/tests/CMakeLists.txt
  zend_abstract_interface/methods/tests/methods.cc
  zend_abstract_interface/methods/tests/stubs/AbstractTest.php
  zend_abstract_interface/methods/tests/stubs/ExceptionTest.php
  zend_abstract_interface/methods/tests/stubs/Test.php
  zend_abstract_interface/properties/CMakeLists.txt
  zend_abstract_interface/properties/php5/properties.c
  zend_abstract_interface/properties/php5/properties.h
  zend_abstract_interface/properties/php7-8/properties.c
  zend_abstract_interface/properties/php7-8/properties.h
  zend_abstract_interface/properties/properties.h
  zend_abstract_interface/properties/tests/CMakeLists.txt
  zend_abstract_interface/properties/tests/properties.cc
  zend_abstract_interface/properties/tests/stubs/classes.php
  zend_abstract_interface/sandbox/tests/error.cc
  zend_abstract_interface/sandbox/tests/exception.cc
  zend_abstract_interface/sandbox/tests/sandbox.cc
  zend_abstract_interface/uri_normalization/tests/uri_normalization.cc
  zend_abstract_interface/value/tests/value.cc
Labels: c-extension

#1477 Setup: Error if profiling is given but unavailable
  datadog-setup.php
  dockerfiles/verify_packages/Makefile
  dockerfiles/verify_packages/installer/test_first_install_php_debug.sh
  dockerfiles/verify_packages/installer/test_first_install_php_debugzts.sh
  dockerfiles/verify_packages/installer/test_first_install_php_zts.sh
  dockerfiles/verify_packages/installer/test_profiler_install_unsupported.sh
  dockerfiles/verify_packages/installer/test_profiler_install_unsupported_debug.sh
  dockerfiles/verify_packages/installer/utils.sh
Labels: 🐛 bug, cat:installation

#1483 BGS shutdown/flush
  ext/php5/coms.c
  ext/php7/coms.c
  ext/php8/coms.c
Labels: c-extension
