Repository DataDog/dd-trace-php, pull requests merged in 2022-03, with the labels that each got.

#1517 Add Code Hotspots
  .circleci/config.yml
  Makefile
  config.m4
  ddtrace.sym
  ext/php7/php7/engine_hooks.c
  ext/php7/profiling_context.c
  ext/php7/profiling_context.h
  ext/php7/runtime.h
  ext/php7/serializer.c
  ext/php8/php8/engine_hooks.c
  ext/php8/profiling_context.c
  ext/php8/profiling_context.h
  ext/php8/runtime.h
  ext/php8/serializer.c
  tests/ext/profiling/runtime_id_01.phpt
  tests/ext/profiling/runtime_id_02.phpt
Labels: 🏆 enhancement, c-extension

#1537 Update profiling to v0.5.0 from v0.5.0-rc.2
  Makefile
Labels: c-extension

#1541 Update profiling to v0.5.1
  Makefile
Labels: 🏆 enhancement

#1543 Use latest ubuntu images in CI
  .circleci/config.yml
Labels: ci

#1553 Use 8.1.4 in development buster images
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/xfail_tests/8.1.list
  dockerfiles/ci/xfail_tests/README.md
Labels: ci
