Repository DataDog/dd-trace-php, pull requests merged in 2023-07, with the labels that each got.

#2141 refactor(profiling): apply clippy suggestions
  profiling/src/allocation.rs
  profiling/src/bindings/mod.rs
  profiling/src/capi.rs
  profiling/src/config.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
  profiling/src/timeline.rs
Labels: profiling

#2130 Add SpanData::peerServiceSources
  ext/ddtrace.c
  ext/ddtrace.h
  ext/ddtrace.stub.php
  ext/ddtrace_arginfo.h
  ext/span.h
  tests/ext/active_span.phpt
  tests/ext/peer_service_sources_not_serialized_when_set.phpt
  tests/ext/peer_service_sources_not_serialized_when_unset.phpt
  tests/ext/sandbox/span_clone.phpt
Labels: 🏆 enhancement, tracing

#2144 doc(profiling): make `phpinfo()` output more helpful
  profiling/src/lib.rs
  profiling/tests/phpt/phpinfo_02.phpt
Labels: profiling

#2135 Handle peer.service-related post-process in the extension
  ext/configuration.h
  ext/ddtrace.h
  ext/serializer.c
  tests/ext/peer_service_disabled_default.phpt
  tests/ext/peer_service_honor_user_value.phpt
  tests/ext/peer_service_remapping.phpt
  tests/ext/peer_service_sources_not_serialized_when_set.phpt
  tests/ext/peer_service_sources_not_serialized_when_unset.phpt
  tests/ext/peer_service_use_first_available_tag.phpt
  tests/ext/peer_service_wrong_values.phpt
Labels: 🏆 enhancement, c-extension, tracing

#2149 feat(profiling): Explicit shutdown allocation profiling on `fork()`
  profiling/src/allocation.rs
  profiling/src/pcntl.rs
Labels: profiling

#2156 ci: skip online tests due to flakiness
  .circleci/continue_config.yml
  dockerfiles/ci/xfail_tests/7.0.list
  dockerfiles/ci/xfail_tests/README.md
Labels: ci

#2118 Add Logs Correlation
  Makefile
  bridge/_files_integrations.php
  ext/configuration.h
  ext/ddtrace.c
  ext/ddtrace.stub.php
  ext/ddtrace_arginfo.h
  ext/integrations/integrations.c
  ext/integrations/integrations.h
  ext/random.c
  src/Integrations/Integrations/Laminas/LaminasIntegration.php
  src/Integrations/Integrations/LaravelQueue/LaravelQueueIntegration.php
  src/Integrations/Integrations/Logs/LogsIntegration.php
  tests/Common/BaseTestCase.php
  tests/Integrations/Logs/BaseLogsTest.php
  tests/Integrations/Logs/LaminasLogV2/LaminasLogV2Test.php
  tests/Integrations/Logs/MonologV1/MonologV1Test.php
  tests/Integrations/Logs/MonologV2/MonologV2Test.php
  tests/Integrations/Logs/MonologV3/MonologV3Test.php
  tests/Integrations/Lumen/V5_2/CommonScenariosTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/composer.json
  tests/ext/alias_logs.phpt
  tests/ext/retrieve_128_bit_trace_id.phpt
Labels: cat:log-injection

#1980 Fix memory leak in randomized tests
  .circleci/continue_config.yml
  dockerfiles/ci/buster/0001-Fix-GH-10611-fpm_env_init_main-leaks-environ.patch
  dockerfiles/ci/buster/build-php.sh
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/buster/php-8.0/Dockerfile
  dockerfiles/ci/xfail_tests/8.1.list
  dockerfiles/ci/xfail_tests/8.2.list
  dockerfiles/ci/xfail_tests/README.md
  dockerfiles/verify_packages/centos/install.sh
  tests/randomized/Makefile
  tests/randomized/analyze-results.php
  tests/randomized/generate-scenarios.php
  tests/randomized/lib/templates/docker-compose.template.yml
Labels: ci

#2160 Add invalid regex handling for sampling rules
  ext/priority_sampling/priority_sampling.c
  tests/ext/priority_sampling/invalid-regex-rule.phpt
  zend_abstract_interface/uri_normalization/CMakeLists.txt
  zend_abstract_interface/uri_normalization/uri_normalization.c
Labels: 🐛 bug, tracing

#2166 Evaluate the service name after the service mapping for a sampling decision
  ext/priority_sampling/priority_sampling.c
  tests/ext/priority_sampling/013-rule-service-mapped.phpt
Labels: 🐛 bug, tracing

#2164 Improve cargo build a bit
  .cargo-registry/.gitignore
  components-rs/build.rs
  config.m4
  docker-compose.yml
Labels: ci, profiling, tracing

#2157 fix(profiling): more accurate event timestamp for timeline
  profiling/src/allocation.rs
  profiling/src/profiling/mod.rs
  profiling/src/timeline.rs
Labels: profiling

#2168 perf(profiling): only wake every 10ms if PHP is serving a request
  profiling/build.rs
  profiling/src/lib.rs
  profiling/src/profiling/interrupts.rs
  profiling/src/profiling/mod.rs
  profiling/src/profiling/uploader.rs
Labels: cat:performance, profiling

#2177 (Legacy OpenTracing API) Check if the active span has a parent
  src/DDTrace/ScopeManager.php
  tests/Common/BaseTestCase.php
  tests/Unit/TracerTest.php
Labels: 🐛 bug

#1998 perf(profiling): speed up stack walking by using function run_time_cache
  Cargo.lock
  profiling/Cargo.toml
  profiling/benches/stack_walking.rs
  profiling/build.rs
  profiling/src/bindings/mod.rs
  profiling/src/lib.rs
  profiling/src/php_ffi.c
  profiling/src/php_ffi.h
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
  profiling/src/string_table/borrowed.rs
  profiling/src/string_table/bump_owned.rs
  profiling/src/string_table/mod.rs
  profiling/src/string_table/owned.rs
  profiling/tests/phpt/trampolines_01.phpt
Labels: ☠️ do-not-merge/WIP, Overhead, profiling

#2158 Add log levels
  cbindgen.toml
  components-rs/Cargo.toml
  components-rs/common.h
  components-rs/ddtrace.h
  components-rs/lib.rs
  components-rs/log.rs
  components/log/log.c
  components/log/log.h
  config.m4
  docker-compose.yml
  ext/auto_flush.c
  ext/circuit_breaker.c
  ext/comms_php.c
  ext/configuration.c
  ext/configuration.h
  ext/ddshared.c
  ext/ddtrace.c
  ext/dogstatsd_client.c
  ext/engine_hooks.c
  ext/excluded_modules.c
  ext/handlers_curl.c
  ext/handlers_curl_php7.c
  ext/hook/uhook.c
  ext/hook/uhook_legacy.c
  ext/integrations/integrations.c
  ext/ip_extraction.c
  ext/logging.c
  ext/logging.h
  ext/request_hooks.c
  ext/serializer.c
  ext/signals.c
  ext/span.c
  ext/startup_logging.c
  ext/telemetry.c
  ext/tracer_tag_propagation/tracer_tag_propagation.c
  tests/ext/sandbox/hook_function/03.phpt
  tests/ext/sandbox/hook_limit.phpt
  tests/ext/sandbox/hook_method/03.phpt
  tests/ext/sandbox/install_hook/hook_file.phpt
  tests/ext/sandbox/install_hook/replace_hook_args.phpt
  zend_abstract_interface/config/config_decode.c
Labels: tracing
