Repository DataDog/dd-trace-php, pull requests merged in 2023-06, with the labels that each got.

#2079 docs(profiling): add profiling Bits to readme
  profiling/README.md
  profiling/profiling_bits_211220.png
Labels: profiling

#2084 docs(tests): add ASAN section to randomised tests `README.md`
  tests/randomized/README.md
Labels: dev/testing, cat:docs

#2069 Fix error stack in span's resource when a AMQP connection error occurs
  src/Integrations/Integrations/AMQP/AMQPIntegration.php
  tests/Integrations/AMQP/AMQPTest.php
Labels: 🐛 bug, tracing

#2090 refactor(profiling): move allocation profiling to its own module
  profiling/src/allocation.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
Labels: profiling

#2094 (Laminas) Fix incorrect offset access
  src/Integrations/Integrations/Laminas/LaminasIntegration.php
Labels: 🐛 bug, tracing

#2091 Disable root span generation and removes orphans for Laravel Horizon
  ext/configuration.h
  src/Integrations/Integrations/Laravel/LaravelIntegration.php
  src/Integrations/Integrations/LaravelQueue/LaravelQueueIntegration.php
  src/Integrations/Integrations/Predis/PredisIntegration.php
  tests/Integrations/Laravel/V5_8/QueueTest.php
  tests/Integrations/Laravel/V8_x/QueueTest.php
Labels: 🐛 bug, cat:long-running-processes, tracing

#2092 Use span links in the RabbitMQ Integration
  src/Integrations/Integrations/AMQP/AMQPIntegration.php
  tests/Integrations/AMQP/AMQPTest.php
Labels: 🐛 bug, tracing

#2105 build: fix commit hashes in profiling release versions
  .circleci/continue_config.yml
Labels: 🐛 bug, ci

#1997 feat(profiling): timeline support (not compiled by default)
  .circleci/continue_config.yml
  profiling/Cargo.lock
  profiling/Cargo.toml
  profiling/build.rs
  profiling/src/bindings/mod.rs
  profiling/src/capi.rs
  profiling/src/config.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/src/timeline.rs
  profiling/tests/phpt/fibers_01.phpt
  profiling/tests/phpt/gc_collect_cycles_01.phpt
Labels: 🏆 enhancement, profiling

#2108 feat(profiling) compile timeline feature by default
  profiling/Cargo.toml
  profiling/src/lib.rs
Labels: profiling

#2107 Fix a memory leak when overriding default arguments in install_hook (PHP7.2-)
  ext/hook/uhook.c
  tests/ext/sandbox/install_hook/override_default_argument.phpt
Labels: 🐛 bug, c-extension

#2116 Link to docs in GitHub Issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: cat:docs

#2041 test(profiling): add stack walking benchmark
  .gitignore
  Cargo.lock
  profiling/Cargo.toml
  profiling/README.md
  profiling/benches/stack_walking.rs
  profiling/build.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
Labels: ci, cat:performance, profiling

#2120 ci: make sure core file is where it should be
  .circleci/continue_config.yml
Labels: ci

#2125 Add hint to remove sensitive information
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: cat:docs

#2111 feat(profiling): add endpoint counts
  profiling/src/profiling/mod.rs
  profiling/src/profiling/uploader.rs
Labels: 🏆 enhancement, profiling

#2129 Add git submodules operations to the CONTRIBUTING file
  CONTRIBUTING.md
Labels: dev/testing

#2127 build(profiling): bump indexmap to v2.0.0
  .github/CODEOWNERS
  Cargo.lock
  profiling/Cargo.toml
Labels: profiling

#2128 build(profiling): bump bindgen to 0.66.1
  Cargo.lock
  profiling/Cargo.toml
  profiling/build.rs
  profiling/src/allocation.rs
  profiling/src/bindings/mod.rs
Labels: profiling

#2119 feat(profiling): add file compilation to timeline
  profiling/src/bindings/mod.rs
  profiling/src/profiling/mod.rs
  profiling/src/timeline.rs
Labels: profiling

#2133 Run benchmarks only in profiling PRs
  .gitlab/benchmarks.yml
  tests/randomized/config/envs.php
Labels: ci

#2136 CI: don't run benchmarks on non profiling PRs
  .gitlab/benchmarks.yml
Labels: ci

#2137 fix: generate runtime-id on first request
  ext/ddtrace.c
Labels: 🐛 bug, profiling, tracing

#2139 ci: do not run benchmarks in not profiling related PRs
  .gitlab/benchmarks.yml
Labels: ci
