Repository DataDog/dd-trace-php, pull requests merged in 2023-04, with the labels that each got.

#2003 test(profiling) add a test to ensure we do not crash with fibers
  profiling/tests/phpt/fibers_01.phpt
Labels: dev/testing, profiling

#1992 Sync profiling version with tracer; append git sha1 to non-release builds
  .circleci/config.yml
  ext/version.h
  profiling/Cargo.lock
  profiling/Cargo.toml
  src/DDTrace/Tracer.php
  tooling/bin/generate-installers.sh
  tooling/bin/pecl-build
  tooling/ci/download-binary-php.sh
Labels: ci, profiling

#1989 Add file hooking to DDTrace\install_hook
  ext/ddtrace.c
  ext/hook/uhook.c
  ext/hook/uhook.h
  ext/hook/uhook.stub.php
  ext/hook/uhook_arginfo.h
  ext/hook/uhook_attributes.c
  ext/span.c
  tea/include/extension.h
  tea/src/extension.c
  tests/ext/sandbox/install_hook/hook_file.phpt
  tests/ext/sandbox/install_hook/hook_scoped_file.phpt
  tests/ext/sandbox/install_hook/testinclude.inc
  tests/ext/sandbox/install_hook/trace_file.phpt
  zend_abstract_interface/hook/hook.c
  zend_abstract_interface/hook/hook.h
  zend_abstract_interface/interceptor/php7/resolver.c
  zend_abstract_interface/interceptor/php8/interceptor.c
  zend_abstract_interface/interceptor/php8/resolver.c
  zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c
  zend_abstract_interface/interceptor/tests/resolver.cc
Labels: 🏆 enhancement, 🍏 core

#1991 Allow DDTrace\install_hook to take any callable
  ext/compatibility.h
  ext/ddtrace.c
  ext/hook/uhook.c
  ext/hook/uhook.stub.php
  ext/hook/uhook_arginfo.h
  tests/ext/sandbox/hook_function/hook_internal_fake_closure.phpt
  tests/ext/sandbox/install_hook/hook_internal_fake_closure.phpt
  tests/ext/sandbox/install_hook/trace_callable.phpt
  tests/ext/sandbox/install_hook/trace_closure.phpt
  tests/ext/sandbox/install_hook/trace_closure_from_callable.phpt
  tests/ext/sandbox/install_hook/trace_file.phpt
  zend_abstract_interface/hook/hook.c
  zend_abstract_interface/hook/hook.h
  zend_abstract_interface/interceptor/tests/resolver.cc
Labels: 🏆 enhancement, 🍏 core

#1984 feat(profiling) move upscaling to libdatadog
  profiling/Cargo.lock
  profiling/Cargo.toml
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/tests/phpt/fibers_01.phpt
  profiling/tests/phpt/preload_01.phpt
Labels: 🏆 enhancement, profiling

#1996 Add php-amqplib integration
  .circleci/config.yml
  Makefile
  bridge/_files_integrations.php
  docker-compose.yml
  ext/integrations/integrations.c
  ext/integrations/integrations.h
  src/Integrations/Integrations/AMQP/AMQPIntegration.php
  src/api/Tag.php
  tests/Integrations/AMQP/AMQPTest.php
  tests/Integrations/AMQP/scripts/receive.php
  tests/Integrations/AMQP/scripts/send.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/api/Unit/UserAvailableConstantsTest.php
  tests/composer.json
Labels: cat:new-integration, tracing

#2020 Increase the number of configuration entries in zai config
  zend_abstract_interface/config/config.h
Labels: 🐛 bug

#1951 feat: add config mode to `datadog-setup.php`
  datadog-setup.php
  tests/Integration/PHPInstallerTest.php
Labels: 🏆 enhancement, cat:configuration

#2028 Schedule reliability env deploys
  .gitlab-ci.yml
Labels: ci
