Repository DataDog/dd-trace-php, pull requests merged in 2023-08, with the labels that each got.

#2183 build: update Cargo.lock
  Cargo.lock
Labels: ci

#2182 fix: lifetime issue cached filename
  profiling/README.md
  profiling/src/php_ffi.c
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
  profiling/tests/phpt/jit_01.phpt
  profiling/tests/phpt/preload_01.phpt
  profiling/tests/phpt/preload_01_preload.php
Labels: 🐛 bug, profiling

#2169 feat(profiling): attach fiber's function name as a label
  profiling/build.rs
  profiling/src/php_ffi.c
  profiling/src/php_ffi.h
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
Labels: profiling

#2186 refactor(profiling): simplify string tables
  profiling/src/profiling/stalk_walking.rs
  profiling/src/string_table.rs
  profiling/src/string_table/borrowed.rs
  profiling/src/string_table/bump_owned.rs
  profiling/src/string_table/mod.rs
  profiling/src/string_table/owned.rs
Labels: profiling

#2187 perf(profiling): use u32 instead of usize for string table indices
  profiling/src/profiling/stalk_walking.rs
  profiling/src/string_table.rs
Labels: cat:performance, profiling

#2201 test: add `Datadog\Profiling\trigger_time_sample`
  .github/workflows/prof_correctness.yml
  profiling/Cargo.toml
  profiling/build.rs
  profiling/src/bindings/mod.rs
  profiling/src/capi.rs
  profiling/src/lib.rs
  profiling/src/php_ffi.c
  profiling/tests/correctness/strange_frames.json
  profiling/tests/correctness/strange_frames.php
Labels: dev/testing, profiling

#2176 Handle killed workers and change root span initialization in the integrations
  ext/compatibility.h
  ext/ddtrace.c
  ext/ddtrace.stub.php
  ext/ddtrace_arginfo.h
  src/Integrations/Integrations/CakePHP/CakePHPIntegration.php
  src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
  src/Integrations/Integrations/Laminas/LaminasIntegration.php
  src/Integrations/Integrations/Laravel/LaravelIntegration.php
  src/Integrations/Integrations/LaravelQueue/LaravelQueueIntegration.php
  src/Integrations/Integrations/Logs/LogsIntegration.php
  src/Integrations/Integrations/Lumen/LumenIntegration.php
  src/Integrations/Integrations/Nette/NetteIntegration.php
  src/Integrations/Integrations/Symfony/SymfonyIntegration.php
  src/Integrations/Integrations/Yii/YiiIntegration.php
  tests/Frameworks/Symfony/Version_5_2/.env
  tests/ext/force_flush_traces.phpt
Labels: 🐛 bug, tracing

#2208 build: Update to Rust 1.71 / Alpine 3.18
  Cargo.lock
  dockerfiles/ci/README.md
  dockerfiles/ci/alpine_compile_extension/Dockerfile
  dockerfiles/ci/alpine_compile_extension/docker-compose.yml
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/build-php.sh
  dockerfiles/ci/buster/docker-compose.yml
  dockerfiles/ci/centos/7/base.Dockerfile
  dockerfiles/ci/centos/7/docker-compose.yml
  dockerfiles/ci/centos/7/download-src.sh
  profiling/rust-toolchain.toml
Labels: ci

#2194 fix: add Symfony command's exception to the root span
  ext/span.c
  src/Integrations/Integrations/Symfony/SymfonyIntegration.php
  tests/Frameworks/Symfony/Version_4_4/src/Command/ThrowCommand.php
  tests/Frameworks/Symfony/Version_5_2/src/Command/ThrowCommand.php
  tests/Frameworks/Symfony/Version_6_2/src/Command/ThrowCommand.php
  tests/Integrations/CLI/Symfony/V4_4/CommonScenariosTest.php
  tests/Integrations/CLI/Symfony/V5_2/CommonScenariosTest.php
  tests/Integrations/CLI/Symfony/V6_2/CommonScenariosTest.php
  tests/ext/dd_trace_push_span_id_from_userland.phpt
Labels: 🐛 bug, tracing

#2205 Add `zai_option_str` and use it in config
  zend_abstract_interface/config/config.c
  zend_abstract_interface/config/config_ini.c
  zend_abstract_interface/config/config_ini.h
  zend_abstract_interface/zai_string/string.h
Labels: tracing

#2207 Use zai_str APIs a bit more
  zend_abstract_interface/config/config_ini.c
  zend_abstract_interface/config/tests/decode.cc
  zend_abstract_interface/interceptor/tests/interceptor.cc
  zend_abstract_interface/symbols/tests/call/internal.cc
  zend_abstract_interface/symbols/tests/lookup/class.cc
Labels: tracing

#2212 refactor: rename zai_str_equals_ci_cstr to zai_str_eq_ci_cstr
  ext/configuration.c
  zend_abstract_interface/zai_string/string.h
Labels: tracing

#2213 Fix duplicate `zai_option_str` definitions caused by bad auto-merge
  zend_abstract_interface/zai_string/string.h
Labels: tracing

#2215 fix(profiling): clippy lints
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/src/profiling/stalk_walking.rs
Labels: ci, profiling

#2216 style(profiler): use let-else syntax
  profiling/src/allocation.rs
  profiling/src/timeline.rs
Labels: ci, profiling

#2218 Not run syslog tests on outdated libsasl2-2.1.27
  dockerfiles/ci/xfail_tests/8.1.list
  dockerfiles/ci/xfail_tests/8.2.list
  dockerfiles/ci/xfail_tests/README.md
Labels: ci

#2219 Fix tests: allocate less TLS space by putting uhook HashTables into module globals
  ext/ddtrace.h
  ext/hook/uhook.c
  ext/serializer.c
Labels: ci

#2222 fix: flaky test
  tests/ext/force_flush_traces.phpt
Labels: dev/testing

#2214 Require `zai_str.ptr` to not be null
  profiling/build.rs
  profiling/src/bindings/ffi.rs
  profiling/src/bindings/mod.rs
  profiling/src/capi.rs
  profiling/src/config.rs
  profiling/src/profiling/stalk_walking.rs
  profiling/src/timeline.rs
  tea/include/common.h
  zend_abstract_interface/config/tests/id.cc
  zend_abstract_interface/env/tests/error.cc
  zend_abstract_interface/headers/tests/headers.cc
  zend_abstract_interface/hook/tests/internal/request.cc
  zend_abstract_interface/symbols/call.c
  zend_abstract_interface/zai_assert/zai_assert.h
  zend_abstract_interface/zai_string/CMakeLists.txt
  zend_abstract_interface/zai_string/string.h
Labels: profiling, tracing

#2220 build: finish hooking up Tea::Php using PhpConfig
  .circleci/continue_config.yml
  Makefile
  cmake/Modules/FindPhpConfig.cmake
  tea/CMakeLists.txt
  tea/cmake/TeaConfig.cmake.in
  tests/tea/profiling/CMakeLists.txt
  zend_abstract_interface/CMakeLists.txt
  zend_abstract_interface/config/CMakeLists.txt
  zend_abstract_interface/env/CMakeLists.txt
  zend_abstract_interface/env/tests/sapi.cc
  zend_abstract_interface/exceptions/CMakeLists.txt
  zend_abstract_interface/headers/CMakeLists.txt
  zend_abstract_interface/hook/CMakeLists.txt
  zend_abstract_interface/interceptor/CMakeLists.txt
  zend_abstract_interface/json/CMakeLists.txt
  zend_abstract_interface/sandbox/CMakeLists.txt
  zend_abstract_interface/symbols/CMakeLists.txt
  zend_abstract_interface/uri_normalization/CMakeLists.txt
  zend_abstract_interface/zai_assert/CMakeLists.txt
  zend_abstract_interface/zai_string/CMakeLists.txt
Labels: cat:devtools

#2210 Bump libdatadog to `v3.0.0`
  Cargo.lock
  profiling/Cargo.toml
  profiling/src/profiling/uploader.rs
Labels: profiling

#2217 Add `zai_string` and use it in `zai_config`
  config.m4
  profiling/build.rs
  profiling/src/bindings/mod.rs
  profiling/src/capi.rs
  profiling/src/php_ffi.c
  profiling/src/profiling/stalk_walking.rs
  profiling/src/timeline.rs
  zend_abstract_interface/config/CMakeLists.txt
  zend_abstract_interface/env/CMakeLists.txt
  zend_abstract_interface/env/env.h
  zend_abstract_interface/headers/CMakeLists.txt
  zend_abstract_interface/symbols/CMakeLists.txt
  zend_abstract_interface/symbols/lookup.c
  zend_abstract_interface/zai_string/CMakeLists.txt
  zend_abstract_interface/zai_string/string.c
  zend_abstract_interface/zai_string/string.h
  zend_abstract_interface/zai_string/tests/CMakeLists.txt
  zend_abstract_interface/zai_string/tests/strings.cc
Labels: profiling, tracing

#2236 fix: PHP7 compatibility in logs correlation
  src/Integrations/Integrations/Logs/LogsIntegration.php
Labels: 🐛 bug, cat:log-injection
