Repository DataDog/dd-trace-php, pull requests merged in 2023-05, with the labels that each got.

#2036 feat(profiling) raise sampling distance for allocation profiling
  profiling/src/lib.rs
Labels: 🏆 enhancement, profiling

#2034 test(profiling) add stack walking test
  .circleci/config.yml
  profiling/Cargo.toml
  profiling/README.md
  profiling/build.rs
  profiling/src/php_ffi.c
  profiling/src/php_ffi.h
  profiling/src/profiling/stalk_walking.rs
Labels: profiling

#2039 fix(profiling): crashes when allocation sampling occurs in certain places
  ext/handlers_curl_php7.c
  ext/span.c
  tests/randomized/config/envs.php
Labels: cat:app-crash, profiling

#2031 Add SQLSRV Integration
  .circleci/config.yml
  Makefile
  bridge/_files_integrations.php
  docker-compose.yml
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/build-extensions.sh
  dockerfiles/ci/buster/php-7.0/Dockerfile
  dockerfiles/ci/buster/php-7.1/Dockerfile
  dockerfiles/ci/buster/php-7.2/Dockerfile
  dockerfiles/ci/buster/php-7.3/Dockerfile
  dockerfiles/ci/buster/php-7.4/Dockerfile
  dockerfiles/ci/buster/php-8.0/Dockerfile
  dockerfiles/ci/buster/php-8.1/Dockerfile
  dockerfiles/ci/buster/php-8.2/Dockerfile
  ext/integrations/integrations.c
  ext/integrations/integrations.h
  src/Integrations/Integrations/SQLSRV/SQLSRVIntegration.php
  src/api/Tag.php
  tests/Integrations/SQLSRV/SQLSRVTest.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/api/Unit/UserAvailableConstantsTest.php
Labels: cat:new-integration, tracing

#2026 Add Laravel Queue Integration with Span Links
  .circleci/config.yml
  bridge/_files_integrations.php
  ext/ddtrace.c
  ext/ddtrace.h
  ext/ddtrace.stub.php
  ext/ddtrace_arginfo.h
  ext/integrations/integrations.c
  ext/integrations/integrations.h
  ext/serializer.c
  ext/span.c
  ext/span.h
  src/Integrations/Integrations/IntegrationsLoader.php
  src/Integrations/Integrations/Laravel/LaravelIntegration.php
  src/Integrations/Integrations/LaravelQueue/LaravelQueueIntegration.php
  src/api/Tag.php
  tests/Common/SpanAssertionTrait.php
  tests/Common/SpanChecker.php
  tests/Common/TracerTestTrait.php
  tests/Frameworks/Laravel/Version_5_7/app/Http/Controllers/QueueTestController.php
  tests/Frameworks/Laravel/Version_5_7/app/Jobs/SendVerificationEmail.php
  tests/Frameworks/Laravel/Version_5_7/app/Providers/AppServiceProvider.php
  tests/Frameworks/Laravel/Version_5_7/composer.json
  tests/Frameworks/Laravel/Version_5_7/database/migrations/2014_10_12_000000_create_users_table.php
  tests/Frameworks/Laravel/Version_5_7/database/migrations/2023_04_27_095138_create_failed_jobs_table.php
  tests/Frameworks/Laravel/Version_5_7/database/migrations/2023_04_27_095151_create_jobs_table.php
  tests/Frameworks/Laravel/Version_5_7/routes/web.php
  tests/Frameworks/Laravel/Version_5_8/app/Http/Controllers/QueueTestController.php
  tests/Frameworks/Laravel/Version_5_8/app/Jobs/SendVerificationEmail.php
  tests/Frameworks/Laravel/Version_5_8/app/Providers/AppServiceProvider.php
  tests/Frameworks/Laravel/Version_5_8/composer.json
  tests/Frameworks/Laravel/Version_5_8/database/migrations/2014_10_12_000000_create_users_table.php
  tests/Frameworks/Laravel/Version_5_8/database/migrations/2023_04_27_082843_create_failed_jobs_table.php
  tests/Frameworks/Laravel/Version_5_8/database/migrations/2023_04_27_083019_create_jobs_table.php
  tests/Frameworks/Laravel/Version_5_8/routes/web.php
  tests/Frameworks/Laravel/Version_8_x/app/Http/Controllers/QueueTestController.php
  tests/Frameworks/Laravel/Version_8_x/app/Jobs/SendVerificationEmail.php
  tests/Frameworks/Laravel/Version_8_x/app/Providers/AppServiceProvider.php
  tests/Frameworks/Laravel/Version_8_x/composer.json
  tests/Frameworks/Laravel/Version_8_x/database/migrations/2014_10_12_000000_create_users_table.php
  tests/Frameworks/Laravel/Version_8_x/database/migrations/2023_04_20_113530_create_job_batches_table.php
  tests/Frameworks/Laravel/Version_8_x/database/migrations/2023_04_21_090909_create_jobs_table.php
  tests/Frameworks/Laravel/Version_8_x/routes/web.php
  tests/Integrations/Laravel/V5_7/QueueTest.php
  tests/Integrations/Laravel/V5_8/QueueTest.php
  tests/Integrations/Laravel/V8_x/InternalExceptionsTest.php
  tests/Integrations/Laravel/V8_x/QueueTest.php
  tests/Sapi/PhpApache/PhpApache.php
  tests/Unit/Integrations/IntegrationsLoaderTest.php
  tests/WebServer.php
  tests/api/Unit/UserAvailableConstantsTest.php
  tests/ext/active_span.phpt
  tests/ext/dd_trace_span_data_get_link.phpt
  tests/ext/dd_trace_span_data_serialization_with_links.phpt
  tests/ext/sandbox-regression/limiter_reset_flush_with_open_spans.phpt
  tests/ext/sandbox/span_clone.phpt
  zend_abstract_interface/json/json.c
  zend_abstract_interface/json/json.h
Labels: 🏆 enhancement, cat:new-integration, tracing

#2044 fix(ci) switch to static binary for `jq`
  .circleci/config.yml
Labels: ci

#2037 Fix #2030: Segmentation fault with autoloaders bailing out
  tests/ext/sandbox-regression/class_resolver_bailout_hook.phpt
  zend_abstract_interface/interceptor/php7/interceptor.c
  zend_abstract_interface/interceptor/php7/resolver.c
  zend_abstract_interface/interceptor/php8/interceptor.c
  zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c
Labels: cat:app-crash, tracing

#2043 fix(profiling): fix panic by explicitly depending on `ext-json`
  profiling/Cargo.lock
  profiling/Cargo.toml
  profiling/src/bindings/mod.rs
  profiling/src/config.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  zend_abstract_interface/json/json.c
  zend_abstract_interface/json/json.h
Labels: profiling

#2048 fix(ci) this will update the container used for `package extension`
  .circleci/config.yml
Labels: ci

#2055 build: delete unused C components
  components/CMakeLists.txt
  components/arena/CMakeLists.txt
  components/arena/arena.c
  components/arena/arena.h
  components/arena/tests/CMakeLists.txt
  components/arena/tests/arena.cc
  components/channel/CMakeLists.txt
  components/channel/channel.c
  components/channel/channel.h
  components/channel/tests/CMakeLists.txt
  components/channel/tests/channel.cc
  components/log/CMakeLists.txt
  components/log/log.c
  components/log/log.h
  components/log/tests/CMakeLists.txt
  components/log/tests/log.cc
  components/queue/CMakeLists.txt
  components/queue/queue.c
  components/queue/queue.h
  components/queue/tests/CMakeLists.txt
  components/queue/tests/queue.cc
  components/time/CMakeLists.txt
  components/time/tests/CMakeLists.txt
  components/time/tests/time.cc
  components/time/time.c
  components/time/time.h
  dockerfiles/ci/buster/Dockerfile
Labels: dev/testing, ci

#2057 Reduce Laravel queues' tests flakiness
  dockerfiles/services/request-replayer/src/index.php
  tests/Integrations/Laravel/V5_8/QueueTest.php
  tests/Integrations/Laravel/V8_x/QueueTest.php
Labels: dev/testing, ci

#2059 fix(datadog-setup.php): remove return types for compatibility with PHP 5
  datadog-setup.php
Labels: cat:installation

#2060 build: downsize resource class for profiling jobs
  .circleci/config.yml
Labels: ci

#2050 feat: add environment variable mapping to datadog-setup.php
  .circleci/config.yml
  composer.json
  datadog-setup.php
  phpcs.xml
  tests/Integration/PHPInstallerTest.php
Labels: 🏆 enhancement, cat:configuration

#2071 build: pin guzzlehttp/promises to ^1.5.3
  tests/composer.json
Labels: dev/testing, ci

#2072 Work around fiber->execute_data only being correct upon yielding
  dockerfiles/ci/xfail_tests/8.1.list
  dockerfiles/ci/xfail_tests/8.2.list
  dockerfiles/ci/xfail_tests/README.md
  ext/handlers_fiber.c
  ext/span.h
Labels: 🐛 bug

#2061 build: update ubuntu images used in circleci
  .circleci/config.yml
  tests/randomized/generate-scenarios.php
Labels: ci

#2073 Update removed methods used in Guzzle V6 & V7 test suites
  tests/Integrations/Guzzle/V6/guzzle_in_distributed_web_request.php
  tests/composer.json
Labels: dev/testing

#2065 build(ci): execute workflows based on which files are modified
  .circleci/config.yml
  .circleci/continue_config.yml
Labels: ci

#2038 feat(profiling): GA allocation profiling
  datadog-setup.php
  profiling/src/config.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/tests/phpt/fibers_01.phpt
  profiling/tests/phpt/gc_mem_caches_01.phpt
  profiling/tests/phpt/phpinfo_01.phpt
  profiling/tests/phpt/phpinfo_ini_01.phpt
  profiling/tests/phpt/preload_01.phpt
  tests/randomized/analyze-results.php
Labels: 🏆 enhancement, profiling
