Repository DataDog/dd-trace-php, pull requests merged in 2023-12, with the labels that each got.

#2405 fix(ci) fix xdebug
  .circleci/continue_config.yml
  dockerfiles/ci/xfail_tests/8.1.list
  dockerfiles/ci/xfail_tests/8.2.list
Labels: ci

#2406 Always serialize schemas when available
  appsec/src/extension/commands/client_init.c
  appsec/src/extension/configuration.h
  appsec/src/helper/client.cpp
  appsec/src/helper/client.hpp
  appsec/src/helper/engine.cpp
  appsec/src/helper/engine.hpp
  appsec/src/helper/network/proto.hpp
  appsec/src/helper/subscriber/base.hpp
  appsec/src/helper/subscriber/waf.cpp
  appsec/src/helper/subscriber/waf.hpp
  appsec/tests/extension/api_security_env_variables.phpt
  appsec/tests/extension/rinit_rshutdown_basic.phpt
  appsec/tests/helper/broker_test.cpp
  appsec/tests/helper/client_test.cpp
  appsec/tests/helper/waf_test.cpp
Labels: tracing, area:asm

#2408 Add macrobenchmark runs
  .gitlab/benchmarks.yml
Labels: ci

#2379 Add http.route to CodeIgniter
  src/Integrations/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
  tests/Frameworks/CodeIgniter/Version_2_2/application/config/routes.php
  tests/Frameworks/CodeIgniter/Version_2_2/application/controllers/parameterized.php
  tests/Integrations/CodeIgniter/V2_2/CommonScenariosTest.php
  tests/Integrations/CodeIgniter/V2_2/ExitTest.php
  tests/Integrations/CodeIgniter/V2_2/NoCI_ControllertTest.php
Labels: cat:integration, tracing

#2418 CI: Handle latest Alpine 3.19 image
  dockerfiles/verify_packages/alpine/install.sh
Labels: ci

#2417 Update datadog-setup.php
  datadog-setup.php
Labels: 🐛 bug, cat:installation

#2424 [WordPress] Avoid Setting User ID When Unauthenticated
  src/Integrations/Integrations/WordPress/V2/WordPressIntegrationLoader.php
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_callbacks_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v5_5.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_callbacks_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v5_9.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_callbacks_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v6_1.common_scenarios_test.test_scenario_get_with_view.json
Labels: 🐛 bug, area:asm

#2385 feat(profiling): allow to enable all experimental features
  .github/workflows/prof_correctness.yml
  profiling/src/config.rs
  profiling/src/lib.rs
  profiling/src/profiling/mod.rs
  profiling/tests/phpt/phpinfo_06.phpt
  profiling/tests/phpt/phpinfo_07.phpt
Labels: 🏆 enhancement, profiling

#2420 ci(profiling): run prof-correctness nightly
  .github/workflows/prof_correctness.yml
Labels: ci, profiling

#2409 Fix analytics.event override
  ext/serializer.c
  tests/OpenTelemetry/Integration/API/TracerTest.php
Labels: 🐛 bug, tracing, cat:opentelemetry

#2437 Add Symfony 7.0 test suite
  Makefile
  tests/Frameworks/Symfony/Version_7_0/.env
  tests/Frameworks/Symfony/Version_7_0/.gitignore
  tests/Frameworks/Symfony/Version_7_0/bin/console
  tests/Frameworks/Symfony/Version_7_0/compose.override.yaml
  tests/Frameworks/Symfony/Version_7_0/compose.yaml
  tests/Frameworks/Symfony/Version_7_0/composer.json
  tests/Frameworks/Symfony/Version_7_0/config/bundles.php
  tests/Frameworks/Symfony/Version_7_0/config/packages/cache.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/doctrine.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/doctrine_migrations.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/framework.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/monolog.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/routing.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/security.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/test/framework.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/test/twig.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/twig.yaml
  tests/Frameworks/Symfony/Version_7_0/config/packages/validator.yaml
  tests/Frameworks/Symfony/Version_7_0/config/preload.php
  tests/Frameworks/Symfony/Version_7_0/config/routes.yaml
  tests/Frameworks/Symfony/Version_7_0/config/routes/attributes.yaml
  tests/Frameworks/Symfony/Version_7_0/config/routes/framework.yaml
  tests/Frameworks/Symfony/Version_7_0/config/services.yaml
  tests/Frameworks/Symfony/Version_7_0/migrations/.gitignore
  tests/Frameworks/Symfony/Version_7_0/migrations/Version20230707083454.php
  tests/Frameworks/Symfony/Version_7_0/migrations/Version20231227143831.php
  tests/Frameworks/Symfony/Version_7_0/public/index.php
  tests/Frameworks/Symfony/Version_7_0/src/Command/ThrowCommand.php
  tests/Frameworks/Symfony/Version_7_0/src/Controller/.gitignore
  tests/Frameworks/Symfony/Version_7_0/src/Controller/CommonScenariosController.php
  tests/Frameworks/Symfony/Version_7_0/src/Controller/LoginController.php
  tests/Frameworks/Symfony/Version_7_0/src/Controller/RegistrationController.php
  tests/Frameworks/Symfony/Version_7_0/src/Entity/.gitignore
  tests/Frameworks/Symfony/Version_7_0/src/Entity/User.php
  tests/Frameworks/Symfony/Version_7_0/src/Form/RegistrationFormType.php
  tests/Frameworks/Symfony/Version_7_0/src/Kernel.php
  tests/Frameworks/Symfony/Version_7_0/src/Repository/.gitignore
  tests/Frameworks/Symfony/Version_7_0/src/Repository/UserRepository.php
  tests/Frameworks/Symfony/Version_7_0/templates/base.html.twig
  tests/Frameworks/Symfony/Version_7_0/templates/login/index.html.twig
  tests/Frameworks/Symfony/Version_7_0/templates/registration/register.html.twig
  tests/Frameworks/Symfony/Version_7_0/templates/twig_template.html.twig
  tests/Integrations/CLI/Symfony/V7_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V6_2/AutomatedLoginEventsTest.php
  tests/Integrations/Symfony/V7_0/AutomatedLoginEventsTest.php
  tests/Integrations/Symfony/V7_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V7_0/ConsoleCommandTest.php
  tests/Integrations/Symfony/V7_0/TraceSearchConfigTest.php
  tests/phpunit.xml
Labels: tracing
