Repository DataDog/dd-trace-php, pull requests merged in 2024-10, with the labels that each got.

#2870 fix(mongodb): Deprecated exception in v1.20+
  src/DDTrace/Integrations/MongoDB/MongoDBIntegration.php
Labels: 🐛 bug, cat:integration

#2874 Fix failing appsec tests on pipeline
  .circleci/continue_config.yml
  appsec/src/extension/helper_process.c
  appsec/src/extension/helper_process.h
  appsec/tests/extension/report_backtrace_01.phpt
  appsec/tests/extension/report_backtrace_05.phpt
  appsec/tests/extension/root_span_add_tag.phpt
Labels: tracing, area:asm

#2879 Revert unintended change in extension_no_static_tls.phpt
  tests/ext/extension_no_static_tls.phpt
  tests/ext/live-debugger/exception-replay_001.phpt
  tests/ext/live-debugger/exception-replay_002.phpt
Labels: tracing

#2888 AppSec: improve behavior with empty DD_SERVICE/DD_ENV
  appsec/src/extension/commands/client_init.c
  appsec/src/extension/commands/config_sync.c
  appsec/src/extension/ddappsec.c
  appsec/src/extension/request_lifecycle.c
  appsec/src/helper/client.cpp
  appsec/src/helper/remote_config/listeners/asm_features_listener.hpp
  appsec/src/helper/service_config.hpp
  appsec/src/helper/subscriber/waf.cpp
  appsec/tests/integration/src/main/groovy/com/datadog/appsec/php/mock_agent/TracesV04Handler.groovy
  appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/RemoteConfigTests.groovy
  appsec/tests/integration/src/test/www/base/public/change_env.php
Labels: tracing, area:asm

#2876 build(profiling): bump to Rust 1.76
  profiling/Cargo.toml
  profiling/rust-toolchain.toml
  profiling/src/profiling/uploader.rs
Labels: profiling

#2897 [ASM] Update event obfuscation regex
  appsec/src/extension/configuration.h
Labels: tracing, area:asm

#2900 Fix abort() call on appsec helper unload
  appsec/src/helper/main.cpp
  appsec/src/helper/runner.cpp
  appsec/src/helper/runner.hpp
Labels: tracing, area:asm

#2894 ci(profiling) fix actions cache
  .github/workflows/prof_asan.yml
  .github/workflows/prof_correctness.yml
Labels: ci, profiling

#2908 Fix crash when yielding from generators are destroyed
  zend_abstract_interface/interceptor/php8/interceptor.c
Labels: crashtracker-identified
