Repository DataDog/dd-trace-php, pull requests merged in 2024-09, with the labels that each got.

#2845 ci(profiling): Add PHP 8.0 to correctness tests
  .github/workflows/prof_correctness.yml
Labels: ci, profiling

#2854 Fix improper symbol exports in appsec ext/helper
  appsec/cmake/cond_flag.cmake
  appsec/cmake/extension.cmake
  appsec/cmake/helper.cmake
  appsec/src/extension/ddappsec.version
  appsec/src/helper/helper.version
Labels: area:asm

#2849 fix(otel): Missing `addLink` method and Fiber handling
  Makefile
  src/DDTrace/OpenTelemetry/Context.php
  src/DDTrace/OpenTelemetry/Span.php
  tests/OpenTelemetry/Integration/Context/Fiber/FiberTest.php
  tests/OpenTelemetry/Integration/Context/Fiber/test_context_switching_ffi_observer.phpt
  tests/OpenTelemetry/Integration/Context/Fiber/test_context_switching_ffi_observer_registered_on_startup.phpt
  tests/OpenTelemetry/Integration/SDK/SpanBuilderTest.php
  tests/OpenTelemetry/composer-1.json
  tests/OpenTelemetry/composer-beta.json
  tests/OpenTelemetry/composer.json
  tests/phpunit.xml
Labels: 🐛 bug, cat:opentelemetry

#2855 Remove gid from socket/lock path of helper
  appsec/src/extension/helper_process.c
  appsec/tests/extension/inc/mock_helper.php
Labels: tracing, area:asm

#2861 docs: Remove pre-beta state
  CONTRIBUTING.md
Labels: cat:docs

#2859 Fix orderly helper appsec shutdown
  appsec/src/helper/main.cpp
  appsec/src/helper/network/acceptor.cpp
  appsec/src/helper/runner.cpp
  appsec/src/helper/runner.hpp
  appsec/tests/integration/src/test/groovy/com/datadog/appsec/php/integration/Apache2FpmTests.groovy
Labels: tracing, area:asm

#2863 Disable kubernetes injection tests
  .gitlab-ci.yml
Labels: ci
