Repository DataDog/dd-trace-php, pull requests merged in 2024-12, with the labels that each got.

#2978 ci: update xdebug/swoole
  dockerfiles/ci/alpine_compile_extension/Dockerfile
  dockerfiles/ci/alpine_compile_extension/docker-compose.yml
  dockerfiles/ci/bookworm/build-extensions.sh
  dockerfiles/ci/buster/build-extensions.sh
  zend_abstract_interface/jit_utils/jit_blacklist.c
Labels: ci

#2990 fix(profiling): mismatch in utf8 handling
  Cargo.lock
  profiling/src/timeline.rs
Labels: profiling

#3002 Restart usleep() on EINTR
  appsec/src/extension/network.c
Labels: tracing, area:asm

#3013 Fix flaky appsec tests
  tests/ext/telemetry/integration_filesystem_01.phpt
  tests/ext/telemetry/integration_filesystem_02.phpt
  tests/ext/telemetry/integration_filesystem_03.phpt
  tests/ext/telemetry/integration_filesystem_04.phpt
Labels: area:asm
