Repository DataDog/dd-trace-php, pull requests merged in 2024-05, with the labels that each got.

#2647 Add all asm headers on user events
  appsec/src/extension/tags.c
  appsec/tests/extension/headers_collection_01.phpt
  appsec/tests/extension/headers_collection_02.phpt
  appsec/tests/extension/headers_collection_03.phpt
  appsec/tests/extension/headers_collection_04.phpt
  appsec/tests/extension/headers_collection_05.phpt
  appsec/tests/extension/headers_collection_06.phpt
  appsec/tests/extension/headers_collection_07.phpt
  appsec/tests/extension/headers_collection_08.phpt
  appsec/tests/extension/headers_collection_09.phpt
  appsec/tests/extension/headers_collection_10.phpt
  appsec/tests/extension/headers_collection_11.phpt
  appsec/tests/extension/headers_collection_12.phpt
  appsec/tests/extension/headers_collection_13.phpt
Labels: tracing, area:asm

#2650 fix(bench): Pass sources path as an env var to the PHP process
  Makefile
Labels: 🐛 bug, cat:benchmarks

#2654 ci(profiling) notify if correctness job fails on master
  .github/workflows/prof_correctness.yml
Labels: profiling

#2655 Mark Laravel Octane requests as `laravel.request`
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  tests/Integrations/Laravel/Octane/CommonScenariosTest.php
Labels: 💔 breaking-change, cat:integration, major-release

#2657 refactor(profiling): use `php_version` when available
  profiling/src/allocation.rs
  profiling/src/bindings/mod.rs
  profiling/src/lib.rs
  profiling/src/php_ffi.c
Labels: profiling, tracing

#2670 fix(ci): Install `php` during plesk installer test
  dockerfiles/verify_packages/installer/test_install_on_plesk.sh
Labels: 🐛 bug, ci

#2666 fix: Web Tests Errors Detection
  src/DDTrace/Integrations/Laravel/LaravelIntegration.php
  src/DDTrace/Integrations/WordPress/WordPressIntegrationLoader.php
  src/DDTrace/OpenTelemetry/Span.php
  tests/Common/SpanAssertion.php
  tests/Common/SpanChecker.php
  tests/Integrations/Elasticsearch/V1/ElasticSearchIntegrationTest.php
  tests/Integrations/Elasticsearch/V8/ElasticSearchIntegrationTest.php
  tests/Integrations/Laravel/Octane/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_7/CommonScenariosTest.php
  tests/Integrations/Laravel/V5_8/CommonScenariosTest.php
  tests/Integrations/Laravel/V8_x/CommonScenariosTest.php
  tests/Integrations/Laravel/V9_x/CommonScenariosTest.php
  tests/Integrations/Symfony/V4_4/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_0/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_1/CommonScenariosTest.php
  tests/Integrations/Symfony/V5_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V6_2/CommonScenariosTest.php
  tests/Integrations/Symfony/V7_0/CommonScenariosTest.php
  tests/OpenTelemetry/Integration/API/BaggageTest.php
  tests/OpenTelemetry/Integration/InteroperabilityTest.php
  tests/WebServer.php
  tests/snapshots/tests.integrations.laravel.v10_x.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.laravel.v11_x.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.laravel.v5_7.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.laravel.v5_7.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.laravel.v5_7.common_scenarios_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.laravel.v5_7.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.laravel.v5_7.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.laravel.v5_8.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.laravel.v5_8.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.laravel.v5_8.common_scenarios_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.laravel.v5_8.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.laravel.v5_8.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.laravel.v8_x.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.laravel.v8_x.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.laravel.v8_x.common_scenarios_test.test_scenario_get_to_missing_route.json
  tests/snapshots/tests.integrations.laravel.v8_x.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.laravel.v8_x.common_scenarios_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.laravel.v9_x.common_scenarios_test.test_scenario_get_dynamic_route.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_callbacks_test.test_scenario_get_with_view.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_return_string.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_exception.json
  tests/snapshots/tests.integrations.word_press.v4_8.common_scenarios_test.test_scenario_get_with_view.json
Labels: 🐛 bug, dev/testing

#2676 Fix alpine:latest verify job
  dockerfiles/verify_packages/alpine/install.sh
Labels: ci

#2682 Fix exception profiling in Generator->throw()
  ext/handlers_api.c
  ext/handlers_api.h
  package.xml
  profiling/src/bindings/mod.rs
  profiling/src/exception.rs
  profiling/src/php_ffi.h
  profiling/tests/phpt/exceptions_generator_throw.phpt
Labels: 🐛 bug, cat:app-crash, profiling
