Repository DataDog/dd-trace-php, pull requests merged in 2025-09, with the labels that each got.

#3397 feat(ci): enable performance SLO change tracking
  .github/chainguard/gitlab-ci-slo-change-tracking.sts.yaml
  .gitlab/benchmarks.yml
  .gitlab/bp-runner.fail-on-breach.yml
Labels: ci

#3402 Fix possible crash with freed proc resource
  ext/integrations/exec_integration.c
Labels: crashtracker-identified

#3417 fix(prof) missing line numbers
  profiling/src/profiling/stack_walking.rs
Labels: profiling, tracing
