Repository DataDog/dd-trace-php, pull requests merged in 2025-01, with the labels that each got.

#2984 Supported php84
  datadog-setup.php
Labels: ci, cat:installation

#3004 feat: Kafka Integration
  .circleci/continue_config.yml
  .gitlab/ci-images.yml
  Makefile
  config.m4
  config.w32
  docker-compose.yml
  dockerfiles/ci/alpine/Dockerfile
  dockerfiles/ci/alpine_compile_extension/base.Dockerfile
  dockerfiles/ci/buster/Dockerfile
  dockerfiles/ci/buster/build-extensions.sh
  dockerfiles/ci/centos/7/base.Dockerfile
  ext/compatibility.h
  ext/configuration.h
  ext/handlers_internal.c
  ext/handlers_kafka.c
  ext/integrations/integrations.c
  ext/integrations/integrations.h
  src/DDTrace/Integrations/Kafka/KafkaIntegration.php
  src/api/Tag.php
  src/api/Type.php
  src/ddtrace_php_api.stubs.php
  tests/Integrations/Kafka/KafkaTest.php
  tests/Integrations/Kafka/scripts/consumer-highlevel.php
  tests/Integrations/Kafka/scripts/consumer-lowlevel.php
  tests/Integrations/Kafka/scripts/producer.php
  tests/Integrations/Kafka/scripts/producerv.php
  tests/api/Unit/UserAvailableConstantsTest.php
  tests/snapshots/tests.integrations.kafka_test.test_distributed_tracing_high_level_producer.json
  tests/snapshots/tests.integrations.kafka_test.test_span_links_high_level_consumer.json
  tests/snapshots/tests.integrations.kafka_test.test_span_links_high_level_producer.json
  tests/snapshots/tests.integrations.kafka_test.test_span_links_low_level_consumer.json
  tests/snapshots/tests.integrations.kafka_test.test_span_links_low_level_producer.json
Labels: 🎉 new-integration

#3008 appsec: fix recv/writev calls in the face of interrupting signals
  appsec/src/extension/commands_helpers.c
  appsec/src/extension/network.c
  appsec/src/extension/network.h
Labels: tracing, area:asm

#3016 fix: PHP Installer Tests
  tests/Integration/PHPInstallerTest.php
Labels: dev/testing

#3018 [ASM] Workaround for boost download issues
  appsec/CMakeLists.txt
Labels: area:asm

#2981 Fix PHP 8.4 deprecations
  src/DDTrace/Integrations/AMQP/AMQPIntegration.php
  src/DDTrace/Integrations/CodeIgniter/V2/CodeIgniterIntegration.php
  src/DDTrace/Integrations/Logs/LogsIntegration.php
  src/DDTrace/Integrations/WordPress/WordPressIntegrationLoader.php
  src/DDTrace/OpenTelemetry/Span.php
  src/DDTrace/OpenTelemetry/SpanBuilder.php
  src/DDTrace/OpenTracer/Tracer.php
  src/DDTrace/OpenTracer1/Tracer.php
  src/DDTrace/ScopeManager.php
  src/DDTrace/Tracer.php
  src/ddtrace_php_api.stubs.php
Labels: cat:integration, tracing

#2836 Blocking from a hook is not stopping code execution
  appsec/tests/extension/push_params_block_02.phpt
  appsec/tests/extension/push_params_block_03.phpt
  appsec/tests/extension/push_params_redirect_01.phpt
  appsec/tests/extension/push_params_redirect_02.phpt
  zend_abstract_interface/sandbox/php7/sandbox.c
  zend_abstract_interface/sandbox/php8/sandbox.c
  zend_abstract_interface/sandbox/sandbox.h
Labels: tracing, area:asm

#3019 fix(prof): crash on PHP 8.4
  profiling/src/php_ffi.c
Labels: cat:app-crash, profiling

#3021 Fix appsec lint
  appsec/src/extension/commands_helpers.c
  appsec/src/extension/network.c
Labels: tracing, area:asm

#3025 Fix SpanLink::fromHeaders() crash with no or invalid propagated tags
  ext/ddtrace.c
  tests/ext/distributed_tracing/distributed_trace_span_link_from_headers_invalid_tags.phpt
Labels: crashtracker-identified

#3027 [ASM] Strip new line from version on CMake
  appsec/CMakeLists.txt
Labels: area:asm

#3032 style: cargo clippy --fix and fmt on Rust v1.84
  .circleci/continue_config.yml
  config.w32
  docker-compose.yml
  profiling/src/allocation.rs
  profiling/src/bindings/mod.rs
  profiling/src/exception.rs
  profiling/src/profiling/stack_walking.rs
  profiling/src/sapi.rs
  profiling/src/thin_str.rs
  tests/randomized/lib/docker-compose.yml
Labels: profiling, tracing

#2969 feat(profiling) support new ZendMM api
  profiling/build.rs
  profiling/src/allocation/allocation_ge84.rs
  profiling/src/allocation/allocation_le83.rs
  profiling/src/allocation/mod.rs
  profiling/src/bindings/mod.rs
  profiling/src/config.rs
  profiling/src/lib.rs
Labels: profiling

#3038 fix(prof): PHP 8.4 crash with opcache optimizer
  profiling/src/profiling/stack_walking.rs
Labels: cat:app-crash, profiling

#3049 fix(profiler) guard `VERSION` against CRLF characters
  profiling/build.rs
  profiling/src/lib.rs
Labels: profiling

#3048 build(prof): bump `libdatadog` to version `15`
  .github/workflows/prof_correctness.yml
  Cargo.lock
  profiling/Cargo.toml
  profiling/src/profiling/uploader.rs
Labels: ci, profiling

#3052 build(prof): update dependencies
  Cargo.lock
Labels: profiling

#3053 Skip non-linux OCI package creation
  .gitlab/prepare-oci-package.sh
Labels: ci
